begin;
create temp table nearby_ids as select gen_random_uuid() actor, gen_random_uuid() stranger, gen_random_uuid() org, gen_random_uuid() listing;
create temp table nearby_checks(name text);
create function pg_temp.nearby_check(ok boolean, label text) returns void language plpgsql as $$
begin if not coalesce(ok,false) then raise exception 'FAIL: %',label; end if; insert into nearby_checks values(label); end $$;
do $$ declare f nearby_ids; begin select * into f from nearby_ids;
 insert into auth.users(id,email) values(f.actor,'nearby-owner@example.invalid'),(f.stranger,'nearby-stranger@example.invalid');
 insert into orgs(id,name,plan) values(f.org,'Synthetic reviewed places','pro');
 insert into memberships(user_id,org_id,role) values(f.actor,f.org,'owner');
 insert into listings(id,org_id,agent_id,address,details) values(f.listing,f.org,f.actor,'Synthetic property','{"floorplan_asset_id":"unchanged","floor_measurements_v1":{"private":"unchanged"},"amenities":"Existing features"}');
end $$;
grant all on nearby_ids,nearby_checks to service_role;
set role service_role;
do $$ declare f nearby_ids; r jsonb; original_details jsonb; refused boolean; begin select * into f from nearby_ids;
 select details into original_details from listings where id=f.listing;
 r:=public.save_listing_facts(f.actor,f.org,f.listing,'{}','{}','{"nearbyAttractions":{"present":false,"value":null}}','{"nearbyAttractions":"Apple Maps: Synthetic park · approx. 0.5 mi"}');
 perform pg_temp.nearby_check(r->'details'->>'nearbyAttractions'='Apple Maps: Synthetic park · approx. 0.5 mi','Reviewed nearby note round-trips');
 perform pg_temp.nearby_check((r->'details')-'nearbyAttractions'=original_details and original_details ? 'amenities' and original_details ? 'floor_measurements_v1','Nearby edit preserves every prior detail, including private measurements');
 refused:=false;
 begin perform public.save_listing_facts(f.actor,f.org,f.listing,'{}','{}','{"nearbyAttractions":{"present":false,"value":null}}','{"nearbyAttractions":"Stale losing note"}'); exception when sqlstate 'PT409' then refused:=true; end;
 perform pg_temp.nearby_check(refused,'Stale nearby edit conflicts');
 refused:=false;
 begin perform public.save_listing_facts(f.actor,f.org,f.listing,'{}','{}',jsonb_build_object('nearbyAttractions',jsonb_build_object('present',true,'value','Apple Maps: Synthetic park · approx. 0.5 mi')),jsonb_build_object('nearbyAttractions',repeat('x',501))); exception when sqlstate '22023' then refused:=true; end;
 perform pg_temp.nearby_check(refused,'Oversized nearby note refuses before write');
 refused:=false;
 begin perform public.save_listing_facts(f.stranger,f.org,f.listing,'{}','{}',jsonb_build_object('nearbyAttractions',jsonb_build_object('present',true,'value','Apple Maps: Synthetic park · approx. 0.5 mi')),'{"nearbyAttractions":"Foreign actor"}'); exception when sqlstate '42501' then refused:=true; end;
 perform pg_temp.nearby_check(refused,'Unrelated account cannot save nearby note');
 r:=public.save_listing_facts(f.actor,f.org,f.listing,'{}','{}',jsonb_build_object('nearbyAttractions',jsonb_build_object('present',true,'value','Apple Maps: Synthetic park · approx. 0.5 mi')),'{"nearbyAttractions":null}');
 perform pg_temp.nearby_check(not(r->'details' ? 'nearbyAttractions'),'Explicit clear removes only nearby note');
end $$;
reset role;
select jsonb_build_object('passed',true,'assertions',count(*)) from nearby_checks;
rollback;
