\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_audit'or inet_server_addr()is not null then raise exception 'Run only in the owned socket-only rendprop_audit fixture';end if;end$$;
create temp table client_checks(name text primary key,passed boolean not null);
create function pg_temp.ok(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'CLIENT FAIL: %',label;end if;insert into client_checks values(label,true);end$$;
create function pg_temp.denied(command text,prefix text,label text)returns void language plpgsql as $$declare message text;begin begin execute command;exception when others then message:=sqlerrm;end;perform pg_temp.ok(message like prefix||'%',label);end$$;
-- Test setup uses the actual confirmation RPCs; it never marks a typed
-- recipient verified by direct DML. Only fixture timestamps advance to avoid
-- making a real recipient click multiple emails inside one minute.
create function pg_temp.verify_contact(actor uuid,org uuid,listing uuid)returns void language plpgsql security definer set search_path='' as $$
declare nonce text:=replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','');begin
 if current_database()<>'rendprop_audit'or inet_server_addr()is not null then raise exception 'Fixture only';end if;
 update public.client_recipient_verifications set created_at=created_at-interval '2 minutes',expires_at=expires_at-interval '2 minutes'where listing_id=listing;
 perform public.client_recipient_verification_request(actor,org,listing,nonce);
 if not public.client_recipient_verification_consume(nonce)then raise exception 'Fixture recipient confirmation failed';end if;
end$$;
create temp table fixture(actor uuid,org uuid,other_actor uuid,other_org uuid,marketing uuid,agent uuid,listing uuid,other_listing uuid,photo uuid,wrong_photo uuid,job uuid,render uuid,lead uuid);
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();m uuid:=gen_random_uuid();ag uuid:=gen_random_uuid();o uuid;other uuid;l uuid:=gen_random_uuid();ol uuid:=gen_random_uuid();p uuid:=gen_random_uuid();wp uuid:=gen_random_uuid();j uuid:=gen_random_uuid();r uuid:=gen_random_uuid();begin
 insert into auth.users(id,email,is_anonymous)values(a,'photographer@fixture.invalid',false),(b,'other@fixture.invalid',false),(m,'marketing@fixture.invalid',false),(ag,'agent@fixture.invalid',false);
 select org_id into o from memberships where user_id=a;select org_id into other from memberships where user_id=b;
 -- Recipient delivery fixtures already own hosted media; trial admission is
 -- covered separately. Explicit manual authority admits these synthetic tours.
 update orgs set plan='pro',plan_source='manual',plan_expires_at=null where id in(o,other);
 insert into memberships(user_id,org_id,role)values(m,o,'marketing'),(ag,o,'agent');
 insert into listings(id,org_id,agent_id,address)values(l,o,a,'Synthetic client listing'),(ol,other,b,'Other synthetic property');
 insert into capture_assets(id,listing_id,kind,bucket,storage_key,uploaded)values(p,l,'photo','renders','renders/'||o||'/'||l||'/contact-'||p||'.jpg',true),(wp,ol,'photo','renders','renders/'||other||'/'||ol||'/contact-'||wp||'.jpg',true);
 insert into render_jobs(id,listing_id,tier,status)values(j,l,'smooth','completed');
 insert into renders(id,job_id,listing_id,slug,duration_s,published_at)values(r,j,l,'synthetic-client-tour',5,now());
 insert into fixture values(a,o,b,other,m,ag,l,ol,p,wp,j,r,gen_random_uuid());
end$$;
grant all on client_checks to service_role,anon,authenticated;
grant select on fixture to service_role,anon,authenticated;
select pg_temp.ok(not has_table_privilege(role,'public.listing_client_contacts','select')and not has_table_privilege(role,'public.client_lead_deliveries','select'),'private tables deny '||role)from unnest(array['anon','authenticated'])role;
select pg_temp.ok(not has_function_privilege(role,'public.listing_client_contact_put(uuid,uuid,uuid,integer,boolean,jsonb,text,boolean,uuid)','execute')and not has_function_privilege(role,'public.client_lead_resend(uuid,uuid,uuid,uuid,text)','execute'),'contact and resend RPCs deny '||role)from unnest(array['anon','authenticated'])role;
select pg_temp.ok((select bool_and(real_estate_role is null)from profiles where id in(select actor from fixture union select other_actor from fixture)),'new accounts explicitly choose a professional role');
create temp table adoption_fixture(source uuid,target uuid,org uuid,operation uuid,kind text);
do $$declare source uuid;target uuid;org uuid;kind text;begin
 for kind in select unnest(array['null_target','existing_target','no_source_choice','promoted_source'])loop
  source:=gen_random_uuid();target:=gen_random_uuid();
  insert into auth.users(id,email,is_anonymous)values(source,null,true),(target,kind||'@fixture.invalid',false);
  select org_id into org from memberships where user_id=source;
  if kind<>'no_source_choice'then update profiles set real_estate_role='photographer_videographer'where id=source;end if;
  if kind='existing_target'then update profiles set real_estate_role='agent'where id=target;end if;
  if kind='promoted_source'then update auth.users set is_anonymous=false where id=source;end if;
  insert into adoption_fixture values(source,target,org,gen_random_uuid(),kind);
 end loop;
end$$;
grant select on adoption_fixture to service_role;
set local role service_role;
do $$declare f record;begin
 for f in select * from adoption_fixture where kind<>'promoted_source'loop
  perform adopt_anonymous_org(f.target,f.source,f.org,f.operation);
  perform pg_temp.ok((select real_estate_role is not distinct from case f.kind when 'null_target'then 'photographer_videographer'when 'existing_target'then 'agent'else null end from profiles where id=f.target),'verified adoption preserves role: '||f.kind);
  perform pg_temp.ok(exists(select 1 from anonymous_adoption_receipts where operation_id=f.operation and source_user_id=f.source and destination_user_id=f.target),'role copy stays bound to durable adoption receipt: '||f.kind);
  if f.kind='null_target'then
   perform set_real_estate_role(f.target,'agent');
   perform adopt_anonymous_org(f.target,f.source,f.org,f.operation);
   perform pg_temp.ok((select real_estate_role='agent'from profiles where id=f.target),'adoption receipt replay never overwrites later explicit role');
  end if;
 end loop;
 select * into f from adoption_fixture where kind='promoted_source';
 perform pg_temp.denied(format('select adopt_anonymous_org(%L,%L,%L,%L)',f.target,f.source,f.org,f.operation),'RP403:','promoted source cannot copy preference through forged adoption');
 perform pg_temp.ok((select real_estate_role is null from profiles where id=f.target)and not exists(select 1 from anonymous_adoption_receipts where operation_id=f.operation),'failed adoption leaves target preference and receipt unchanged');
end$$;
reset role;
set local role service_role;
do $$declare f record;c jsonb;r jsonb;begin select * into f from fixture;
 perform pg_temp.ok(listing_client_contact_get(f.actor,f.org,f.listing)is null,'absent client contact is explicit null');
 c:=listing_client_contact_put(f.actor,f.org,f.listing,0,true,'{"name":"Client Agent","email":"public@fixture.invalid","brokerage":"Synthetic Realty"}',' PRIVATE@fixture.invalid ',true,f.photo);
 perform pg_temp.ok(c->>'revision'='1'and c->>'recipient_email'='private@fixture.invalid'and c->>'photo_asset_id'=f.photo::text,'save normalizes private email and binds uploaded photo');
 perform pg_temp.ok(listing_client_contact_get(f.marketing,f.org,f.listing)=c,'marketing may read existing protected client contact');
 r:=set_real_estate_role(f.marketing,'photographer_videographer');
 perform pg_temp.ok(r->>'real_estate_role'='photographer_videographer'and(select role='marketing'from memberships where user_id=f.marketing and org_id=f.org),'product preference never elevates marketing permissions');
 perform pg_temp.denied(format('select listing_client_contact_put(%L,%L,%L,1,true,%L::jsonb,%L,true,null)',f.marketing,f.org,f.listing,'{"name":"No"}','bad@fixture.invalid'),'RP403:','marketing cannot edit client contact');
 perform pg_temp.denied(format('select listing_client_contact_get(%L,%L,%L)',f.other_actor,f.org,f.listing),'RP404:','nonmember cannot read private client recipient');
 perform pg_temp.denied(format('select listing_client_contact_get(%L,%L,%L)',f.actor,f.other_org,f.listing),'RP404:','explicit wrong workspace cannot read contact');
 perform pg_temp.denied(format('select listing_client_contact_put(%L,%L,%L,0,true,%L::jsonb,%L,true,null)',f.actor,f.org,f.listing,'{"name":"Stale"}','stale@fixture.invalid'),'RP409:','stale revision cannot overwrite office edits');
 perform pg_temp.denied(format('select listing_client_contact_put(%L,%L,%L,1,true,%L::jsonb,%L,true,%L)',f.actor,f.org,f.listing,'{"name":"Client"}','private@fixture.invalid',f.wrong_photo),'RP400:','other workspace headshot cannot be referenced');
 perform pg_temp.denied(format('select listing_client_contact_put(%L,%L,%L,1,true,%L::jsonb,%L,true,null)',f.actor,f.org,f.listing,'{"name":"Client","avatar_url":"https://other.invalid/photo.jpg"}','private@fixture.invalid'),'RP400:','arbitrary headshot URLs cannot bypass upload fence');
 perform pg_temp.denied(format('select listing_client_contact_put(%L,%L,%L,1,true,%L::jsonb,%L,true,null)',f.actor,f.org,f.listing,'{"name":"Client","recipient_email":"leak@fixture.invalid"}','private@fixture.invalid'),'RP400:','private recipient cannot be inserted in public card');
 perform pg_temp.denied(format('select set_real_estate_role(%L,%L)',f.actor,'admin'),'RP400:','unknown product role cannot become permission role');
end$$;
reset role;
set local role service_role;
select pg_temp.verify_contact(actor,org,listing)from fixture;
reset role;
-- A lead recorded before assignment stays unsent, then exposes a manual send.
do $$declare f record;old_lead uuid:=gen_random_uuid();c jsonb;s jsonb;begin
 select * into f from fixture;
 update listing_client_contacts set enabled=false where listing_id=f.listing;
 insert into leads(id,listing_id,org_id,render_id,name,extra)values(old_lead,f.listing,f.org,f.render,'Older Buyer','{"preferred_date":"2026-10-04"}');
 perform pg_temp.ok(not exists(select 1 from client_lead_deliveries where lead_id=old_lead),'inquiry before forwarding has no automatic client email');
 update listing_client_contacts set enabled=true where listing_id=f.listing;
 set local role service_role;
 s:=client_lead_delivery_list(f.actor,f.org,array[old_lead])->old_lead::text;
 perform pg_temp.ok(s->>'state'='skipped'and s->>'recipient_email'is null and s->>'client_name'is null and s->>'last_attempt_at'is null and s->>'sent_at'is null and s->>'current_recipient_email'='private@fixture.invalid'and(s->>'can_resend')::boolean,'older inquiry becomes truthfully manually forwardable after client assignment');
 perform pg_temp.ok(not exists(select 1 from client_lead_deliveries where lead_id=old_lead),'assignment never automatically sends historical inquiry');
 s:=client_lead_delivery_list(f.marketing,f.org,array[old_lead])->old_lead::text;
 perform pg_temp.ok(not(s->>'can_resend')::boolean,'marketing reads older inquiry status without a send action');
 reset role;
 delete from leads where id=old_lead;
end$$;
insert into leads(id,listing_id,org_id,render_id,name,email,phone,extra)select lead,listing,org,render,'Synthetic Buyer','buyer@fixture.invalid','555-555-0101','{"message":"Please arrange a showing.","preferred_date":"2026-10-03","preferred_time":"15:30","party_size":4}'from fixture;
do $$declare f record;d record;begin select * into f from fixture;
 select * into d from client_lead_deliveries where lead_id=f.lead;
 perform pg_temp.ok(d.recipient_email='private@fixture.invalid'and d.email_text like '%buyer@fixture.invalid%'and d.email_text like '%555-555-0101%'and d.email_text like '%Please arrange a showing.%'and d.email_text like '%2026-10-03%'and d.email_text like '%15:30%'and d.email_text like '%Party Size: 4%'and d.email_text like '%https://rendprop.com/f/synthetic-client-tour%','automatic client email includes full inquiry without a login');
 perform pg_temp.ok((select count(*)=1 from notification_outbox where client_delivery_id=d.id and user_id is null and to_email=d.recipient_email and channel='email'),'lead insert queues one independent external email');
 perform pg_temp.ok((select count(*)=1 from notification_outbox where category='lead_received'and org_id=f.org and dedupe_key='lead_received:'||f.lead||':'||f.actor),'photographer alert remains separate from client email');
 perform pg_temp.ok((select count(*)=1 from leads where org_id=f.org and id=f.lead),'photographer inbox preserves lead');
end$$;
set local role service_role;
do $$declare f record;c jsonb;d record;o record;payload jsonb;replay jsonb;begin select * into f from fixture;
 select * into d from client_lead_deliveries where lead_id=f.lead;
 select * into o from notification_claim_batch(200)where client_delivery_id=d.id;
 payload:=client_lead_prepare(d.id,o.id,'Studio <notify@fixture.invalid>');
 perform pg_temp.ok(payload->>'to'='private@fixture.invalid'and payload->>'idempotency_key'='client-lead/'||d.id,'provider payload uses immutable recipient and unique delivery key');
 replay:=client_lead_prepare(d.id,o.id,'Changed <else@fixture.invalid>');
 perform pg_temp.ok(payload=replay,'retry freezes sender and complete provider payload');
 perform notification_mark(o.id,'sent',null,'provider-synthetic');
 perform notification_mark(o.id,'sent',null,'provider-synthetic');
 perform pg_temp.ok((select state='email_sent'and sent_at is not null from client_lead_deliveries where id=d.id),'accepted provider email has permanent honest status');
 perform pg_temp.ok((select count(*)=1 from notification_log where provider_message_id='provider-synthetic'),'repeated acknowledgment cannot double-log client email');
 perform pg_temp.denied(format('select client_lead_resend(%L,%L,%L,%L,%L)',f.marketing,f.org,f.lead,gen_random_uuid(),'private@fixture.invalid'),'RP403:','marketing cannot resend');
 perform pg_temp.denied(format('select client_lead_resend(%L,%L,%L,%L,%L)',f.actor,f.org,f.lead,gen_random_uuid(),'wrong@fixture.invalid'),'RP409:','wrong confirmation email cannot redirect inquiry');
 perform pg_temp.denied(format('select client_lead_resend(%L,%L,%L,%L,%L)',f.actor,f.org,f.lead,gen_random_uuid(),'private@fixture.invalid'),'RP429:','resend cooldown prevents double tap');
 c:=listing_client_contact_put(f.agent,f.org,f.listing,1,true,'{"name":"New Client"}','new@fixture.invalid',true,f.photo);
 perform pg_temp.verify_contact(f.agent,f.org,f.listing);
 payload:=client_delivery_summary(f.lead);
 perform pg_temp.ok(payload->>'recipient_email'='private@fixture.invalid'and payload->>'current_recipient_email'='new@fixture.invalid','last sent recipient stays historical and confirmation sees new recipient');
end$$;
reset role;
update client_lead_deliveries set created_at=now()-interval '2 minutes';
set local role service_role;
do $$declare f record;r jsonb;request uuid:=gen_random_uuid();d record;o record;c jsonb;begin select * into f from fixture;
 r:=client_lead_resend(f.agent,f.org,f.lead,request,'new@fixture.invalid');
 perform pg_temp.ok(r#>>'{delivery,state}'='queued'and r#>>'{delivery,recipient_email}'='new@fixture.invalid','explicit resend creates new immutable recipient');
 perform pg_temp.ok(client_lead_resend(f.agent,f.org,f.lead,request,'new@fixture.invalid')=r,'same request replay does not enqueue twice');
 perform pg_temp.ok((select count(*)=2 from client_lead_deliveries where lead_id=f.lead),'resend request has one delivery record');
 select * into d from client_lead_deliveries where lead_id=f.lead and request_id=request;
 select * into o from notification_claim_batch(200)where client_delivery_id=d.id;
 perform client_lead_prepare(d.id,o.id,'notify@fixture.invalid');
 c:=listing_client_contact_put(f.actor,f.org,f.listing,2,false,'{"name":"New Client"}','new@fixture.invalid',true,f.photo);
 perform pg_temp.ok(c->>'enabled'='false'and c->>'recipient_email'='new@fixture.invalid'and c->>'photo_asset_id'=f.photo::text,'disable preserves saved client fields and photo');
 perform pg_temp.ok(client_lead_prepare(d.id,o.id,'notify@fixture.invalid')is null,'disabled routing cancels already claimed email before dispatch');
 perform notification_mark(o.id,'failed','Synthetic in-flight provider failure',null);
 perform pg_temp.ok((select state='skipped'from client_lead_deliveries where id=d.id)and(select state='skipped'from notification_outbox where id=o.id),'canceled in-flight failure never retries');
 perform notification_mark(o.id,'sent',null,'late-provider-accepted');
 perform notification_mark(o.id,'sent',null,'late-provider-accepted');
 perform pg_temp.ok((select state='email_sent'and recipient_email='new@fixture.invalid'and reason like '%cannot be recalled%'from client_lead_deliveries where id=d.id)and(select count(*)=1 from notification_log where provider_message_id='late-provider-accepted'),'verified in-flight acceptance retains truthful original recipient once');
 perform pg_temp.ok((select state='sent'and claimed_at is null from notification_outbox where id=o.id),'late acceptance records history without requeueing');
 c:=listing_client_contact_put(f.actor,f.org,f.listing,3,true,'{"name":"New Client"}','new@fixture.invalid',true,f.photo);
end$$;
reset role;
update client_lead_deliveries set created_at=now()-interval '2 minutes';
set local role service_role;
select client_lead_resend(actor,org,lead,gen_random_uuid(),'new@fixture.invalid')from fixture;
reset role;
-- Revocation before preparation cannot be revived by a stale worker receipt.
update listings set deleted_at=now()where id=(select listing from fixture);
set local role service_role;
do $$declare o record;begin
 select * into o from notification_outbox where category='client_lead_received'and state='skipped'and client_delivery_id in(select id from client_lead_deliveries where email_from is null)limit 1;
 perform notification_mark(o.id,'sent',null,'unprepared-stale');
 perform pg_temp.ok((select state='skipped'from notification_outbox where id=o.id)and not exists(select 1 from notification_log where provider_message_id='unprepared-stale'),'unprepared canceled email ignores stale acceptance');
end$$;
reset role;
select pg_temp.ok(not exists(select 1 from client_lead_deliveries where listing_id=(select listing from fixture)and state in('queued','sending')),'soft deletion cancels pending client emails');
set local role service_role;
select pg_temp.denied('select listing_client_contact_get(actor,org,listing)from fixture','RP404:','deleted listing loses private contact access');
reset role;
delete from leads where id=(select lead from fixture);
select pg_temp.ok(not exists(select 1 from client_lead_deliveries),'deleting lead removes private delivery history');
select pg_temp.ok(not exists(select 1 from notification_outbox where category='client_lead_received'),'deleting lead removes external email snapshots');
do $$declare f record;lid uuid:=gen_random_uuid();leadid uuid:=gen_random_uuid();rid uuid:=gen_random_uuid();jid uuid:=gen_random_uuid();d record;o record;begin
 select * into f from fixture;
 insert into listings(id,org_id,agent_id,address)values(lid,f.other_org,f.other_actor,'Deletion authority fixture');
 insert into render_jobs(id,listing_id,tier,status)values(jid,lid,'smooth','completed');
 insert into renders(id,job_id,listing_id,slug,duration_s,published_at)values(rid,jid,lid,'deletion-authority-fixture',5,now());
 set local role service_role;
 perform listing_client_contact_put(f.other_actor,f.other_org,lid,0,true,'{"name":"Deletion Client"}','deletion@fixture.invalid',true,null);
 perform pg_temp.verify_contact(f.other_actor,f.other_org,lid);
 reset role;
 insert into leads(id,org_id,listing_id,render_id,name)values(leadid,f.other_org,lid,rid,'Deletion Buyer');
 select * into d from client_lead_deliveries where lead_id=leadid;
 set local role service_role;
 select * into o from notification_claim_batch(200)where client_delivery_id=d.id;
 reset role;
 insert into deletion_requests(user_id,status)values(f.other_actor,'pending');
 perform pg_temp.ok((select state='skipped'from notification_outbox where id=o.id),'account deletion intent immediately cancels claimed client email');
 set local role service_role;
 perform pg_temp.ok(client_lead_prepare(d.id,o.id,'notify@fixture.invalid')is null,'deleting owner cannot dispatch prepared client email');
 reset role;
 delete from deletion_requests where user_id=f.other_actor;
 update orgs set deleted_at=now()where id=f.other_org;
 insert into leads(id,org_id,listing_id,render_id,name)values(gen_random_uuid(),f.other_org,lid,rid,'After deletion Buyer');
 perform pg_temp.ok((select count(*)=1 from client_lead_deliveries where listing_id=lid),'deleted workspace never queues new client emails');
 delete from leads where listing_id=lid;
end$$;
do $$declare a uuid:=gen_random_uuid();o uuid;lid uuid:=gen_random_uuid();rid uuid:=gen_random_uuid();jid uuid:=gen_random_uuid();leadid uuid;leadids uuid[]:='{}';i integer;begin
 insert into auth.users(id,email,is_anonymous)values(a,'rate-owner@fixture.invalid',false);
 select org_id into o from memberships where user_id=a;
 update orgs set plan='pro',plan_source='manual',plan_expires_at=null where id=o;
 insert into listings(id,org_id,agent_id,address)values(lid,o,a,'Manual forwarding rate fixture');
 insert into render_jobs(id,listing_id,tier,status)values(jid,lid,'smooth','completed');
 insert into renders(id,job_id,listing_id,slug,duration_s,published_at)values(rid,jid,lid,'manual-forwarding-rate-fixture',5,now());
 for i in 1..21 loop leadid:=gen_random_uuid();leadids:=array_append(leadids,leadid);insert into leads(id,org_id,listing_id,render_id,name)values(leadid,o,lid,rid,'Older inquiry '||i);end loop;
 set local role service_role;
 perform listing_client_contact_put(a,o,lid,0,true,'{"name":"Rate Client"}','rate@fixture.invalid',true,null);
 perform pg_temp.verify_contact(a,o,lid);
 for i in 1..20 loop perform client_lead_resend(a,o,leadids[i],gen_random_uuid(),'rate@fixture.invalid');end loop;
 perform pg_temp.ok((select count(*)=20 from client_lead_deliveries where org_id=o and requested_by=a),'bounded manual forwarding permits twenty distinct inquiries');
 perform pg_temp.denied(format('select client_lead_resend(%L,%L,%L,%L,%L)',a,o,leadids[21],gen_random_uuid(),'rate@fixture.invalid'),'RP429:','manual forwarding rate caps different inquiries in same window');
 reset role;
 update client_lead_deliveries set created_at=now()-interval '11 minutes'where org_id=o;
 set local role service_role;
 perform client_lead_resend(a,o,leadids[21],gen_random_uuid(),'rate@fixture.invalid');
 perform pg_temp.ok((select count(*)=21 from client_lead_deliveries where org_id=o),'manual forwarding allowance renews after the bounded window');
 reset role;
end$$;
select count(*) as passed from client_checks;
select name,passed from client_checks order by name;
rollback;
