\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_privacy_audit'or inet_server_addr()is not null then raise exception 'Use only the owned socket-only privacy fixture';end if;end$$;
create temp table privacy_cleanup_checks(label text primary key,passed boolean not null);
create function pg_temp.ok(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'CLEANUP FAIL: %',label;end if;insert into privacy_cleanup_checks values(label,true);end$$;
create function pg_temp.denied(command text,prefix text,label text)returns void language plpgsql as $$declare problem text;begin begin execute command;exception when others then problem:=sqlerrm;end;if problem not like prefix||'%' or problem is null then raise exception 'CLEANUP DENIAL: % expected %, got %',label,prefix,coalesce(problem,'no failure');end if;perform pg_temp.ok(true,label);end$$;
grant all on privacy_cleanup_checks to service_role,anon,authenticated;
create temp table fixture(a uuid,b uuid,m uuid,o uuid,other uuid,l uuid,lead uuid,photo uuid,key text);
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();m uuid:=gen_random_uuid();o uuid;other uuid;l uuid:=gen_random_uuid();p uuid:=gen_random_uuid();begin
 insert into auth.users(id,email,is_anonymous)values(a,'owner@fixture.invalid',false),(b,'other@fixture.invalid',false),(m,'marketing@fixture.invalid',false);
 select org_id into o from memberships where user_id=a;select org_id into other from memberships where user_id=b;
 insert into memberships(user_id,org_id,role)values(m,o,'marketing');
 insert into listings(id,org_id,agent_id,address)values(l,o,a,'Private cleanup fixture');
 insert into capture_assets(id,listing_id,kind,bucket,storage_key,uploaded,transport_version)values(p,l,'photo','renders','renders/'||o||'/'||l||'/'||p||'.jpg',true,2);
 insert into fixture values(a,b,m,o,other,l,gen_random_uuid(),p,'ai-router/'||o||'/image.edit/'||gen_random_uuid()||'.jpg');
end$$;
grant select on fixture to service_role,anon,authenticated;
select pg_temp.ok(not has_table_privilege(r,table_name,'insert,update,delete'),'cleanup table denies DML '||r||' '||table_name)
 from unnest(array['anon','authenticated','service_role'])r cross join unnest(array['public.private_ai_outputs','public.privacy_cleanup_jobs','public.privacy_runtime'])table_name;
select pg_temp.ok(not has_function_privilege(r,fn,'execute'),'cleanup RPC denies '||r||' '||fn)
 from unnest(array['anon','authenticated'])r cross join unnest(array['public.register_private_ai_output(uuid,uuid,uuid,text,text,bigint)','public.delete_workspace_lead(uuid,uuid,uuid)','public.privacy_cleanup_claim(uuid)','public.privacy_cleanup_due()','public.privacy_cleanup_finish(uuid,uuid,jsonb,text)'])fn;
set local role service_role;
do $$declare f record;r jsonb;begin select * into f from fixture;
 r:=register_private_ai_output(f.a,f.o,f.l,'renders',f.key,12345);
 perform pg_temp.ok(r->>'ok'='true'and r->>'key'=f.key,'output intent records exact server key before write');
 perform pg_temp.ok(register_private_ai_output(f.a,f.o,f.l,'renders',f.key,12345)=r,'same output intent replays immutably');
 perform register_private_ai_output(f.a,f.o,null,'renders',f.key||'-account-only',12345);
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12346)',f.a,f.o,f.l,'renders',f.key),'RP409:','output replay cannot change byte receipt');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.b,f.o,f.l,'renders',f.key),'RP403:','foreign actor cannot journal another org output');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.other,f.l,'renders',f.key),'RP403:','foreign org cannot receive output receipt');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.o,gen_random_uuid(),'renders',f.key||'x'),'RP404:','unowned listing cannot receive output receipt');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.o,f.l,'uploads',f.key),'RP400:','wrong output bucket cannot be journaled');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.o,f.l,'renders','ai-router/'||f.other||'/image.edit/x.jpg'),'RP400:','foreign output prefix cannot be journaled');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.o,f.l,'renders','ai-router/'||f.o||'/../other/x.jpg'),'RP400:','path traversal cannot be journaled');
end$$;
reset role;
insert into leads(id,org_id,listing_id,phone,name,created_at)select lead,o,l,'+1 (727) 555-0101','Phone-only buyer',now()-interval '1 day'from fixture;
set local role service_role;
do $$declare f record;r jsonb;begin select * into f from fixture;
 perform pg_temp.denied(format('select delete_workspace_lead(%L,%L,%L)',f.b,f.o,f.lead),'RP403:','foreign actor cannot delete inquiry');
 perform pg_temp.denied(format('select delete_workspace_lead(%L,%L,%L)',f.m,f.o,f.lead),'RP403:','marketing cannot delete inquiry');
 perform pg_temp.denied(format('select delete_workspace_lead(%L,%L,%L)',f.a,f.other,f.lead),'RP403:','wrong selected org cannot delete inquiry');
 r:=delete_workspace_lead(f.a,f.o,f.lead);
 perform pg_temp.ok(r=jsonb_build_object('ok',true,'lead_id',f.lead,'deleted',true,'cleanup_pending',true),'lead deletion returns exact confirmed receipt');
 perform pg_temp.ok(not exists(select 1 from leads where id=f.lead),'deleted inquiry is absent');
 perform pg_temp.ok(not exists(select 1 from notification_outbox where payload#>>'{data,lead_id}'=f.lead::text),'deleted inquiry pending alert payload is erased');
 perform pg_temp.ok((select payload#>>'{ghl_targets,0,phone}'='+1 (727) 555-0101'and not(payload#>'{ghl_targets,0}'?'email')and payload#>>'{ghl_targets,0,org_id}'=f.o::text from privacy_cleanup_jobs where kind='lead'and source_id=f.lead),'phone-only legacy CRM cleanup survives local deletion');
 perform pg_temp.denied(format('select delete_workspace_lead(%L,%L,%L)',f.a,f.o,f.lead),'RP403:','absent inquiry never invents deletion confirmation');
end$$;
reset role;
set local role service_role;
do $$declare f record;j record;c jsonb;empty_payload jsonb:=jsonb_build_object('r2','[]'::jsonb,'stream_uids','[]'::jsonb,'ghl_targets','[]'::jsonb);begin select * into f from fixture;
 select * into j from privacy_cleanup_jobs where kind='lead'and source_id=f.lead;c:=privacy_cleanup_claim(j.id);
 perform pg_temp.ok(c->'payload'=j.payload,'lead cleanup claim retains exact legacy identity');
 perform privacy_cleanup_finish(j.id,(c->>'token')::uuid,j.payload,'Legacy cleanup transport unavailable.');
 perform pg_temp.ok((select payload=j.payload and remaining=j.payload and state='pending'from privacy_cleanup_jobs where id=j.id),'unacknowledged lead cleanup retains legacy identity');
 reset role;
 update privacy_cleanup_jobs set next_attempt_at=now()-interval '1 second'where id=j.id;
 set local role service_role;
 c:=privacy_cleanup_claim(j.id);
 perform privacy_cleanup_finish(j.id,(c->>'token')::uuid,empty_payload,'');
 perform pg_temp.ok((select state='completed'and payload=empty_payload and remaining=empty_payload from privacy_cleanup_jobs where id=j.id),'completed lead cleanup erases original email phone inventory');
 perform pg_temp.ok((select last_error is null from privacy_cleanup_jobs where id=j.id),'completed lead cleanup retains no error detail');
end$$;
reset role;
update listings set deleted_at=now()where id=(select l from fixture);
set local role service_role;
do $$declare f record;j record;begin select * into f from fixture;
 select * into j from privacy_cleanup_jobs where kind='listing'and source_id=f.l;
 perform pg_temp.ok(j.state='pending'and j.org_id=f.o,'listing deletion freezes owned cleanup intent');
 perform pg_temp.ok(j.payload->'r2'@>jsonb_build_array(jsonb_build_object('bucket','renders','key',f.key)),'listing cleanup includes raw output journal intent');
 perform pg_temp.ok(j.payload->'r2'@>jsonb_build_array(jsonb_build_object('bucket','renders','key','renders/'||f.o||'/'||f.l||'/'||f.photo||'.jpg')),'listing cleanup includes uploaded media');
 perform pg_temp.ok(privacy_cleanup_claim(j.id)is null,'cleanup waits for admitted writes to drain');
 perform pg_temp.denied(format('select register_private_ai_output(%L,%L,%L,%L,%L,12345)',f.a,f.o,f.l,'renders',f.key||'new'),'RP404:','deleted listing blocks fresh output write intent');
end$$;
reset role;
update privacy_cleanup_jobs set not_before=now()-interval '1 second'where kind='listing';
set local role service_role;
do $$declare f record;j record;c jsonb;r jsonb;begin select * into f from fixture;
 select * into j from privacy_cleanup_jobs where kind='listing'and source_id=f.l;
 c:=privacy_cleanup_claim(j.id);
 perform pg_temp.ok(c->>'id'=j.id::text and c->'payload'=j.payload,'cleanup lease returns exact frozen inventory');
 perform pg_temp.ok(privacy_cleanup_claim(j.id)is null,'concurrent cleanup cannot take active lease');
 perform pg_temp.denied(format('select privacy_cleanup_finish(%L,%L,%L::jsonb,%L)',j.id,gen_random_uuid(),jsonb_build_object('r2','[]'::jsonb,'stream_uids','[]'::jsonb,'ghl_targets','[]'::jsonb),''),'RP409:','stale cleanup token cannot acknowledge deletion');
 perform pg_temp.denied(format('select privacy_cleanup_finish(%L,%L,%L::jsonb,%L)',j.id,c->>'token',jsonb_build_object('r2',jsonb_build_array(jsonb_build_object('bucket','renders','key','renders/'||f.other||'/foreign.jpg')),'stream_uids','[]'::jsonb,'ghl_targets','[]'::jsonb),''),'RP403:','cleanup cannot retarget foreign object');
 perform pg_temp.denied(format('select privacy_cleanup_finish(%L,%L,%L::jsonb,%L)',j.id,c->>'token',j.payload||'{"other":[]}'::jsonb,''),'RP400:','unknown cleanup category cannot be dropped');
 r:=privacy_cleanup_finish(j.id,(c->>'token')::uuid,j.payload,'Unavailable synthetic transport');
 perform pg_temp.ok(r->>'cleanup_complete'='false'and(select remaining=payload and state='pending'from privacy_cleanup_jobs where id=j.id),'failed transport retains every target');
 perform pg_temp.ok(exists(select 1 from private_ai_outputs where listing_id=f.l and storage_key=f.key),'pending listing cleanup retains exact output journal');
end$$;
reset role;
update privacy_cleanup_jobs set next_attempt_at=now()-interval '1 second'where kind='listing';
set local role service_role;
do $$declare f record;j uuid;c jsonb;r jsonb;begin select * into f from fixture;
 select id into j from privacy_cleanup_jobs where kind='listing'and source_id=f.l;c:=privacy_cleanup_claim(j);
 r:=privacy_cleanup_finish(j,(c->>'token')::uuid,jsonb_build_object('r2','[]'::jsonb,'stream_uids','[]'::jsonb,'ghl_targets','[]'::jsonb),'Synthetic acknowledgments only; no objects were contacted.');
 perform pg_temp.ok(r->>'cleanup_complete'='true'and(select state='completed'and completed_at is not null from privacy_cleanup_jobs where id=j),'all acknowledged cleanup completes durable receipt');
 perform pg_temp.ok(not exists(select 1 from private_ai_outputs where listing_id=f.l and org_id=f.o),'completed listing cleanup prunes its exact output journals');
 perform pg_temp.ok(exists(select 1 from private_ai_outputs where listing_id is null and storage_key=f.key||'-account-only'),'listing completion preserves unrelated account output journal');
end$$;
reset role;
-- A genuinely solely-owned account receives both bounded output namespaces,
-- while a shared workspace is retained and never enumerated.
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();o uuid;other uuid;l uuid:=gen_random_uuid();r jsonb;begin
 insert into auth.users(id,email,is_anonymous)values(a,'deletion@fixture.invalid',false),(b,'shared@fixture.invalid',false);
 select org_id into o from memberships where user_id=a;select org_id into other from memberships where user_id=b;
 insert into memberships(user_id,org_id,role)values(a,other,'agent');
 insert into listings(id,org_id,agent_id,address)values(l,o,a,'Account deletion fixture');
 insert into leads(org_id,listing_id,phone,created_at)values(o,l,'7275550102',now()-interval '1 day');
 set local role service_role;
 r:=prepare_account_deletion(a,'uploads','renders');
 perform pg_temp.ok(r#>'{payload,r2_prefixes}'@>jsonb_build_array(jsonb_build_object('bucket','renders','org_id',o,'prefix','ai-router/'||o||'/','removed_count',0),jsonb_build_object('bucket','uploads','org_id',o,'prefix','presenter-private/'||o||'/','removed_count',0)),'account inventory includes both actual output buckets');
 perform pg_temp.ok(not exists(select 1 from jsonb_array_elements(r#>'{payload,r2_prefixes}')p where p->>'org_id'=other::text),'shared workspace never enters account output prefix inventory');
 perform pg_temp.ok(r#>'{payload,ghl_targets}'@>jsonb_build_array(jsonb_build_object('org_id',o,'phone','7275550102')),'account deletion retains phone-only legacy CRM target');
 perform pg_temp.ok(account_cleanup_prefixes_valid(r#>'{payload,r2_prefixes}',r#>'{payload,r2_prefixes}'),'unchanged owned prefix remains valid');
 perform pg_temp.denied(format('select finish_account_deletion(%L,%L,%L::jsonb,%L)',r->>'request_id',r->>'lease_token',jsonb_set(r->'payload','{r2_prefixes}','[]'),''),'RP409:','account output prefix waits for admitted write deadline');
 perform pg_temp.ok(not account_cleanup_prefixes_valid(r#>'{payload,r2_prefixes}',jsonb_build_array(jsonb_build_object('bucket','renders','org_id',other,'prefix','ai-router/'||other||'/','removed_count',0))),'account prefix cannot expand to shared or foreign org');
 reset role;
end$$;
select count(*)from privacy_cleanup_checks;
select 'PASS: cleanup inventory assertions; fixtures rolled back.';
rollback;
