\set ON_ERROR_STOP on
do $$ begin
 if current_database()<>'rendprop_spatial_audit' or current_setting('listen_addresses')<>'' or current_setting('data_directory') !~ '^/tmp/rendprop-spatial-db-[^/]+/cluster$' then raise exception 'spatial fixture refuses existing databases'; end if;
end $$;
begin;
create temp table _checks(label text primary key);
create function pg_temp.a(ok boolean,label text) returns void language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'spatial assertion failed: %',label; end if; insert into _checks values(label);
end $$;
create function pg_temp.denied(command text,expected text,label text) returns void language plpgsql as $$ begin
 begin execute command; raise exception 'fixture accepted forbidden operation'; exception when others then
 if sqlerrm not like expected then raise exception 'wrong failure for %: %',label,sqlerrm; end if; end; perform pg_temp.a(true,label);
end $$;
select pg_temp.a(to_regclass('public.spatial_jobs') is not null,'durable spatial table exists');
select pg_temp.denied('update spatial_runtime set max_seconds=60','new row for relation "spatial_runtime" violates check constraint%','unexecutable short provider profile rejected');
create temp table _fixture(actor uuid,other_actor uuid,marketing uuid,org uuid,listing uuid,capture uuid,job uuid,lease uuid,revision uuid);
insert into auth.users(id,email,raw_user_meta_data) values
 ('a0400000-0000-4000-8000-000000000001','spatial-owner@fixture.invalid','{}'),
 ('a0400000-0000-4000-8000-000000000002','spatial-other@fixture.invalid','{}'),
 ('a0400000-0000-4000-8000-000000000003','spatial-marketing@fixture.invalid','{}');
insert into _fixture select 'a0400000-0000-4000-8000-000000000001','a0400000-0000-4000-8000-000000000002','a0400000-0000-4000-8000-000000000003',org_id,
 'a0400000-0000-4000-8000-000000000004','a0400000-0000-4000-8000-000000000005',null,null,null from memberships where user_id='a0400000-0000-4000-8000-000000000001';
insert into memberships(user_id,org_id,role) select marketing,org,'marketing' from _fixture;
insert into listings(id,org_id,agent_id) select listing,org,actor from _fixture;
create function pg_temp.manifest() returns jsonb language sql as $$ select jsonb_build_object('status','complete','session_id',capture,'image_bytes',2000,'feature_point_observations',20,'frames',(select jsonb_agg('frames/'||lpad(i::text,6,'0')||'.json') from generate_series(1,20)g(i))) from _fixture $$;
create function pg_temp.create_job() returns jsonb language sql as $$select spatial_create(actor,listing,capture,capture,'Room',pg_temp.manifest()) from _fixture$$;
do $$ declare ns text;begin select nspname into ns from pg_namespace where oid=pg_my_temp_schema();execute format('grant usage on schema %I to service_role,anon,authenticated',ns);end $$;
grant select,insert,update on _checks,_fixture to service_role,anon,authenticated;
grant execute on all functions in schema pg_temp to service_role,anon,authenticated;
select pg_temp.a(not has_table_privilege('authenticated','spatial_jobs','SELECT,INSERT,UPDATE,DELETE'),'job Data API privileges denied');
select pg_temp.a(not has_table_privilege('anon','spatial_inputs','SELECT,INSERT,UPDATE,DELETE'),'input Data API privileges denied');
select pg_temp.a(not has_function_privilege('authenticated','spatial_publish(uuid,uuid)','EXECUTE'),'publish RPC not member callable');
select pg_temp.denied('select pg_temp.create_job()','RP403:%','explicit service-only guard');
set local role authenticated;
select pg_temp.denied('select pg_temp.create_job()','permission denied%','actual Data API role call denied');
reset role;
set local role service_role;
update _fixture set job=(pg_temp.create_job()->>'id')::uuid;
select pg_temp.a((select status='uploading' from spatial_jobs where id=(select job from _fixture)),'create commits uploading job');
select pg_temp.a((select (pg_temp.create_job()->>'id')::uuid=job from _fixture),'idempotency returns same job');
select pg_temp.denied('select spatial_create(actor,listing,capture,capture,''Other'',pg_temp.manifest()) from _fixture','RP409:%','idempotency refuses changed room');
select pg_temp.denied('select spatial_access(other_actor,listing,false) from _fixture','RP403:%','cross-tenant read denied');
select pg_temp.denied('select spatial_create(marketing,listing,gen_random_uuid(),gen_random_uuid(),''Room'',pg_temp.manifest()) from _fixture','RP403:%','marketing create denied');
select pg_temp.denied('select spatial_start(actor,job) from _fixture','RP409:%','start without inputs denied');
reset role;
insert into capture_assets(id,listing_id,kind,storage_key,bytes,bucket,uploaded,transport_version,content_type)
 select ('a0401000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,listing,'photo','uploads/'||org||'/'||listing||'/'||i||'.jpg',100,'uploads',true,2,'image/jpeg' from _fixture cross join generate_series(1,20)g(i);
insert into upload_reservations(asset_id,org_id,listing_id,actor_id,day,spec,held_bytes,spent_bytes,state,settled_at)
 select a.id,f.org,f.listing,f.actor,current_date,'{}',0,200,'completed',clock_timestamp() from capture_assets a join _fixture f on a.listing_id=f.listing;
create function pg_temp.frame(i integer) returns jsonb language sql as $$select jsonb_build_array(jsonb_build_object('ticket_id',('a0401000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'relative_path','images/'||lpad(i::text,6,'0')||'.jpg','frame',jsonb_build_object('session_id',capture,'image','images/'||lpad(i::text,6,'0')||'.jpg','timestamp',i,'raw_feature_points',jsonb_build_array(jsonb_build_object('id','1','position',jsonb_build_array(0,0,-1))),'tracking_state',jsonb_build_object('state','normal')))) from _fixture$$;
grant execute on function pg_temp.frame(integer) to service_role;
set local role service_role;
do $$ declare i integer;f record;begin select * into f from _fixture;for i in 1..20 loop perform spatial_attach_inputs(f.actor,f.job,pg_temp.frame(i));end loop;end $$;
select pg_temp.a((select count(*)=20 from spatial_inputs where job_id=(select job from _fixture)),'all twenty input rows attached');
select pg_temp.a((select spatial_attach_inputs(actor,job,pg_temp.frame(1))->>'status'='uploading' from _fixture),'input exact replay accepted');
select pg_temp.denied('select spatial_attach_inputs(actor,job,jsonb_set(pg_temp.frame(1),''{0,frame,session_id}'',''"a0409999-0000-4000-8000-000000000001"'')) from _fixture','RP400:%','cross-session sidecar rejected');
select pg_temp.denied('select spatial_start(actor,job) from _fixture','RP503:%','unconfigured generation fails explicitly');
update spatial_jobs set capture_manifest=jsonb_set(capture_manifest,'{image_bytes}','2001') where id=(select job from _fixture);
select pg_temp.denied('select spatial_start(actor,job) from _fixture','RP400:%','observed image bytes validated before spending');
update spatial_jobs set capture_manifest=jsonb_set(capture_manifest,'{image_bytes}','2000') where id=(select job from _fixture);
update spatial_inputs set frame=jsonb_set(frame,'{timestamp}','2') where job_id=(select job from _fixture) and relative_path='images/000001.jpg';
select pg_temp.denied('select spatial_start(actor,job) from _fixture','RP400:%','duplicate timestamps rejected before spending');
update spatial_inputs set frame=jsonb_set(frame,'{timestamp}','1') where job_id=(select job from _fixture) and relative_path='images/000001.jpg';
update spatial_runtime set enabled=true,daily_budget_cents=600,org_monthly_budget_cents=600;
select pg_temp.a((select spatial_start(actor,job)->>'status'='queued' from _fixture),'configured start queues');
select pg_temp.a((select spatial_start(actor,job)->>'status'='queued' from _fixture),'queue retry is idempotent');
select pg_temp.a((select sum(committed_cents)=1200 from spatial_budget_windows),'one global and one org reservation consumed');
select pg_temp.denied('select spatial_attach_inputs(actor,job,pg_temp.frame(1)) from _fixture','RP409:%','queued inputs immutable');
update _fixture set lease=(spatial_claim('a0402000-0000-4000-8000-000000000001')->>'lease_token')::uuid;
select pg_temp.a((select lease is not null from _fixture),'worker claim returns lease');
select pg_temp.a(spatial_claim('a0402000-0000-4000-8000-000000000002') is null,'second worker cannot duplicate running job');
select pg_temp.denied('select spatial_worker_update(job,gen_random_uuid(),''heartbeat'',''{"progress":0.5,"cost_cents":1}'') from _fixture','RP409:%','stale lease heartbeat rejected');
select pg_temp.a((select spatial_worker_update(job,lease,'heartbeat','{"progress":0.5,"cost_cents":1}')->>'status'='processing' from _fixture),'valid heartbeat commits');
select pg_temp.denied('select spatial_worker_update(job,lease,''heartbeat'',''{"progress":0.5,"cost_cents":0}'') from _fixture','RP400:%','cost cannot decrease');
select pg_temp.denied('select spatial_worker_update(job,lease,''heartbeat'',''{"progress":0.5,"cost_cents":601}'') from _fixture','RP400:%','cost cap enforced');
select pg_temp.denied('select spatial_worker_update(job,lease,''complete'',''{"manifest":{},"cost_cents":2}'') from _fixture','RP409:%','complete without stored model fails');
update _fixture set revision=(select (spatial_worker_update(job,lease,'output_ticket',jsonb_build_object('bytes',100,'sha256',repeat('a',64)))->>'artifact_revision')::uuid from _fixture);
select pg_temp.a((select spatial_worker_update(job,lease,'output_claim','{}')->>'dispatch'='true' from _fixture),'first output claims one dispatch');
select pg_temp.a((select spatial_worker_update(job,lease,'output_claim','{}')->>'dispatch'='false' from _fixture),'replayed output cannot dispatch twice');
select pg_temp.denied('select spatial_worker_update(job,lease,''output_ticket'',jsonb_build_object(''bytes'',101,''sha256'',repeat(''a'',64))) from _fixture','RP409:%','output replay cannot swap bytes');
select spatial_worker_update(job,lease,'output_stored','{"etag":"synthetic-etag"}') from _fixture;
select spatial_worker_update(job,lease,'complete',jsonb_build_object('cost_cents',2,'manifest',jsonb_build_object('artifact_revision',revision,'sha256',repeat('a',64),'bytes',100,'provenance','captured'))) from _fixture;
select pg_temp.a((select status='review' and not approved and published_at is null from spatial_jobs where id=(select job from _fixture)),'completed reconstruction is private');
select pg_temp.denied('select spatial_publish(actor,job) from _fixture','RP409:%','publication without review rejected');
select spatial_review(actor,job,revision,true,false,'[]') from _fixture;
select pg_temp.a((select spatial_publish(actor,job)->>'status'='ready' from _fixture),'reviewed no-redaction room publishes');
select pg_temp.a((select spatial_publish(actor,job)->>'status'='ready' from _fixture),'publish replay is idempotent');
select spatial_review(actor,job,revision,true,true,'[]') from _fixture;
select pg_temp.a((select excluded and published_at is null and not approved from spatial_jobs where id=(select job from _fixture)),'exclude revokes public sharing immediately');
select pg_temp.denied('select spatial_publish(actor,job) from _fixture','RP409:%','excluded room cannot publish');
select spatial_review(actor,job,revision,true,false,'[{"min":[0,0,0],"max":[1,1,1]}]') from _fixture;
select pg_temp.denied('select spatial_publish(actor,job) from _fixture','RP409:%','unprocessed region redaction cannot publish');
reset role;
insert into memberships(user_id,org_id,role) select other_actor,org,'owner' from _fixture;
update listings l set agent_id=f.other_actor from _fixture f where l.id=f.listing;
select pg_temp.a((select j.actor_id=f.other_actor and j.origin_actor_id=f.actor and j.lease_token=f.lease from spatial_jobs j join _fixture f on j.id=f.job),'listing handoff preserves lease and follows execution owner');
update spatial_jobs set status='processing',lease_expires_at=clock_timestamp()+interval '2 minutes' where id=(select job from _fixture);
set local role service_role;
select pg_temp.a((select spatial_worker_update(job,lease,'heartbeat','{"cost_cents":3,"progress":0.95}')->>'status'='processing' from _fixture),'worker survives attributed ownership handoff');
select pg_temp.denied('select spatial_recover(marketing,job,''cancel'') from _fixture','RP403:%','marketing recovery mutation denied');
select pg_temp.denied('select spatial_recover(actor,job,''cancel'') from _fixture','RP409:%','running worker not falsely cancelled');
select spatial_worker_update(job,lease,'fail','{"failure_code":"provider_failed","cost_cents":3,"provider_stopped":false}') from _fixture;
select pg_temp.denied('select spatial_recover(actor,job,''retry'') from _fixture','RP400:%','retry requires explicit new operation key');
select pg_temp.denied('select spatial_recover(actor,job,''retry'',''a0408000-0000-4000-8000-000000000002'') from _fixture','RP409:%','unconfirmed provider lifetime prevents overlapping retry');
reset role;
update spatial_jobs set deadline_at=clock_timestamp()-interval '1 second' where id=(select job from _fixture);
set local role service_role;
select pg_temp.denied('select spatial_recover(actor,job,''retry'',''a0408000-0000-4000-8000-000000000002'') from _fixture','RP429:%','retry cannot bypass exhausted reservation budget');
select pg_temp.a((select j.attempt_number=1 and j.output_key is not null and not exists(select 1 from spatial_attempt_history) from spatial_jobs j join _fixture f on j.id=f.job),'failed retry rolls back reset and attempt journal');
update spatial_runtime set daily_budget_cents=1800,org_monthly_budget_cents=1800;
select pg_temp.a((select spatial_recover(actor,job,'retry','a0408000-0000-4000-8000-000000000002')->>'status'='queued' from _fixture),'expired failed capture explicitly retries without recapture');
select pg_temp.a((select count(*)=20 from spatial_inputs where job_id=(select job from _fixture)),'retry reuses all original input bindings');
select pg_temp.a((select count(*)=1 and bool_and(snapshot->>'output_key' is not null) from spatial_attempt_history),'prior lease and output retained in retry history');
select pg_temp.a((select spatial_recover(actor,job,'retry','a0408000-0000-4000-8000-000000000002')->>'attempt_number'='2' from _fixture),'retry same key returns same paid attempt');
select pg_temp.denied('select spatial_recover(actor,job,''retry'',''a0408000-0000-4000-8000-000000000099'') from _fixture','RP409:%','competing retry key cannot replace queued attempt');
select pg_temp.a((select sum(committed_cents)=2400 from spatial_budget_windows),'explicit retry reserves exactly once');
select pg_temp.a((select spatial_recover(actor,job,'cancel')->>'failure_code'='user_cancelled' from _fixture),'queued attempt cancellation commits without deletion');
select pg_temp.a((select spatial_recover(actor,job,'cancel')->>'failure_code'='user_cancelled' from _fixture),'cancel replay is idempotent');
select pg_temp.a((select spatial_recover(actor,job,'resume')->>'status'='uploading' from _fixture),'cancelled queued capture resumes same attempt');
select pg_temp.a((select spatial_start(actor,job)->>'status'='queued' from _fixture),'resumed attempt can return to queue');
select pg_temp.a((select sum(committed_cents)=2400 from spatial_budget_windows),'resume never charges previously reserved undispatched attempt again');
select pg_temp.a((spatial_claim('a0402000-0000-4000-8000-000000000002')->>'status')='processing','retry can obtain a fresh worker lease');
select pg_temp.denied('select spatial_worker_update(job,lease,''output_claim'',''{}'') from _fixture','RP409:%','previous attempt lease cannot write retry output');
select spatial_worker_update(id,lease_token,'fail','{"failure_code":"provider_failed","cost_cents":600,"provider_stopped":true}') from spatial_jobs where id=(select job from _fixture);
select pg_temp.a((select spatial_recover(actor,job,'retry','a0408000-0000-4000-8000-000000000003')->>'attempt_number'='3' from _fixture),'confirmed provider stop allows immediate bounded retry');
select pg_temp.a((select spatial_recover(actor,job,'retry','a0408000-0000-4000-8000-000000000002')->>'attempt_number'='3' from _fixture),'old retry transport replay cannot restart newest attempt');
select spatial_claim('a0402000-0000-4000-8000-000000000003');
select spatial_worker_update(id,lease_token,'fail','{"failure_code":"provider_failed","cost_cents":600,"provider_stopped":true}') from spatial_jobs where id=(select job from _fixture);
select pg_temp.denied('select spatial_recover(actor,job,''retry'',''a0408000-0000-4000-8000-000000000004'') from _fixture','RP429:%','maximum three attempts per capture enforced');
select pg_temp.a((select sum(committed_cents)=3600 from spatial_budget_windows),'failed attempts retain all worst-case reservations');
reset role;
update spatial_jobs set status='processing',provider_stopped=false,lease_expires_at=clock_timestamp()-interval '1 second',deadline_at=clock_timestamp()+interval '1 hour' where id=(select job from _fixture);
update spatial_runtime set enabled=false;
set local role service_role;
select pg_temp.a((select spatial_expire(listing)=1 from _fixture),'independent sweep expires processing while runtime disabled');
select pg_temp.a((select status='failed' and failure_code='worker_lease_expired' and not provider_stopped from spatial_jobs where id=(select job from _fixture)),'lease expiry is failure not a termination receipt');
select pg_temp.a(spatial_claim('a0402000-0000-4000-8000-000000000004') is null,'disabled runtime does not claim after sweep');
select pg_temp.a((select sum(committed_cents)=3600 from spatial_budget_windows),'expiry does not refund uncertain spend');
reset role;
select 'PASS: '||count(*)||' spatial SQL assertions; all fixtures rolled back.' from _checks;
rollback;
