\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_audit' or inet_server_addr() is not null then raise exception 'Run only in the owned socket-only rendprop_audit fixture';end if;end$$;
create temp table checks(name text primary key,passed boolean not null);
create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label,true);end$$;
create function pg_temp.denied(command text,prefix text,label text) returns void language plpgsql as $$declare message text;begin begin execute command;exception when others then message:=sqlerrm;end;perform pg_temp.ok(message like prefix||'%',label);end$$;
grant all on checks to service_role;
create temp table fixture(a uuid,b uuid,c uuid,q uuid,o uuid,other uuid,qo uuid,l uuid,m uuid,bm uuid,sha text,key text);
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();q uuid:=gen_random_uuid();o uuid;other uuid;qo uuid;l uuid:=gen_random_uuid();begin
 insert into auth.users(id,email)values(a,'audit-a@fixture.invalid'),(b,'audit-b@fixture.invalid'),(c,'audit-c@fixture.invalid'),(q,'audit-q@fixture.invalid');
 select org_id into strict o from memberships where user_id=a;select org_id into strict other from memberships where user_id=c;select org_id into strict qo from memberships where user_id=q;
 insert into memberships(user_id,org_id,role) values(b,o,'agent');
 insert into listings(id,org_id,agent_id,address)values(l,o,a,'Synthetic private-media property');
 insert into fixture values(a,b,c,q,o,other,qo,l,gen_random_uuid(),gen_random_uuid(),repeat('a',64),'project:'||gen_random_uuid());
end$$;
grant select on fixture to service_role;
select pg_temp.ok(not has_table_privilege(role,'studio_project_media',perm),'media denies '||role||' '||perm) from unnest(array['anon','authenticated'])role cross join unnest(array['select','insert','update','delete'])perm;
select pg_temp.ok(not has_function_privilege(role,fn,'execute'),'RPC denies '||role||' '||fn) from unnest(array['anon','authenticated'])role cross join unnest(array['studio_project_media_write(uuid,uuid,uuid,text,jsonb)','studio_save_project(uuid,uuid,text,uuid,integer,jsonb)','studio_project_deletion_targets(uuid,uuid[],text)'])fn;
select pg_temp.ok(not has_function_privilege('service_role','studio_project_deletion_targets(uuid,uuid[],text)','execute'),'deletion inventory helper remains internal');
set local role service_role;
do $$declare f record;r jsonb;data jsonb;project jsonb;i integer;begin
 select * into f from fixture;
 data:=jsonb_build_object('sha256',f.sha,'bytes',9437184,'mime','video/mp4','filename','fixture.mp4','modified',0);
 r:=studio_project_media_write(f.a,f.o,f.m,'reserve',data);
 perform pg_temp.ok((r->>'parts')::int=2,'reserve enumerates full and tail chunks');
 perform pg_temp.ok((studio_project_media_write(f.a,f.o,gen_random_uuid(),'reserve',data)->>'id')::uuid=f.m,'same-account hash replay binds original ID');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'reserve',data||'{"bytes":3}'::jsonb),'RP409:','same hash cannot change size');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.c,f.o,f.m,'inspect','{"part":0,"bytes":8388608,"sha256":"'||f.sha||'"}'),'RP403:','outsider cannot inspect guessed ID');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.b,f.o,f.m,'inspect','{"part":0,"bytes":8388608,"sha256":"'||f.sha||'"}'),'RP404:','same-org colleague cannot inspect private ID');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.other,f.m,'inspect','{"part":0,"bytes":8388608,"sha256":"'||f.sha||'"}'),'RP403:','actor cannot switch org for private ID');
 data:=jsonb_build_object('part',0,'bytes',8388608,'sha256',f.sha);
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'finish',data),'RP409:','finish requires prior claimed attempt');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'claim',data-'sha256'),'RP400:','missing chunk hash rejected');
 r:=studio_project_media_write(f.a,f.o,f.m,'claim',data);
 perform pg_temp.ok((r->>'dispatch')::bool,'first claim admits one storage dispatch');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'inspect',data||jsonb_build_object('sha256',repeat('b',64))),'RP409:','recovery cannot replace immutable hash');
 perform studio_project_media_write(f.a,f.o,f.m,'claim',data);perform studio_project_media_write(f.a,f.o,f.m,'claim',data);
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'claim',data),'RP409:','fourth storage dispatch rejected');
 r:=studio_project_media_write(f.a,f.o,f.m,'inspect',data);
 perform pg_temp.ok((r#>>'{media,receipts,0,attempts}')::int=3 and not(r->>'dispatch')::bool,'exhausted matching part remains inspectable without new attempt');
 r:=studio_project_media_write(f.a,f.o,f.m,'finish',data);
 perform pg_temp.ok(r#>>'{media,receipts,0,state}'='complete' and (r#>>'{media,receipts,0,attempts}')::int=3,'verified uncertain write can settle without fourth dispatch');
 perform pg_temp.ok(not(studio_project_media_write(f.a,f.o,f.m,'claim',data)->>'dispatch')::bool,'completed part replay never writes');
 perform studio_project_media_write(f.b,f.o,f.bm,'reserve',jsonb_build_object('sha256',repeat('b',64),'bytes',3,'mime','audio/mpeg','filename','colleague.mp3','modified',0));
 project:=jsonb_build_object('schema',1,'name','Private edit','archived',false,'listingId',f.l,'draft','{}'::jsonb,'sources','[]'::jsonb);
 r:=studio_save_project(f.a,f.o,f.key,f.l,0,project);perform pg_temp.ok((r->>'revision')::int=1,'new project starts revision one');
 perform pg_temp.denied(format('select studio_save_project(%L,%L,%L,%L,0,%L::jsonb)',f.a,f.o,f.key,f.l,project),'RP409:','stale create cannot overwrite project');
 r:=studio_save_project(f.a,f.o,f.key,f.l,1,project||'{"name":"Second"}'::jsonb);perform pg_temp.ok((r->>'revision')::int=2,'CAS update increments once');
 perform pg_temp.denied(format('select studio_save_project(%L,%L,%L,%L,1,%L::jsonb)',f.a,f.o,f.key,f.l,project),'RP409:','stale update cannot overwrite project');
 perform pg_temp.denied(format('select studio_save_project(%L,%L,%L,NULL,2,%L::jsonb)',f.a,f.o,f.key,project||'{"listingId":null}'::jsonb),'RP409:','project property cannot be rebound');
 perform pg_temp.denied(format('select studio_save_project(%L,%L,%L,%L,0,%L::jsonb)',f.c,f.o,'project:'||gen_random_uuid(),f.l,project),'RP403:','outsider cannot create project');
 for i in 1..99 loop perform studio_save_project(f.a,f.o,'project:'||gen_random_uuid(),f.l,0,project);end loop;
 perform pg_temp.denied(format('select studio_save_project(%L,%L,%L,%L,0,%L::jsonb)',f.a,f.o,'project:'||gen_random_uuid(),f.l,project),'RP400:','101st private project rejected');
 for i in 1..4 loop perform studio_project_media_write(f.q,f.qo,gen_random_uuid(),'reserve',jsonb_build_object('sha256',repeat(i::text,64),'bytes',134217728,'mime','video/mp4','filename','quota.mp4','modified',0));end loop;
 perform pg_temp.ok((select sum(bytes) from studio_project_media where org_id=f.qo)=536870912,'workspace quota admits exactly 512 MiB');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.q,f.qo,gen_random_uuid(),'reserve',jsonb_build_object('sha256',repeat('e',64),'bytes',1,'mime','video/mp4','filename','over.mp4','modified',0)),'RP400:','quota rejects one byte over cap');
end$$;
reset role;
do $$declare f record;begin select * into f from fixture;
 update memberships set role='marketing' where user_id=f.b and org_id=f.o;
 update studio_project_media set write_deadline=clock_timestamp()-interval '1 hour' where id=f.bm;
end$$;
set local role service_role;
do $$declare f record;r jsonb;deadline timestamptz;begin select * into f from fixture;
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.b,f.o,f.bm,'inspect',jsonb_build_object('part',0,'bytes',3,'sha256',repeat('b',64))),'RP403:','marketing cannot inspect writable media');
 perform pg_temp.ok((studio_project_media_write(f.b,f.o,f.bm,'read','{}')->>'id')::uuid=f.bm,'marketing can read own original after upload deadline');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.bm,'read','{}'),'RP404:','read recheck denies same-org colleague original');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.c,f.o,f.bm,'read','{}'),'RP403:','read recheck denies foreign workspace');
 select write_deadline into deadline from studio_project_media where id=f.m;
 r:=prepare_account_deletion(f.a,'fixture-uploads','fixture-renders');
 select payload into r from deletion_requests where user_id=f.a and snapshot_version=2;
 perform pg_temp.ok((select count(*) from jsonb_array_elements(r->'r2')v where v->>'key' like 'studio-project/'||f.o||'/'||f.a||'/'||f.m||'/%')=2,'deletion enumerates completed and never-written reserved chunks');
 perform pg_temp.ok(not exists(select 1 from jsonb_array_elements(r->'r2')v where v->>'key' like 'studio-project/'||f.o||'/'||f.b||'/%'),'deletion excludes colleague originals in shared workspace');
 perform pg_temp.ok((r->>'storage_not_before')::timestamptz>=deadline+interval '1 hour','deletion waits beyond bounded upload write deadline');
 perform pg_temp.ok(not exists(select 1 from studio_project_media where actor_id=f.a),'account deletion removes private media metadata');
 perform pg_temp.ok(exists(select 1 from studio_project_media where id=f.bm),'account deletion preserves other contributors media');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'inspect',jsonb_build_object('part',0,'bytes',8388608,'sha256',f.sha)),'RP403:','deletion intent fences late recovery');
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.a,f.o,f.m,'read','{}'),'RP403:','deletion intent fences signed media response');
end$$;
reset role;
update memberships set role='agent' where user_id=(select b from fixture) and org_id=(select o from fixture);
set local role service_role;
do $$declare f record;begin select * into f from fixture;
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.b,f.o,f.bm,'inspect',jsonb_build_object('part',0,'bytes',3,'sha256',repeat('b',64))),'RP409:','expired writable upload remains refused');
end$$;
reset role;
delete from memberships where user_id=(select b from fixture) and org_id=(select o from fixture);
set local role service_role;
do $$declare f record;begin select * into f from fixture;
 perform pg_temp.denied(format('select studio_project_media_write(%L,%L,%L,%L,%L::jsonb)',f.b,f.o,f.bm,'read','{}'),'RP403:','membership revocation fences signed media response');
end$$;
reset role;
select count(*) as passed from checks;
select name,passed from checks order by name;
rollback;
