\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_audit' or inet_server_addr() is not null then raise exception 'Run only in the owned socket-only rendprop_audit fixture';end if;end$$;
create temp table team_checks(name text primary key,passed boolean not null);
create function pg_temp.team_ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'TEAM FAIL: %',label;end if;insert into team_checks values(label,true);end$$;
create function pg_temp.team_denied(command text,prefix text,label text) returns void language plpgsql as $$declare message text;begin begin execute command;exception when others then message:=sqlerrm;end;perform pg_temp.team_ok(message like prefix||'%',label);end$$;
grant all on team_checks to service_role,authenticated;
create temp table team_fixture(owner_id uuid,org_id uuid,other_owner uuid,other_org uuid,first_member uuid,listing_id uuid,invite_id uuid,invite_code text);
do $$declare own uuid:=gen_random_uuid();other uuid:=gen_random_uuid();org uuid;other_org uuid;i uuid:=gen_random_uuid();begin
 insert into auth.users(id,email,raw_user_meta_data,is_anonymous)values(own,'manager@fixture.invalid','{"name":"Fixture Manager"}',false),(other,'outsider@fixture.invalid','{}',false);
 select org_id into strict org from memberships where user_id=own;select org_id into strict other_org from memberships where user_id=other;
 update orgs set plan='team',name='Fixture Brokerage' where id=org;
 insert into team_fixture values(own,org,other,other_org,null,gen_random_uuid(),i,'ABCD-EFGH-JKMN');
end$$;
grant select,update on team_fixture to service_role,authenticated;
set local role service_role;
do $$declare f record;r jsonb;begin select * into f from team_fixture;
 r:=create_org_invite(f.owner_id,f.org_id,'invite@fixture.invalid','agent',encode(sha256(convert_to(replace(f.invite_code,'-',''),'UTF8')),'hex'));
 update team_fixture set invite_id=(r->>'id')::uuid;
 r:=notification_enqueue_invite(f.org_id,(r->>'id')::uuid,' Invite@Fixture.Invalid ',f.invite_code,'agent',f.owner_id);
 perform pg_temp.team_ok(r->>'ok'='true' and r->>'queued'='true','addressed invite queues with the real profile name column');
end$$;
reset role;
do $$declare f record;r jsonb;begin select * into f from team_fixture;
 perform pg_temp.team_ok((select count(*)=1 from notification_outbox where dedupe_key='invite:'||f.invite_id::text),'one actual outbox row exists');
 select payload into r from notification_outbox where dedupe_key='invite:'||f.invite_id::text;
 perform pg_temp.team_ok(r#>>'{data,inviter}'='Fixture Manager','mail carries manager name');
 perform pg_temp.team_ok(r#>>'{data,code}'=f.invite_code and r->>'deep_link'='/join/'||f.invite_code,'mail carries matching code and deep link');
 perform pg_temp.team_ok((select to_email='invite@fixture.invalid' from notification_outbox where dedupe_key='invite:'||f.invite_id::text),'mail address normalized');
 r:=notification_enqueue_invite(f.org_id,f.invite_id,'invite@fixture.invalid',f.invite_code,'agent',f.owner_id);
 perform pg_temp.team_ok(r->>'ok'='true' and r->>'queued'='false' and r->>'reason'='already_queued','duplicate queue attempt is explicit');
 perform pg_temp.team_ok((select count(*)=1 from notification_outbox where dedupe_key='invite:'||f.invite_id::text),'retry creates no duplicate mail');
 r:=notification_enqueue_invite(f.org_id,gen_random_uuid(),null,f.invite_code,'agent',f.owner_id);
 perform pg_temp.team_ok(r->>'ok'='false' and r->>'reason'='no_address','missing address is not success');
 update notification_outbox set state='sent' where dedupe_key='invite:'||f.invite_id::text;
 select payload into r from notification_outbox where dedupe_key='invite:'||f.invite_id::text;
 perform pg_temp.team_ok(r#>>'{data,code}'='[redacted]' and r->>'deep_link'='/join/[redacted]','terminal delivery removes code in both locations');
 perform pg_temp.team_ok(org_seats_allowed(f.org_id)=2 and org_seats_used(f.org_id)=2,'standard Team retains two-seat ceiling including pending invitation');
 perform pg_temp.team_denied(format('select create_org_invite(%L,%L,%L,%L,%L)',f.owner_id,f.org_id,'over@fixture.invalid','agent',repeat('b',64)),'RP402:','ordinary Team cannot accidentally grant third seat');
 update org_invites set revoked_at=now() where id=f.invite_id;
end$$;
select pg_temp.team_ok(not has_function_privilege(role,'public.notification_enqueue_invite(uuid,uuid,text,text,text,uuid)','execute'),'enqueue denies '||role)from unnest(array['anon','authenticated'])role;
select pg_temp.team_ok(not has_function_privilege(role,'public.set_brokerage_contract(uuid,integer,text,text,integer,integer,integer,integer,integer,text,timestamptz,text,boolean)','execute'),'contract changes deny '||role)from unnest(array['anon','authenticated'])role;
set local role service_role;
do $$declare f record;r jsonb;e record;addresses text[];begin select * into f from team_fixture;
 perform set_brokerage_contract(f.org_id,100,'Synthetic Brokerage','billing@fixture.invalid');
 select * into e from org_entitlement(f.org_id);
 perform pg_temp.team_ok(org_seats_allowed(f.org_id)=100 and e.seats=100 and e.plan='brokerage','signed 100-seat contract authorizes 100 seats');
 perform pg_temp.team_ok(e.renders_per_month=300 and e.photo_edits_per_month=4000 and e.reels_per_month=300 and e.aerials_per_month=100,'contract pools existing per-seat allowances exactly');
 select array_agg('agent-'||n||'@fixture.invalid' order by n) into addresses from generate_series(1,99)n;
 r:=create_org_invites_bulk(f.org_id,f.owner_id,addresses||array['bad','agent-1@fixture.invalid'],'agent');
 perform pg_temp.team_ok((r->>'issued')::int=99 and jsonb_array_length(r->'results')=101,'bulk admits 99 seats and reports invalid and duplicate input');
 perform pg_temp.team_ok(org_seats_used(f.org_id)=100,'99 invites plus owner consume exactly 100 seats');
 perform pg_temp.team_denied(format('select create_org_invites_bulk(%L,%L,ARRAY[%L],%L)',f.org_id,f.owner_id,'one-too-many@fixture.invalid','agent'),'RP402:','bulk request cannot overbook contract');
 create temp table admitted_invites as select (v->>'id')::uuid invite_id,v->>'code' code,v->>'email' email,gen_random_uuid() user_id from jsonb_array_elements(r->'results')v where v->>'outcome'='issued';
end$$;
reset role;
insert into auth.users(id,email,is_anonymous) select user_id,email,false from admitted_invites;
grant select on admitted_invites to service_role;
update team_fixture set first_member=(select user_id from admitted_invites order by email limit 1);
set local role service_role;
do $$declare f record;r jsonb;i record;begin select * into f from team_fixture;
 for i in select * from admitted_invites loop
  r:=accept_org_invite(i.user_id,encode(sha256(convert_to(replace(i.code,'-',''),'UTF8')),'hex'));
  if r->>'org_id'<>f.org_id::text or r->>'role'<>'agent' then raise exception 'TEAM FAIL: accepted invite identity mismatch';end if;
 end loop;
 perform pg_temp.team_ok((select count(*)=100 from memberships where org_id=f.org_id),'all 99 agents join one 100-person workspace');
 perform pg_temp.team_ok((select count(*)=0 from admitted_invites admitted where (select count(*) from memberships where user_id=admitted.user_id)<>2),'each agent retains their independent workspace');
 perform pg_temp.team_ok((select bool_and(active_org_for_user(user_id)=f.org_id) from admitted_invites),'accepted team becomes every agent active workspace');
 perform pg_temp.team_denied(format('select create_org_invites_bulk(%L,%L,ARRAY[%L],%L)',f.org_id,f.first_member,'unauthorized@fixture.invalid','agent'),'RP403:','agent cannot invite');
 perform pg_temp.team_denied(format('select brokerage_overview(%L,%L)',f.org_id,f.first_member),'RP403:','agent cannot inspect whole brokerage activity');
 perform pg_temp.team_denied(format('select remove_org_member(%L,%L,%L)',f.org_id,f.first_member,f.owner_id),'RP403:','agent cannot remove manager');
 r:=brokerage_overview(f.org_id,f.owner_id);
 perform pg_temp.team_ok((r#>>'{seats,allowed}')::int=100 and (r#>>'{seats,used}')::int=100,'manager overview reflects contract capacity');
end$$;
reset role;
insert into listings(id,org_id,agent_id,address)select listing_id,org_id,first_member,'Synthetic team property'from team_fixture;
select set_config('request.jwt.claim.sub',(select first_member::text from team_fixture),true);
set local role authenticated;
select pg_temp.team_ok((select count(*)=1 from listings where id=(select listing_id from team_fixture)),'member can access shared property');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role service_role;
do $$declare f record;i record;begin select * into f from team_fixture;select * into i from admitted_invites where user_id=f.first_member;
 perform remove_org_member(f.org_id,f.owner_id,f.first_member);
 perform pg_temp.team_ok(active_org_for_user(f.first_member)<>f.org_id and active_org_for_user(f.first_member)is not null,'removed member falls back to retained personal workspace');
 perform pg_temp.team_denied(format('select accept_org_invite(%L,%L)',f.first_member,encode(sha256(convert_to(replace(i.code,'-',''),'UTF8')),'hex')),'RP404:','removed member cannot replay accepted code');
 perform pg_temp.team_ok((select count(*)=1 from listings where id=f.listing_id and org_id=f.org_id),'removal preserves team property');
 perform pg_temp.team_ok(org_seats_used(f.org_id)=99,'removal frees one contracted seat');
end$$;
reset role;
select set_config('request.jwt.claim.sub',(select first_member::text from team_fixture),true);
set local role authenticated;
select pg_temp.team_ok((select count(*)=0 from listings where id=(select listing_id from team_fixture)),'removed agent loses property visibility immediately');
reset role;
select set_config('request.jwt.claim.sub',(select other_owner::text from team_fixture),true);
set local role authenticated;
select pg_temp.team_ok((select count(*)=0 from listings where id=(select listing_id from team_fixture)),'independent account cannot see brokerage property');
reset role;
select count(*) as passed from team_checks;
select name,passed from team_checks order by name;
rollback;
