\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_privacy_audit'or inet_server_addr()is not null then raise exception 'Use only the owned socket-only privacy fixture';end if;end$$;
create temp table privacy_checks(label text primary key,passed boolean not null);
create function pg_temp.ok(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'PRIVACY FAIL: %',label;end if;insert into privacy_checks values(label,true);end$$;
create function pg_temp.denied(command text,prefix text,label text)returns void language plpgsql as $$declare problem text;begin begin execute command;exception when others then problem:=sqlerrm;end;perform pg_temp.ok(problem like prefix||'%',label);end$$;
grant all on privacy_checks to service_role,anon,authenticated;
create temp table fixture(a uuid,b uuid,c uuid,m uuid,o uuid,other uuid,l uuid,lead uuid);
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();m uuid:=gen_random_uuid();o uuid;other uuid;l uuid:=gen_random_uuid();begin
 insert into auth.users(id,email,is_anonymous,email_confirmed_at)values(a,'auth-owner@fixture.invalid',false,now()),(b,'unconfirmed@fixture.invalid',false,null),(c,'anonymous@fixture.invalid',true,now()),(m,'marketing@fixture.invalid',false,now());
 select org_id into o from memberships where user_id=a;select org_id into other from memberships where user_id=b;
 insert into memberships(user_id,org_id,role)values(m,o,'marketing'),(c,o,'agent');
 insert into listings(id,org_id,agent_id,address)values(l,o,a,'Synthetic private property');
 update profiles set email='attacker@fixture.invalid'where id=a;
 insert into fixture values(a,b,c,m,o,other,l,gen_random_uuid());
end$$;
grant select on fixture to service_role,anon,authenticated;
select pg_temp.ok(not has_table_privilege(r,'public.client_recipient_verifications','insert,update,delete'),'token table denies DML '||r)from unnest(array['anon','authenticated','service_role'])r;
select pg_temp.ok(not has_function_privilege(r,fn,'execute'),'privileged recipient RPC denies '||r||' '||fn)
 from unnest(array['anon','authenticated'])r cross join unnest(array['public.notification_verified_recipients(uuid[])','public.client_recipient_verification_request(uuid,uuid,uuid,text)','public.client_recipient_verification_consume(text)','public.client_recipient_verification_prepare(uuid,uuid,text)'])fn;
select pg_temp.ok(p.prosecdef and p.proconfig=array['search_path=""']::text[],'recipient helper pins definer path '||p.oid::regprocedure)
 from pg_proc p where p.oid in('public.notification_verified_recipients(uuid[])'::regprocedure,'public.client_recipient_verified(uuid,text)'::regprocedure,'public.client_recipient_verification_request(uuid,uuid,uuid,text)'::regprocedure,'public.client_recipient_verification_consume(text)'::regprocedure,'public.client_recipient_verification_prepare(uuid,uuid,text)'::regprocedure);
set local role service_role;
do $$declare f record;c jsonb;r jsonb;v record;o record;payload jsonb;begin select * into f from fixture;
 perform pg_temp.ok((select email='auth-owner@fixture.invalid'from notification_verified_recipients(array[f.a])),'private notification uses verified Auth not editable profile');
 perform pg_temp.ok(not exists(select 1 from notification_verified_recipients(array[f.b])),'unconfirmed Auth never receives private notification');
 perform pg_temp.ok(not exists(select 1 from notification_verified_recipients(array[f.c])),'anonymous Auth never receives private notification');
 c:=listing_client_contact_put(f.a,f.o,f.l,0,true,'{"name":"Synthetic Client"}','client@fixture.invalid',true,null);
 perform pg_temp.ok(c->>'recipient_verified_at'is null and not client_recipient_verified(f.l,'client@fixture.invalid'),'saving typed contact does not verify recipient');
 insert into public.leads(id,org_id,listing_id,email,name)values(f.lead,f.o,f.l,'buyer@fixture.invalid','Private buyer');
 perform pg_temp.ok(not exists(select 1 from client_lead_deliveries where lead_id=f.lead),'unverified recipient gets no buyer snapshot');
 perform pg_temp.ok((client_delivery_summary(f.lead)->>'can_resend')::boolean=false,'unverified historical inquiry cannot resend');
 perform pg_temp.denied(format('select client_lead_resend(%L,%L,%L,%L,%L)',f.a,f.o,f.lead,gen_random_uuid(),'client@fixture.invalid'),'RP409:','manual resend requires verified recipient');
 perform pg_temp.denied(format('select client_recipient_verification_request(%L,%L,%L,%L)',f.b,f.o,f.l,repeat('b',64)),'RP404:','other agency cannot request verification');
 perform pg_temp.denied(format('select client_recipient_verification_request(%L,%L,%L,%L)',f.m,f.o,f.l,repeat('b',64)),'RP403:','marketing cannot request verification');
 perform pg_temp.denied(format('select client_recipient_verification_request(%L,%L,%L,%L)',f.c,f.o,f.l,repeat('b',64)),'RP403:','anonymous member cannot request verification');
 r:=client_recipient_verification_request(f.a,f.o,f.l,repeat('a',64));
 perform pg_temp.ok(r=jsonb_build_object('ok',true,'state','queued'),'verification request returns no nonce or recipient');
 select * into v from client_recipient_verifications where listing_id=f.l;
 select * into o from notification_outbox where client_verification_id=v.id;
 perform pg_temp.ok(v.token_hash=encode(sha256(convert_to(repeat('a',64),'UTF8')),'hex')and v.token_hash<>repeat('a',64),'verification stores only hashed nonce');
 perform pg_temp.ok(v.recipient_email='client@fixture.invalid'and v.org_id=f.o and v.contact_revision=1,'verification binds saved recipient org and revision');
 perform pg_temp.ok(o.to_email='client@fixture.invalid'and o.payload->>'deep_link'='https://rendprop.com/verify-client-email#token='||repeat('a',64),'verification link carries token in fragment only');
 perform pg_temp.ok(v.expires_at-v.created_at=interval '24 hours','verification expires after 24 hours');
 perform pg_temp.denied(format('select client_recipient_verification_request(%L,%L,%L,%L)',f.a,f.o,f.l,repeat('b',64)),'RP429:','verification double tap is bounded');
 perform notification_claim_batch(200);
 payload:=client_recipient_verification_prepare(v.id,o.id,'Rendprop <fixture@fixture.invalid>');
 perform pg_temp.ok(payload->>'to'='client@fixture.invalid'and payload->>'idempotency_key'='client-verification/'||v.id,'verification sender binds destination and stable key');
 perform pg_temp.ok(position('buyer@fixture.invalid'in(payload->>'text'))=0 and position('Private buyer'in(payload->>'text'))=0 and position('Synthetic private property'in(payload->>'text'))=0,'verification email contains no buyer or property data');
 perform pg_temp.ok(client_recipient_verification_prepare(v.id,o.id,'Different <changed@fixture.invalid>')=payload,'verification retry preserves sender and body');
 perform pg_temp.ok(not client_recipient_verification_consume(repeat('f',64)),'unknown nonce returns generic false');
 perform pg_temp.ok(not client_recipient_verification_consume(''), 'malformed nonce returns generic false');
 perform pg_temp.ok(client_recipient_verification_consume(repeat('a',64)),'possessed current nonce verifies recipient');
 perform pg_temp.ok(client_recipient_verification_consume(repeat('a',64)),'verification repeat is idempotent');
 perform pg_temp.ok(client_recipient_verified(f.l,'client@fixture.invalid')and not client_recipient_verified(f.l,'other@fixture.invalid'),'verification grants only exact recipient');
 perform pg_temp.ok(client_recipient_verification_request(f.a,f.o,f.l,repeat('b',64))=jsonb_build_object('ok',true,'state','verified'),'verified recipient needs no second email');
 r:=client_lead_resend(f.a,f.o,f.lead,gen_random_uuid(),'client@fixture.invalid');
 perform pg_temp.ok(r->>'ok'='true'and r#>>'{delivery,recipient_email}'='client@fixture.invalid','verified historical inquiry can be deliberately forwarded');
 select id into v from client_lead_deliveries where lead_id=f.lead;
 select id into o from notification_outbox where client_delivery_id=v.id;
 perform notification_claim_batch(200);
 perform pg_temp.ok(client_lead_prepare(v.id,o.id,'notify@fixture.invalid')->>'to'='client@fixture.invalid','current verified forwarding survives prepare gate');
 c:=listing_client_contact_put(f.a,f.o,f.l,1,true,'{"name":"Synthetic Client"}','new-client@fixture.invalid',true,null);
 perform pg_temp.ok(c->>'recipient_verified_at'is null and not client_recipient_verified(f.l,'new-client@fixture.invalid'),'recipient edit clears verification');
 perform pg_temp.ok(not client_recipient_verification_consume(repeat('a',64)),'old nonce cannot verify new recipient');
 perform pg_temp.ok(client_lead_prepare(v.id,o.id,'notify@fixture.invalid')is null,'recipient edit revokes queued buyer forwarding');
end$$;
reset role;
update client_recipient_verifications set created_at=created_at-interval '2 minutes',expires_at=expires_at-interval '2 minutes';
set local role service_role;
do $$declare f record;v uuid;c jsonb;begin select * into f from fixture;
 perform client_recipient_verification_request(f.a,f.o,f.l,repeat('c',64));
 select id into v from client_recipient_verifications where token_hash=encode(sha256(convert_to(repeat('c',64),'UTF8')),'hex');
 c:=listing_client_contact_put(f.a,f.o,f.l,2,true,'{"name":"Changed Name"}','new-client@fixture.invalid',true,null);
 perform pg_temp.ok(not client_recipient_verification_consume(repeat('c',64)),'nonce cannot cross contact revision edit');
end$$;
reset role;
update client_recipient_verifications set created_at=created_at-interval '2 minutes',expires_at=expires_at-interval '2 minutes';
set local role service_role;
do $$declare f record;v uuid;begin select * into f from fixture;
 perform client_recipient_verification_request(f.a,f.o,f.l,repeat('d',64));
end$$;
reset role;
update client_recipient_verifications set created_at=now()-interval '25 hours',expires_at=now()-interval '1 hour'where token_hash=encode(sha256(convert_to(repeat('d',64),'UTF8')),'hex');
set local role service_role;
select pg_temp.ok(not client_recipient_verification_consume(repeat('d',64)),'expired nonce cannot verify recipient');
reset role;
update client_recipient_verifications set created_at=created_at-interval '2 minutes',expires_at=expires_at-interval '2 minutes';
set local role service_role;
do $$declare f record;begin select * into f from fixture;perform client_recipient_verification_request(f.a,f.o,f.l,repeat('e',64));end$$;
reset role;
update listings set deleted_at=now()where id=(select l from fixture);
set local role service_role;
select pg_temp.ok(not client_recipient_verification_consume(repeat('e',64)),'deleted listing cannot verify recipient');
reset role;
set local role authenticated;
select pg_temp.denied('select client_recipient_verification_consume(repeat(''a'',64))','permission denied','authenticated cannot consume nonce RPC directly');
reset role;
set local role service_role;
do $$declare f record;r jsonb;begin select * into f from fixture;
 r:=notification_enqueue(f.o,f.a,'first_tour_nudge','{}','fixture-nudge-email',null);
 perform pg_temp.ok(r->>'state'='skipped'and r->>'reason'='promotional_email_disabled','default-on preference cannot enqueue promotional email');
 r:=notification_enqueue(f.o,f.a,'free_week_ending','{}','fixture-expiry-email',null);
 perform pg_temp.ok(r->>'state'='skipped'and r->>'reason'='promotional_email_disabled','trial expiry marketing email stays disabled');
 r:=notification_enqueue(f.o,f.a,'render_ready','{}','fixture-transactional-email',null);
 perform pg_temp.ok(r->>'state'='queued','transactional render email remains available');
end$$;
reset role;
update notification_outbox set state='sent'where client_verification_id is not null;
select pg_temp.ok(not exists(select 1 from notification_outbox where client_verification_id is not null and payload<>'{}'::jsonb),'terminal verification receipt erases opaque nonce');
update client_recipient_verifications set created_at=now()-interval '10 days',expires_at=now()-interval '9 days';
update client_lead_deliveries set state='skipped',created_at=now()-interval '31 days';
update notification_outbox set state='sent',created_at=now()-interval '31 days'where client_delivery_id is not null;
set local role service_role;
do $$declare r jsonb;begin
 r:=privacy_retention_sweep();
 perform pg_temp.ok((r->>'verification_tokens')::integer=4,'expired verification retention removes only expired token fixtures');
 perform pg_temp.ok(not exists(select 1 from notification_outbox where client_verification_id is not null),'expired verification removes secret outbox snapshots');
 perform pg_temp.ok(not exists(select 1 from client_lead_deliveries where email_text<>''or email_subject<>''),'terminal forwarding snapshot retention removes buyer message text');
 perform pg_temp.ok((select count(*)=1 from leads where id=(select lead from fixture)),'retention keeps photographer inquiry inbox intact');
end$$;
reset role;
select count(*)from privacy_checks;
select 'PASS: recipient privacy assertions; fixtures rolled back.';
rollback;
