\set ON_ERROR_STOP on
begin;
do $$begin if current_database()<>'rendprop_audit' or inet_server_addr() is not null then raise exception 'Run only in the owned socket-only rendprop_audit fixture';end if;end$$;
create temp table workspace_checks(name text primary key,passed boolean not null);
create function pg_temp.ws_ok(value boolean,label text)returns void language plpgsql as $$begin if value is distinct from true then raise exception 'WORKSPACE FAIL: %',label;end if;insert into workspace_checks values(label,true);end$$;
create function pg_temp.ws_denied(command text,expected text,label text)returns void language plpgsql as $$begin
 begin execute command;raise exception 'accepted forbidden workspace operation';exception when others then if sqlerrm not like expected then raise exception 'wrong denial for %: %',label,sqlerrm;end if;end;
 perform pg_temp.ws_ok(true,label);end$$;
create temp table workspace_fixture(actor uuid,owner uuid,guest uuid,personal uuid,team uuid,guest_org uuid,other_org uuid,dead_org uuid);
do $$declare u uuid:=gen_random_uuid();o uuid:=gen_random_uuid();g uuid:=gen_random_uuid();other uuid:=gen_random_uuid();a uuid;b uuid;go uuid;oo uuid;dead uuid;begin
 insert into auth.users(id,email,is_anonymous)values(u,'workspace-agent@fixture.invalid',false),(o,'workspace-owner@fixture.invalid',false),(g,null,true),(other,'workspace-other@fixture.invalid',false);
 select org_id into a from memberships where user_id=u;select org_id into b from memberships where user_id=o;select org_id into go from memberships where user_id=g;select org_id into oo from memberships where user_id=other;
 update orgs set plan='team',name='Fixture team'where id=b;
 insert into memberships(user_id,org_id,role)values(u,b,'agent');
 -- Historical source assignment is tied to an explicit accepted invitation;
 -- a bare membership is not evidence that a private library may be mapped.
 insert into org_invites(org_id,role,token_hash,invited_by,accepted_at,accepted_by)values(b,'agent',encode(sha256(convert_to(u::text,'UTF8')),'hex'),o,now(),u);
 insert into orgs(name,deleted_at)values('Deleted workspace',now())returning id into dead;
 insert into memberships(user_id,org_id,role)values(u,dead,'owner');
 insert into listings(org_id,agent_id,address)values(a,u,'Personal property'),(b,u,'Shared property');
 insert into workspace_fixture values(u,o,g,a,b,go,oo,dead);
end$$;
grant all on workspace_checks to service_role,anon,authenticated;
grant select on workspace_fixture to service_role,anon,authenticated;
select pg_temp.ws_ok(not has_table_privilege('authenticated','public.user_workspace_state','UPDATE')and not has_table_privilege('anon','public.user_workspace_state','UPDATE'),'clients cannot bypass verified workspace selection');
select pg_temp.ws_ok(not has_function_privilege(role,'public.select_workspace(uuid,uuid)','execute') and not has_function_privilege(role,'public.workspace_directory(uuid,uuid)','execute'),'workspace RPCs reject direct client role '||role)from unnest(array['anon','authenticated'])role;
select pg_temp.ws_denied('select public.select_workspace(actor,team)from workspace_fixture','service role required','explicit service-role guard rejects table owner bypass');
set local role authenticated;
select pg_temp.ws_denied('select public.select_workspace(actor,team)from workspace_fixture','permission denied%','authenticated cannot execute selection RPC');
reset role;
set local role service_role;
do $$declare f record;r jsonb;before_rows jsonb;after_rows jsonb;begin
 select * into f from workspace_fixture;
 select jsonb_agg(to_jsonb(l)order by id)into before_rows from listings l where org_id in(f.personal,f.team);
 r:=workspace_directory(f.actor,null);
 perform pg_temp.ws_ok(jsonb_array_length(r->'workspaces')=1 and exists(select 1 from jsonb_array_elements(r->'workspaces')w where (w->>'id')::uuid=f.personal and w->>'role'='owner')and not exists(select 1 from jsonb_array_elements(r->'workspaces')w where (w->>'id')::uuid=f.team),'directory keeps personal library and excludes shared Team seat');
 perform pg_temp.ws_ok(not exists(select 1 from jsonb_array_elements(r->'workspaces')w where (w->>'id')::uuid in(f.other_org,f.guest_org,f.dead_org)),'directory excludes other accounts and deleted workspaces');
 perform pg_temp.ws_denied(format('select public.select_workspace(%L,%L)',f.actor,f.team),'RP403:%','ordinary agent cannot select shared Team seat');
 r:=select_workspace(f.actor,f.personal);
 perform pg_temp.ws_ok(active_org_for_user(f.actor)=f.personal,'selection persists private library');
 perform pg_temp.ws_ok((workspace_directory(f.actor,f.personal)->>'active_org_id')::uuid=f.personal,'explicit personal request ignores another device active selection');
 perform pg_temp.ws_ok(active_org_for_user(f.actor)=f.personal,'explicit read does not overwrite default selection');
 perform pg_temp.ws_ok(select_workspace(f.actor,f.personal)=r,'repeat selection response is idempotent');
 r:=select_workspace(f.actor,f.personal);
 perform pg_temp.ws_ok(active_org_for_user(f.actor)=f.personal,'agent can return to preserved personal workspace');
 select jsonb_agg(to_jsonb(l)order by id)into after_rows from listings l where org_id in(f.personal,f.team);
 perform pg_temp.ws_ok(before_rows=after_rows,'selection never moves deletes or edits existing listings');
 perform pg_temp.ws_ok((select count(*)=3 from memberships where user_id=f.actor),'selection never creates or removes membership');
 r:=select_workspace(f.guest,f.guest_org);
 perform pg_temp.ws_ok(r->>'role'='owner'and jsonb_array_length(workspace_directory(f.guest,null)->'workspaces')=1,'anonymous owner can resolve and select their own workspace');
end$$;
select pg_temp.ws_denied('select public.select_workspace(actor,other_org)from workspace_fixture','RP403:%','nonmember cannot select another account workspace');
select pg_temp.ws_denied('select public.workspace_directory(actor,other_org)from workspace_fixture','RP403:%','explicit forbidden directory does not fall back');
select pg_temp.ws_denied('select public.select_workspace(actor,dead_org)from workspace_fixture','RP403:%','deleted workspace cannot be selected');
select pg_temp.ws_denied('select public.workspace_directory(actor,dead_org)from workspace_fixture','RP403:%','deleted explicit directory does not fall back');
select pg_temp.ws_denied('select public.select_workspace(guest,team)from workspace_fixture','RP403:%','guest cannot select someone else team');
select public.select_workspace(actor,personal)from workspace_fixture;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true)from workspace_fixture;
set local role authenticated;
select pg_temp.ws_ok((select count(*)=2 from listings where org_id in(select personal from workspace_fixture union select team from workspace_fixture)),'unfiltered RLS snapshot retains only own original and own legacy properties');
select pg_temp.ws_ok((select count(*)=1 from listings where org_id=(select personal from workspace_fixture))and(select count(*)=1 from listings where org_id=(select team from workspace_fixture)),'exact source-org filters retain own legacy data without shared access');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role service_role;
select public.remove_org_member(team,owner,actor)from workspace_fixture;
select pg_temp.ws_denied('select public.select_workspace(actor,team)from workspace_fixture','RP403:%','removed member cannot select former team');
select pg_temp.ws_denied('select public.workspace_directory(actor,team)from workspace_fixture','RP403:%','removed explicit request cannot drift into personal workspace');
select pg_temp.ws_ok((select(active_org_for_user(actor)=personal)and jsonb_array_length(workspace_directory(actor,null)->'workspaces')=1 from workspace_fixture),'unbound next-session directory recovers to remaining personal membership');
reset role;
insert into deletion_requests(user_id,status,payload)select actor,'pending','{}'from workspace_fixture;
set local role service_role;
select pg_temp.ws_denied('select public.select_workspace(actor,personal)from workspace_fixture','RP409:%','pending account deletion blocks selecting workspace');
select pg_temp.ws_denied('select public.workspace_directory(actor,personal)from workspace_fixture','RP409:%','pending account deletion blocks directory');
reset role;
select count(*)as passed from workspace_checks;
select name,passed from workspace_checks order by name;
rollback;
