/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=TourHostBindings` (hash: f31f3b563585c0355e94b90ae051574b)
interface __BaseEnv_TourHostBindings {
	ASSETS: Fetcher;
	SUPABASE_FUNCTIONS_URL: string;
	TOUR_CACHE_TTL: string;
	TURNSTILE_SITE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_TourHostBindings {}
}
interface TourHostBindings extends __BaseEnv_TourHostBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_FUNCTIONS_URL" | "TOUR_CACHE_TTL" | "TURNSTILE_SITE_KEY">> {}
}
