import {assert,assertEquals,assertRejects}from "https://deno.land/std@0.224.0/assert/mod.ts";
import{assertHostingAvailable,hostingRetention,hostingNoticeCurrent}from "./hosting-retention.ts";
import{HttpError}from "./http.ts";
const org="10000000-0000-4000-8000-000000000001";
const preserved={org_id:org,policy:"preserved",protected:false,retention_ends_at:null,hosting_available:true};
function database(data:unknown,error:unknown=null){const calls:unknown[]=[];return{calls,rpc:async(name:string,args:unknown)=>{calls.push({name,args});return{data,error};}};}
Deno.test("hosting reader preserves exact legacy/QA receipt and admits a prospective future deadline",async()=>{for(const data of[preserved,{...preserved,protected:true},{...preserved,policy:"prospective_90_day_grace",retention_ends_at:"2100-01-01T00:00:00Z"}]){const d=database(data);await assertHostingAvailable(d,org);assertEquals(d.calls,[{name:"hosting_retention_state",args:{p_org:org}}]);}});
Deno.test("hosting reader rejects exact cutoff, withdrawn access and malformed/foreign receipts",async()=>{for(const data of[{...preserved,policy:"prospective_90_day_grace",retention_ends_at:new Date().toISOString()},{...preserved,policy:"prospective_90_day_grace",retention_ends_at:"2020-01-01T00:00:00Z",hosting_available:false},{...preserved,org_id:"foreign"},{...preserved,retention_ends_at:"invalid"},{...preserved,policy:"invented"},null])await assertRejects(()=>assertHostingAvailable(database(data),org),HttpError);await assertRejects(()=>hostingRetention(database(preserved,{message:"private database detail"}),org),HttpError,"could not be verified");});
Deno.test("hosting notice guard leaves unrelated messages alone and rechecks every retained notice",async()=>{const d=database(true);assertEquals(await hostingNoticeCurrent(d,{id:"notice",payload:{}}),true);assertEquals(d.calls,[]);assertEquals(await hostingNoticeCurrent(d,{id:"notice",payload:{hosting_retention:{}}}),true);assertEquals(d.calls,[{name:"hosting_retention_notice_current",args:{p_outbox:"notice"}}]);assertEquals(await hostingNoticeCurrent(database(false),{id:"notice",payload:{hosting_retention:{}}}),false);await assertRejects(()=>hostingNoticeCurrent(database("true"),{id:"notice",payload:{hosting_retention:{}}}),HttpError);});
Deno.test("hosting notice explicit title/body survives the actual send template",async()=>{const {render}=await import("../notify/copy.ts");const payload={title:"Your workspace hosting period is ending",body:"Download original files from Library and your account JSON from Settings > Account data.",hosting_retention:{stage_days:7}};const message=render("allowance_low",payload);assertEquals(message.title,payload.title);assertEquals(message.body,payload.body);assert(message.body.includes("Library"));});
