import {assert,assertEquals,assertRejects}from "https://deno.land/std@0.224.0/assert/mod.ts";
const fixtureEnv={CLOUDFLARE_ACCOUNT_ID:"privacy-fixture",R2_ACCESS_KEY_ID:"fixture-access",R2_SECRET_ACCESS_KEY:"fixture-secret",R2_BUCKET_UPLOADS:"fixture-uploads",R2_BUCKET_RENDERS:"fixture-renders"};
const previousEnv=new Map(Object.keys(fixtureEnv).map(key=>[key,Deno.env.get(key)]));
let r2:typeof import("./r2.ts");
try {for(const[key,value]of Object.entries(fixtureEnv))Deno.env.set(key,value);r2=await import("./r2.ts?private-prefix-fixture");}
finally {for(const[key,value]of previousEnv)if(value===undefined)Deno.env.delete(key);else Deno.env.set(key,value);}

const org="de440103-0000-4000-8000-000000000001",target={bucket:"fixture-renders",org_id:org,prefix:`ai-router/${org}/`,removed_count:0};
function xml(keys:string[],truncated=false){return `<ListBucketResult><KeyCount>${keys.length}</KeyCount><IsTruncated>${truncated}</IsTruncated>${keys.map(key=>`<Contents><Key>${key}</Key></Contents>`).join("")}</ListBucketResult>`;}
async function fixture(responses:Response[],work:(calls:Request[])=>Promise<void>){const original=globalThis.fetch,calls:Request[]=[];globalThis.fetch=(input,init)=>{const req=new Request(input,init);calls.push(req);assert(new URL(req.url).hostname==="privacy-fixture.r2.cloudflarestorage.com");assert(req.headers.get("authorization")?.startsWith("AWS4-HMAC-SHA256"));assertEquals(req.redirect,"error");const response=responses.shift();if(!response)throw new Error("Unmodeled signed storage request");return Promise.resolve(response);};try{await work(calls);assertEquals(responses.length,0);}finally{globalThis.fetch=original;}}
Deno.test("owned prefix deletes one exact signed page then verifies physical absence",()=>fixture([new Response(xml([target.prefix+"one.jpg"])),new Response(null,{status:204}),new Response(xml([]))],async calls=>{assertEquals(await r2.deleteOwnedPrefixPage(target),{complete:true,deleted:1});assertEquals(calls.map(c=>c.method),["GET","DELETE","GET"]);assertEquals(new URL(calls[0].url).searchParams.get("prefix"),target.prefix);assertEquals(new URL(calls[0].url).searchParams.get("max-keys"),"32");assertEquals(new URL(calls[2].url).searchParams.get("max-keys"),"1");}));
Deno.test("remaining physical object cannot be reported complete",()=>fixture([new Response(xml([target.prefix+"one.jpg"],true)),new Response(null,{status:204}),new Response(xml([target.prefix+"two.jpg"]))],async()=>assertEquals(await r2.deleteOwnedPrefixPage(target),{complete:false,deleted:1})));
Deno.test("missing bucket, foreign key, truncated empty XML and traversal fail before DELETE",async()=>{for(const response of [new Response(null,{status:404}),new Response(xml([`ai-router/${org}x/foreign.jpg`])),new Response(xml([],true)),new Response(xml([target.prefix+"../foreign.jpg"])),new Response("<ListBucketResult><KeyCount>0</KeyCount><IsTruncated>false</IsTruncated>"),new Response("<ListBucketResult><IsTruncated>false</IsTruncated></ListBucketResult>")])await fixture([response],async calls=>{await assertRejects(()=>r2.deleteOwnedPrefixPage(target));assertEquals(calls.length,1);assertEquals(calls[0].method,"GET");});});
Deno.test("partial DELETE failure keeps cleanup unconfirmed with a single bounded dispatch",()=>fixture([new Response(xml([target.prefix+"one.jpg"])),new Response(null,{status:503})],async calls=>{await assertRejects(()=>r2.deleteOwnedPrefixPage(target));assertEquals(calls.map(c=>c.method),["GET","DELETE"]);}));
Deno.test("prefix authority rejects extra fields, arbitrary bucket or forged org before storage",async()=>{for(const raw of [{...target,extra:true},{...target,bucket:"fixture-public"},{...target,org_id:"other"},{...target,removed_count:-1},{...target,prefix:"ai-router/"}])await assertRejects(()=>r2.deleteOwnedPrefixPage(raw));});
