import {assert,assertEquals,assertRejects}from "https://deno.land/std@0.224.0/assert/mod.ts";
import {sweepPrivacyCleanup}from "./privacy-cleanup.ts";
const id="de330103-0000-4000-8000-000000000001",token="de330103-0000-4000-8000-000000000002",org="de330103-0000-4000-8000-000000000003";
const target={org_id:org,email:"buyer@fixture.invalid"};
function fixture(payload={r2:[{bucket:"renders",key:`ai-router/${org}/x.jpg`}],stream_uids:["fixture-stream"],ghl_targets:[target]}){let remaining:unknown=null;const calls:string[]=[];return{calls,get remaining(){return remaining;},admin:{rpc(name:string,args:Record<string,unknown>){calls.push(name);if(name==="privacy_cleanup_due")return Promise.resolve({data:[id],error:null});if(name==="privacy_cleanup_claim")return Promise.resolve({data:{id,token,org_id:org,payload},error:null});if(name==="privacy_cleanup_finish"){remaining=args.p_remaining;const p=remaining as {r2:unknown[],stream_uids:unknown[],ghl_targets:unknown[]};return Promise.resolve({data:{ok:true,id,cleanup_complete:!p.r2.length&&!p.stream_uids.length&&!p.ghl_targets.length},error:null});}throw new Error("Unknown RPC");}}};}
const operations={objects:async()=>({deleted:1,errors:[]}),stream:async()=>true,crm:async()=>({removed:1,untagged:0,leftover:0}),streamEnabled:()=>true};
Deno.test("privacy drainer requires acknowledgment of every actual target before completing",async()=>{const f=fixture();assertEquals(await sweepPrivacyCleanup(f.admin,operations),{ok:true,processed:1,completed:1,failed:0});assertEquals(f.remaining,{r2:[],stream_uids:[],ghl_targets:[]});assertEquals(f.calls,["privacy_cleanup_due","privacy_cleanup_claim","privacy_cleanup_finish"]);});
Deno.test("storage partial receipt, false stream acknowledgment and legacy leftovers stay durable",async()=>{const f=fixture();assertEquals(await sweepPrivacyCleanup(f.admin,{...operations,objects:async()=>({deleted:0,errors:[]}),stream:async()=>false,crm:async()=>({removed:0,untagged:0,leftover:1})}),{ok:true,processed:1,completed:0,failed:0});assertEquals(f.remaining,{r2:[{bucket:"renders",key:`ai-router/${org}/x.jpg`}],stream_uids:["fixture-stream"],ghl_targets:[target]});});
Deno.test("maintenance inventory outage, duplicate IDs and false completion receipt never pass",async()=>{
 for(const data of [null,[id,id],["bad"]])await assertRejects(()=>sweepPrivacyCleanup({rpc:()=>Promise.resolve({data,error:null})},operations));
 const f=fixture();const admin={rpc:async(name:string,args:Record<string,unknown>)=>name==="privacy_cleanup_finish"?{data:{ok:true,id,cleanup_complete:true},error:null}:await f.admin.rpc(name,args)};
 const out=await sweepPrivacyCleanup(admin,{...operations,objects:async()=>{throw new Error("Unavailable");}});assertEquals(out.failed,1);assertEquals(out.completed,0);
});
Deno.test("a frozen CRM target from another agency blocks all destructive dispatch",async()=>{const f=fixture({r2:[],stream_uids:[],ghl_targets:[{org_id:token,email:"other@fixture.invalid"}]});let destructive=0;const out=await sweepPrivacyCleanup(f.admin,{...operations,objects:async()=>{destructive++;return{deleted:0,errors:[]};},crm:async()=>{destructive++;return{removed:1,untagged:0,leftover:0};}});assertEquals(out.failed,1);assertEquals(destructive,0);assert(!f.calls.includes("privacy_cleanup_finish"));});
Deno.test("cleanup processes only bounded first job and retains unvisited target batches",async()=>{const r2=Array.from({length:10},(_,i)=>({bucket:"renders",key:`ai-router/${org}/${i}.jpg`}));const f=fixture({r2,stream_uids:[],ghl_targets:[]});const out=await sweepPrivacyCleanup(f.admin,{...operations,objects:async(batch,concurrency,cap)=>{assertEquals(batch.length,8);assertEquals(concurrency,4);assertEquals(cap,8);return{deleted:8,errors:[]};}});assertEquals(out.completed,0);assertEquals(f.remaining,{r2:r2.slice(8),stream_uids:[],ghl_targets:[]});});
