// AI media provenance — the write side of the compliance spine (W2-B3).
//
// Every AI generation records ONE row in public.media_provenance (migration
// 0012) saying what was altered, by which model, against which original, and
// with which public disclosure sentence. That table is what /tours/:slug reads
// to print the disclosure block on both the branded and the unbranded page, and
// what GET /me/compliance exports as the broker's audit log.
//
// Two rules this module exists to enforce:
//
//  1. BEST EFFORT, NEVER FATAL. The provider call is already made and already
//     billed by the time we get here; failing the user's edit because an audit
//     insert failed would trade a $0.04 image for a broken feature. Every call
//     is wrapped — a failure is logged and reported as
//     `provenance: { recorded:false, reason }` so the app can surface it (and
//     so it shows up in the function logs) without losing the result.
//
//  2. THE DISCLOSURE SENTENCE COMES FROM THE DATABASE. record_provenance()
//     derives it with public.provenance_disclosure(kind, edit); we return the
//     stored row's sentence verbatim. DISCLOSURE_FALLBACK below is a MIRROR of
//     that SQL, used only when there is no listing to record against (the app
//     is editing a photo before the listing is synced) so the UI still has copy
//     to show. Keep the two in sync — the SQL is authoritative for anything
//     that reaches a public tour.

import { userClient } from "./supabase.ts";

export type ProvenanceKind =
  | "photo_edit"
  | "virtual_stage"
  | "declutter"
  | "aerial"
  | "reel"
  | "other";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** A body field that must be a UUID when present. Returns null when absent. */
export function optionalUuid(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const s = v.trim();
  return UUID_RE.test(s) ? s : null;
}

/**
 * MIRROR of public.provenance_disclosure() (migration 0012 §2). Used only when
 * no row could be written; the DB copy is authoritative everywhere else.
 */
export function disclosureFallback(kind: ProvenanceKind, edit?: string | null): string {
  const e = (edit ?? "").trim().toLowerCase();
  switch (kind) {
    case "virtual_stage":
      return "This photo was virtually staged with AI: furniture and decor were digitally added or restyled. The architecture, dimensions, and views are unchanged.";
    case "declutter":
      return "This photo was digitally decluttered with AI: clutter and personal items were removed. The architecture, dimensions, and views are unchanged.";
    case "aerial":
      return "Drone-style movement is simulated. No drone footage was captured. This establishing shot was generated by AI.";
    case "reel":
      return "This clip was generated by AI from a still photo of the property. The motion is simulated; no video of this view was captured.";
    case "photo_edit":
      if (e === "twilight") {
        return "This photo was digitally altered with AI: the sky and lighting were changed to simulate dusk. The property itself is unchanged.";
      }
      if (e === "sky") {
        return "This photo was digitally altered with AI: the sky was replaced. The property itself is unchanged.";
      }
      if (e === "lawn") {
        return "This photo was digitally altered with AI: the lawn and landscaping were digitally repaired. The property itself is unchanged.";
      }
      return "This photo was digitally altered with AI. The architecture, dimensions, and views are unchanged.";
    default:
      return "This media was digitally altered or generated with AI.";
  }
}

export interface ProvenanceArgs {
  /** The listing the altered asset belongs to. Without it nothing is recorded. */
  listingId?: string | null;
  kind: ProvenanceKind;
  /** "Living room", "Aerial intro" — shown publicly next to the disclosure. */
  label?: string | null;
  /** The provider model string (internal; never returned by /tours). */
  modelId?: string | null;
  edit?: string | null;
  style?: string | null;
  /** Short, no PII. INTERNAL ONLY — the public tour never returns it. */
  promptSummary?: string | null;
  /** capture_asset of the untouched source (uploads role:"original"). */
  originalAssetId?: string | null;
  /** capture_asset of the published result, when it already exists. */
  alteredAssetId?: string | null;
  renderId?: string | null;
}

export interface ProvenanceResult {
  /** media_provenance.id, or null when nothing was written. */
  id: string | null;
  /** The sentence the public tour will show for this asset. Always present. */
  disclosure: string;
  recorded: boolean;
  /** Why nothing was written (only when recorded === false). */
  reason?: string;
}

/**
 * Record one provenance row as the CALLER (RLS + the RPC's owner/admin/agent
 * gate apply). Never throws.
 */
export async function recordProvenance(
  req: Request,
  args: ProvenanceArgs,
): Promise<ProvenanceResult> {
  const fallback = disclosureFallback(args.kind, args.edit);
  const listingId = optionalUuid(args.listingId);
  if (!listingId) {
    return {
      id: null,
      disclosure: fallback,
      recorded: false,
      reason: "no listing_id was sent, so this edit is not in the compliance log yet",
    };
  }

  try {
    const { data, error } = await userClient(req).rpc("record_provenance", {
      p_listing: listingId,
      p_kind: args.kind,
      p_label: args.label ?? null,
      p_model_id: args.modelId ?? null,
      p_edit: args.edit ?? null,
      p_style: args.style ?? null,
      p_prompt_summary: args.promptSummary ?? null,
      p_original_asset: optionalUuid(args.originalAssetId),
      p_altered_asset: optionalUuid(args.alteredAssetId),
      p_render: optionalUuid(args.renderId),
    });
    if (error) {
      console.error("record_provenance failed:", error.message);
      return { id: null, disclosure: fallback, recorded: false, reason: error.message };
    }
    const row = data as Record<string, unknown> | null;
    return {
      id: (row?.id as string) ?? null,
      disclosure: (row?.disclosure as string) ?? fallback,
      recorded: Boolean(row?.id),
    };
  } catch (e) {
    const reason = e instanceof Error ? e.message : String(e);
    console.error("record_provenance threw:", reason);
    return { id: null, disclosure: fallback, recorded: false, reason };
  }
}
