import Foundation
@main struct PushAccountIsolationTests {
 @MainActor static func main() async throws {
  var checks=0
  func check(_ value:Bool,_ message:String){guard value else{fatalError(message)};checks+=1}
  func tick()async{for _ in 0..<100{await Task.yield()};try? await Task.sleep(nanoseconds:20_000_000)}
  let a=UUID(uuidString:"11000000-0000-4000-8000-000000000001")!
  let b=UUID(uuidString:"11000000-0000-4000-8000-000000000002")!
  func identity(_ owner:UUID,_ revision:UInt64){AuthStore.shared.userID=owner.uuidString;AuthStore.shared.isSignedIn=true;AuthStore.shared.syncSessionRevision=revision;AuthStore.access=owner==a ? "synthetic-A" : "synthetic-B"}
  func reset(){PushHTTP.reset();SecureStore.values=[:];SecureStore.failSet=false;SecureStore.failRead=false;SecureStore.failRemove=false;UserDefaults.standard.values=[:];identity(a,1)}
  reset()
  let push=PushManager();PushHTTP.pausedOwner=a
  push.handleDeviceToken(Data([0xab,0xcd]));await tick()
  check(PushHTTP.requests.filter{$0.method=="POST"}.count==1,"Initial A registration missing")
  push.pendingRoute = .leads;push.showPrePrompt=true;PushHTTP.holdDelete=true
  push.accountWillChange();identity(b,2);push.accountDidChange();await tick()
  check(push.pendingRoute==nil && !push.showPrePrompt,"Old account presentation retained")
  check(PushHTTP.requests.filter{$0.method=="POST"}.count==1,"B POST crossed unacknowledged A cleanup")
  let deletion=PushHTTP.requests.first{$0.method=="DELETE"}!
  check(deletion.credential=="synthetic-A","Cleanup used replacement credential")
  check(deletion.body?["device_token"]as?String=="abcd" && deletion.body?["environment"]as?String=="sandbox","Cleanup token/environment changed")
  check(deletion.body?["user_id"]==nil && deletion.body?["session_id"]==nil,"Cleanup trusts client authority")
  check(try AuthStore.pendingPushUnregisters().count==1,"Cleanup was not retained before request")
  PushHTTP.deleteContinuation?.resume();PushHTTP.deleteContinuation=nil;await tick()
  check(push.acknowledgedOwner==b,"B binding missing after exact cleanup acknowledgment")
  check(try AuthStore.pendingPushUnregisters().isEmpty,"Acknowledged cleanup remained pending")
  PushHTTP.postContinuation?.resume();PushHTTP.postContinuation=nil;await tick()
  check(push.acknowledgedOwner==b,"Late A acknowledgment replaced B binding")
  push.handleDeviceToken(Data([0xab,0xcd]));await tick()
  check(PushHTTP.requests.filter{$0.method=="POST"}.count==2,"Same B token registered repeatedly")
  check(PushHTTP.requests.last{$0.method=="POST"}?.credential=="synthetic-B","B registration used A credential")
  reset();UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1");PushHTTP.holdDelete=true
  let overlapping=PushManager();overlapping.accountWillChange();identity(b,2);overlapping.accountDidChange();await tick()
  SecureStore.failSet=true;overlapping.accountWillChange();identity(a,3);overlapping.accountDidChange();await tick()
  PushHTTP.holdDelete=false;PushHTTP.deleteContinuation?.resume();PushHTTP.deleteContinuation=nil;await tick()
  check(PushHTTP.requests.filter{$0.method=="POST"}.isEmpty,"Cleanup admitted replacement across new failed retention")
  SecureStore.failSet=false;overlapping.accountDidChange();await tick()
  check(overlapping.acknowledgedOwner==a,"Overlapping failed retention did not recover")
  check(PushHTTP.requests.filter{$0.method=="DELETE"}.map{$0.credential}==["synthetic-A","synthetic-B"],"Overlapping cleanup lost original credentials")
  reset();identity(b,3)
  let cleanup=PendingPushUnregister(owner:a,deviceToken:"abcd",environment:"sandbox",accessToken:"synthetic-A")
  check(AuthStore.retainPushUnregister(cleanup),"Could not persist synthetic pending cleanup")
  UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1");PushHTTP.deleteResponse=Data(#"{"ok":true}"#.utf8)
  let restarted=PushManager();restarted.accountDidChange();await tick()
  check(PushHTTP.requests.filter{$0.method=="POST"}.isEmpty,"Incomplete cleanup acknowledgment permitted B POST")
  check(try AuthStore.pendingPushUnregisters()==[cleanup],"Incomplete acknowledgment erased durable barrier")
  reset();identity(b,4);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1")
  check(AuthStore.retainPushUnregister(cleanup),"Could not persist retry cleanup")
  for error in [APIError.badResponse(401),APIError.badResponse(403),APIError.server(400,"RP401")] {
   PushHTTP.deleteError=error;let expired=PushManager();expired.accountDidChange();await tick()
   check(expired.acknowledgedOwner==b,"Terminal cleanup prevented replacement registration")
   check(try AuthStore.pendingPushUnregisters().isEmpty,"Terminal credential remained queued")
   check(PushHTTP.requests.first{$0.method=="DELETE"}?.credential=="synthetic-A","Terminal cleanup used replacement credential")
   PushHTTP.reset();check(AuthStore.retainPushUnregister(cleanup),"Could not retain next terminal fixture")
  }
  reset();identity(b,4);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1")
  check(AuthStore.retainPushUnregister(cleanup),"Could not persist transient fixture")
  let transient=PushManager()
  for error:Error in [APIError.badResponse(503),URLError(.notConnectedToInternet)] {
   PushHTTP.deleteError=error;transient.accountDidChange();await tick()
   check(PushHTTP.requests.filter{$0.method=="POST"}.isEmpty,"Transient cleanup allowed replacement registration")
   check(try AuthStore.pendingPushUnregisters()==[cleanup],"Transient failure discarded cleanup")
  }
  PushHTTP.deleteError=nil;transient.accountDidChange();await tick()
  check(transient.acknowledgedOwner==b,"Transient cleanup could not recover")
  reset();UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1");SecureStore.failSet=true
  let failedStorage=PushManager();failedStorage.accountWillChange();identity(b,5);failedStorage.accountDidChange();await tick()
  check(PushHTTP.requests.isEmpty,"Failed secure retention permitted registration")
  check(UserDefaults.standard.bool(forKey:"push.unregisterStorageBlocked.v1"),"Secure storage failure was not durable")
  SecureStore.failSet=false;failedStorage.accountDidChange();await tick()
  check(failedStorage.acknowledgedOwner==b,"Recovered storage flag stranded replacement")
  check(!UserDefaults.standard.bool(forKey:"push.unregisterStorageBlocked.v1"),"Recovered storage flag remained sticky")
  check(PushHTTP.requests.first{$0.method=="DELETE"}?.credential=="synthetic-A","Failed-write recovery lost captured cleanup")
  reset();SecureStore.values[AuthStore.Keys.pendingPushUnregisters]="corrupt";identity(b,6);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1")
  let corrupt=PushManager();corrupt.accountDidChange();await tick()
  check(corrupt.acknowledgedOwner==b,"Readable corrupt queue stranded replacement")
  check(try AuthStore.pendingPushUnregisters().isEmpty,"Corrupt queue not reset")
  reset();SecureStore.values[AuthStore.Keys.pendingPushUnregisters]="corrupt";SecureStore.failRemove=true;identity(b,6);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1")
  let unremovable=PushManager();unremovable.accountDidChange();await tick()
  check(PushHTTP.requests.isEmpty && SecureStore.values[AuthStore.Keys.pendingPushUnregisters]=="corrupt","Corrupt queue that could not be securely removed admitted registration")
  SecureStore.failRemove=false;unremovable.accountDidChange();await tick()
  check(unremovable.acknowledgedOwner==b && SecureStore.values[AuthStore.Keys.pendingPushUnregisters]==nil,"Corrupt queue did not recover after secure removal")
  reset();identity(b,6);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1");UserDefaults.standard.set(true,forKey:"push.unregisterStorageBlocked.v1")
  let relaunched=PushManager();relaunched.accountDidChange();await tick()
  check(relaunched.acknowledgedOwner==b && !UserDefaults.standard.bool(forKey:"push.unregisterStorageBlocked.v1"),"Sticky failed-write flag stranded registration after relaunch with working storage")
  reset();identity(b,6);UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1");check(AuthStore.retainPushUnregister(cleanup),"Locked fixture unavailable")
  SecureStore.failRead=true;let locked=PushManager();locked.accountDidChange();await tick()
  check(PushHTTP.requests.isEmpty,"Locked Keychain was treated as empty")
  SecureStore.failRead=false;locked.accountDidChange();await tick()
  check(locked.acknowledgedOwner==b,"Unlocked Keychain did not recover")
  reset();check(AuthStore.retainPushUnregister(cleanup),"Startup cleanup fixture unavailable");AuthStore.shared.isSignedIn=false
  let signedOut=PushManager();signedOut.start();await tick()
  check(PushHTTP.requests.count==1 && PushHTTP.requests[0].method=="DELETE","Signed-out startup did not retry cleanup")
  check(try AuthStore.pendingPushUnregisters().isEmpty,"Signed-out retry did not drain queue")
  reset();UserDefaults.standard.set("abcd",forKey:"push.deviceToken.v1")
  let deleted=PushManager();deleted.accountWillChange(retainCleanup:false);await tick()
  check(PushHTTP.requests.isEmpty,"Confirmed account deletion queued dead credential")
  check(try AuthStore.pendingPushUnregisters().isEmpty,"Confirmed deletion left cleanup record")
  check(AuthStore.retainPushUnregister(cleanup),"Wipe fixture unavailable");UserDefaults.standard.set(true,forKey:"push.unregisterStorageBlocked.v1")
  deleted.discardPendingCleanup()
  check(try AuthStore.pendingPushUnregisters().isEmpty,"Device erasure retained captured credential")
  check(!UserDefaults.standard.bool(forKey:"push.unregisterStorageBlocked.v1"),"Device erasure retained blocked flag")
  identity(b,6)
  let bid=PushAccountIdentity(owner:b,revision:6)
  check(!PushManager.accepts(payload:["recipient_user_id":a.uuidString,"rp":["type":"leads"]],identity:bid),"Other account notification accepted")
  check(!PushManager.accepts(payload:["rp":["type":"leads"]],identity:bid),"Legacy unbound notification accepted")
  check(!PushManager.accepts(payload:["recipient_user_id":b.uuidString],identity:nil),"Signed-out notification accepted")
  check(PushManager.accepts(payload:["recipient_user_id":b.uuidString],identity:bid),"Current account notification rejected")
  check(!PushManager.accepts(payload:["recipient_user_id":"malformed"],identity:bid),"Malformed recipient accepted")
  let actualPayload:[AnyHashable:Any] = ["recipient_user_id":b.uuidString,"category":"lead_received","deep_link":"https://rendprop.com/f/synthetic-listing","data":["slug":"synthetic-listing"]]
  let routes=PushManager();routes.handle(payload:actualPayload)
  check(routes.pendingRoute == .leads,"Actual emitted lead notification did not open inbox")
  routes.pendingRoute=nil
  routes.handle(payload:["recipient_user_id":a.uuidString,"category":"lead_received","deep_link":"https://rendprop.com/f/synthetic-listing"])
  check(routes.pendingRoute==nil,"Foreign emitted lead notification opened a route")
  routes.handle(payload:["recipient_user_id":b.uuidString,"category":"render_finished","deep_link":"https://foreign.invalid/f/foreign"])
  check(routes.pendingRoute==nil,"Untrusted emitted URL opened a route")
  routes.handle(payload:["recipient_user_id":b.uuidString,"category":"render_finished","deep_link":"https://rendprop.com/f/synthetic-listing"])
  check(routes.pendingRoute == .tour(.tour(slug:"synthetic-listing")),"Actual emitted render link did not open")
  let root=RootIncomingHarness();root.incomingAccountOwner=a.uuidString
  root.incomingQueue.enqueue(.leads);root.incomingQueue.enqueue(.link(.tour(slug:"A-private")))
  root.accountChanged(nextOwner:b.uuidString)
  check(!root.incomingQueue.hasPending,"A queued account route survived owner change")
  root.incomingQueue.enqueue(.leads);root.accountChanged(nextOwner:nil)
  check(!root.incomingQueue.hasPending,"Signed-out account route survived owner change")
  let cold=RootIncomingHarness();cold.incomingQueue.enqueue(.link(.tour(slug:"public-cold-link")))
  cold.accountChanged(nextOwner:b.uuidString)
  check(cold.incomingQueue.takeNext(canPresent:true) == .link(.tour(slug:"public-cold-link")),"Cold external public link was lost at first sign-in")
  print("PASS: \(checks) actual push account isolation assertions; closed synthetic HTTP/Keychain/OS")
 }
}
