import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "node:http";
import { build } from "vite";
import { chromium, expect } from "@playwright/test";

const root = fileURLToPath(new URL("../", import.meta.url)), artifacts = await mkdtemp(join(tmpdir(), "rendprop-business-browser-")), dist = join(artifacts, "dist");
const receipt = { proof: "Isolated real business UI with native-contract responses; no live customer account or outgoing mail", checks: [], externalRequests: [], errors: [] };
async function sourceManifest() {
  const files = [];
  async function visit(dir) { for (const entry of await readdir(join(root, dir), { withFileTypes: true })) { const name = `${dir}/${entry.name}`; if (entry.isDirectory()) await visit(name); else files.push(name); } }
  await visit("src"); await visit("tests");
  files.push("package.json", "package-lock.json", "tsconfig.json", "index.html");
  return Object.fromEntries(await Promise.all([...new Set(files)].sort().map(async path => [path, createHash("sha256").update(await readFile(join(root,path))).digest("hex")])));
}
receipt.sourceHashes = await sourceManifest();
let browser, server;
try {
  await build({ configFile: false, root, publicDir: false, logLevel: "error", build: { outDir: dist, rollupOptions: { input: join(root, "tests/business-fixture.html") } } });
  server = createServer(async (request, response) => { const path = resolve(dist, `.${new URL(request.url, "http://localhost").pathname}`); if (!path.startsWith(`${dist}/`)) return response.writeHead(400).end(); try { response.setHeader("Content-Type", ({ ".html": "text/html", ".js": "application/javascript", ".css": "text/css" })[extname(path)] ?? "application/octet-stream"); response.end(await readFile(path)); } catch { response.writeHead(404).end(); } });
  await new Promise((done) => server.listen(0, "127.0.0.1", done));
  const origin = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ headless: true, executablePath: process.env.STUDIO_BROWSER_EXECUTABLE });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: "block" });
  await context.route("**/*", (route) => { if (new URL(route.request().url()).origin === origin && route.request().method() === "GET") return route.continue(); receipt.externalRequests.push(route.request().url()); return route.abort(); });
  const page = await context.newPage(); page.on("pageerror", (e) => receipt.errors.push(e.message)); page.setDefaultTimeout(6000);
  const nav = (name) => page.getByRole("navigation", { name: "Business tools" }).getByRole("button", { name, exact: true });
  await page.goto(`${origin}/tests/business-fixture.html`);
  await page.getByRole("button", { name: "Alex Buyer", exact: true }).click();
  await expect(page.getByText("Can I see the garden?", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Status for Alex Buyer" }).selectOption("contacted");
  await expect(page.getByRole("status")).toContainText("marked contacted");
  receipt.checks.push("Lead details and status roundtrip through native route");
  await nav("Agent card").click(); await page.getByLabel("Display name", { exact: true }).fill("Office Agent");
  await page.getByRole("button", { name: "Save personal card", exact: true }).click(); await expect(page.getByRole("status")).toContainText("Personal card saved");
  await nav("Leads").click(); await nav("Agent card").click(); await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Office Agent");
  receipt.checks.push("Personal card persists across panel navigation without copying workspace branding");
  const personal = page.getByRole("form",{name:"Personal contact card"});
  await personal.getByLabel("Public phone",{exact:true}).fill("+44 20 7946 0958");await page.evaluate(()=>window.businessFixture.failPersonal());await personal.getByRole("button",{name:"Save personal card",exact:true}).click();await expect(personal.getByRole("alert")).toContainText("draft kept");await expect(personal.getByLabel("Public phone",{exact:true})).toHaveValue("+44 20 7946 0958");
  await personal.getByRole("button",{name:"Save personal card",exact:true}).click();await expect(personal.getByRole("status")).toContainText("Personal card saved");assert.equal((await page.evaluate(()=>window.businessFixture.brand())).name,"Agent");
  await personal.getByLabel("Public phone",{exact:true}).fill("+44 20 7946 1000");await page.evaluate(()=>window.businessFixture.phoneCard({phone:"+44 20 7946 2000"}));await personal.getByRole("button",{name:"Save personal card",exact:true}).click();await expect(personal.getByRole("alert")).toContainText("changed");await expect(personal.getByLabel("Public phone",{exact:true})).toHaveValue("+44 20 7946 1000");
  page.once("dialog",dialog=>dialog.accept());await personal.getByRole("button",{name:"Reload personal card"}).click();await expect(personal.getByLabel("Public phone",{exact:true})).toHaveValue("+44 20 7946 2000");
  receipt.checks.push("Personal rejected Save and same-field phone conflict retain the draft; explicit Reload adopts winner and workspace inviter identity stays intact");
  const portfolio=page.getByRole("region",{name:"Hosted portfolio selection"});await expect(portfolio.getByRole("checkbox")).not.toBeChecked();await portfolio.getByRole("checkbox").check();await portfolio.getByRole("button",{name:"Save hosted portfolio selection"}).click();await expect(portfolio.getByRole("status")).toContainText("selected listings");await expect(portfolio.getByRole("link",{name:"View your hosted portfolio"})).toHaveAttribute("href",/^https:\/\/rendprop.com\/a\/member-/);await portfolio.getByRole("checkbox").uncheck();await portfolio.getByRole("button",{name:"Save hosted portfolio selection"}).click();await expect(portfolio.getByRole("checkbox")).not.toBeChecked();
  receipt.checks.push("Hosted portfolio begins empty, publishes only an explicit selected listing and supports deliberate clearing");
  await nav("Account & plan").click(); await page.getByLabel("New leads", { exact: true }).uncheck();
  await page.getByRole("button", { name: "Save notification preferences" }).click(); await expect(page.getByRole("status")).toContainText("preferences saved");
  await page.getByText("Delete Rendprop account", { exact: true }).click(); await page.getByRole("button", { name: "Review account deletion" }).click();
  await expect(page.getByRole("button", { name: "Permanently delete my account" })).toBeDisabled();
  receipt.checks.push("Notification preference write and guarded account deletion");
  const trial = { org_id: "22222222-2222-4222-8222-222222222222", status: "active", starts_at: "2026-10-29T12:00:00Z", ends_at: "2026-11-05T12:00:00Z", walkthroughs: { used: 1, cap: 1, remaining: 0 }, photo_edits: { used: 2, cap: 5, remaining: 3 }, published_listings: { used: 0, cap: 1, remaining: 1 }, upload_budget_bytes: 1_073_741_824, upload_used_bytes: 100 };
  await page.evaluate(value => window.businessFixture.trial(value), trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  const trialCard = page.getByRole("region", { name: "Your trial" });
  await expect(trialCard).toContainText("3 remaining"); await expect(trialCard).toContainText("1 remaining");
  await expect(trialCard).toContainText("Upload space"); await expect(trialCard).toContainText("including files still uploading");
  await expect(page.locator(".business-plan-name")).toHaveText("pro trial");
  await expect(trialCard.getByRole("progressbar", { name: "Hosted walkthrough: 1 used of 1" })).toBeVisible();
  await expect(trialCard).toContainText("does not bring Apple’s renewal date forward");
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "Trial card stays inside phone width");
  await page.screenshot({ path: join(artifacts, "trial-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(value => window.businessFixture.trial({ ...value, status: "expired" }), trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(trialCard).toContainText("creation window has ended"); await expect(trialCard).toContainText("downloads remain accessible");
  await page.evaluate(value => window.businessFixture.trial({ ...value, photo_edits: { used: 2, cap: 5, remaining: 5 } }), trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(page.getByRole("alert")).toContainText("allowance could not be verified");
  await expect(trialCard).toHaveCount(0); await expect(page.getByText("The plan could not be verified. Refresh before starting new paid work.", { exact: true })).toBeVisible();
  await page.evaluate(() => window.businessFixture.trial(null));
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(trialCard).toHaveCount(0); await expect(page.locator(".business-plan-name")).toHaveText("team");
  await expect(page.getByText(/Current access through/)).toContainText("2026");
  receipt.checks.push("Trial counters refresh independently, expiry preserves downloads, corrupt refresh hides stale allowance, paid renewal shows fresh plan and date at desktop/phone widths");
  const pending = { org_id: trial.org_id, available: false, funded: false, authority: "subscription_activation_unavailable" };
  await page.evaluate(value => window.businessFixture.activation(value, "pro"), pending);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  const pendingCard = page.getByRole("region", { name: "Service activation pending" });
  await expect(pendingCard).toContainText("subscription is recorded"); await expect(pendingCard).toContainText("included creation service is not active");
  await expect(pendingCard).toContainText("saved work and downloads remain available");
  await expect(page.locator(".business-plan-name")).toHaveText("pro");
  await expect(page.getByRole("region", { name: "Current allowance" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Manage Apple subscriptions ↗" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Choose or restore your plan on iPhone ↗" })).toBeVisible();
  await page.evaluate(value => window.businessFixture.activation(value, "starter"), pending);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(pendingCard).toContainText("included creation service is not active");
  await expect(page.locator(".business-plan-name")).toHaveText("starter");
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "Pending service stays inside phone width");
  await page.screenshot({ path: join(artifacts, "service-pending-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(value => { window.businessFixture.trial(value); window.businessFixture.activation({ org_id: value.org_id, available: false, funded: false, authority: "subscription_activation_unavailable" }, "pro"); }, trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(pendingCard).toContainText("Recorded trial usage: 1 / 1 walkthroughs, 2 / 5 photo edits and 0 / 1 published listings");
  await expect(pendingCard).toContainText("new creation is unavailable until service activation succeeds");
  await expect(trialCard).toHaveCount(0);
  await page.evaluate(value => { window.businessFixture.trial({ ...value, status: "expired" }); window.businessFixture.activation({ org_id: value.org_id, available: false, funded: false, authority: "subscription_activation_unavailable" }, "free"); }, trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(trialCard).toContainText("creation window has ended"); await expect(pendingCard).toHaveCount(0);
  await expect(page.locator(".business-plan-name")).toHaveText("free");
  await page.evaluate(value => { window.businessFixture.trial(null); window.businessFixture.activation(value, "free", "2026-09-01T12:00:00Z"); }, pending);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(trialCard).toHaveCount(0); await expect(pendingCard).toHaveCount(0);
  await expect(page.locator(".business-plan-name")).toHaveText("free");
  await page.evaluate(value => { window.businessFixture.trial({ ...value, status: "exhausted", walkthroughs: { used: 1, cap: 1, remaining: 0 }, photo_edits: { used: 5, cap: 5, remaining: 0 }, published_listings: { used: 1, cap: 1, remaining: 0 } }); window.businessFixture.activation({ org_id: value.org_id, available: false, funded: false, authority: "subscription_activation_unavailable" }, "pro"); }, trial);
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(trialCard).toContainText("used your included trial allowance"); await expect(pendingCard).toHaveCount(0);
  for (const bad of [{ ...pending, org_id: "99999999-9999-4999-8999-999999999999" }, { ...pending, available: true }, { ...pending, authority: "verified_retail", available: true, funded: false }]) {
    await page.evaluate(value => window.businessFixture.activation(value, "pro"), bad);
    await page.getByRole("button", { name: "Refresh allowance" }).click();
    await expect(page.getByRole("alert")).toContainText(/activation.*(?:different workspace|could not be verified)/);
    await expect(trialCard).toHaveCount(0); await expect(pendingCard).toHaveCount(0);
    await expect(page.getByText("The plan could not be verified. Refresh before starting new paid work.", { exact: true })).toBeVisible();
  }
  await page.evaluate(value => { window.businessFixture.trial(null); window.businessFixture.activation(value, "team"); }, { ...pending, authority: "verified_retail", available: true, funded: true });
  await page.getByRole("button", { name: "Refresh allowance" }).click();
  await expect(pendingCard).toHaveCount(0); await expect(trialCard).toHaveCount(0);
  await expect(page.locator(".business-plan-name")).toHaveText("team");
  await expect(page.getByRole("region", { name: "Current allowance" })).toContainText("2 / 2");
  receipt.checks.push("Exact service activation: pending preserves signed plan and saved work at 390 px, expired/free history and exhausted counters win, malformed or foreign activation hides caps, verified paid response restores meters");
  await nav("Team").click(); await page.getByRole("textbox", { name: /^Email addresses/ }).fill("agent@example.invalid");
  await expect(page.getByRole("button", { name: "Create & send invitations" })).toBeDisabled();
  await page.getByLabel(/Send an invitation email to 1 person/).check(); await page.getByRole("button", { name: "Create & send invitations" }).click();
  await expect(page.getByRole("textbox", { name: "Invitation link for agent@example.invalid" })).toHaveValue("https://rendprop.com/join/ABCD-EFGH-JKLM");
  receipt.checks.push("Invite email requires explicit form opt-in and displays one-time share link");
  await nav("Team activity").click(); await expect(page.getByRole("table")).toContainText("Tours published");
  await nav("AI disclosures").click(); await expect(page.getByText("Virtually staged with AI", { exact: true })).toBeVisible();
  receipt.checks.push("Team publishing and disclosure records render without raw payloads");
  await page.evaluate(() => window.businessFixture.marketing()); await nav("Leads").click();
  await expect(page.getByRole("combobox", { name: "Status for Alex Buyer" })).toHaveCount(0);
  await expect(nav("Team activity")).toHaveCount(0); await nav("Agent card").click(); await expect(page.getByLabel("Business name", { exact: true })).toBeDisabled();
  receipt.checks.push("Marketing role has read-only lead/shared-brand controls and keeps its own personal card; no team overview");
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "No horizontal page overflow on phone width");
  await page.screenshot({ path: join(artifacts, "business-mobile.png"), fullPage: true });
  receipt.checks.push("Responsive business workspace at 390px");
  const calls = await page.evaluate(() => window.businessFixture.calls());
  assert.equal(calls.filter((c) => c.method === "DELETE").length, 0);
  assert.equal(calls.filter((c) => c.method === "POST").length, 1);
  for (const persona of ["delegated-owner", "invited-agent"]) {
    await page.goto(`${origin}/tests/business-fixture.html?teamPersona=${persona}`);
    await expect(page.getByRole("combobox", { name: "Status for Alex Buyer" })).toBeVisible();
    await nav("Team").click();
    await expect(page.getByRole("table", { name: "Current team members" })).toBeVisible();
    if (persona === "delegated-owner") {
      await expect(page.getByRole("textbox", { name: /^Email addresses/ })).toBeVisible();
      await expect(page.getByRole("button", { name: "Create invite link", exact: true })).toBeEnabled();
      await expect(nav("Team activity")).toBeVisible();
      await nav("Team activity").click();
      await expect(page.getByRole("table")).toContainText("Tours published");
      receipt.checks.push("Delegated agent-library view retains Team-owner management from bound parent actor authority, not displayed team_owner role");
    } else {
      await expect(page.getByRole("textbox", { name: /^Email addresses/ })).toHaveCount(0);
      await expect(page.getByRole("button", { name: "Create invite link", exact: true })).toHaveCount(0);
      await expect(nav("Team activity")).toHaveCount(0);
      await expect(page.getByText("Visible invitations", { exact: true })).toBeVisible();
      receipt.checks.push("Invited agent owns its private library and can edit its own leads but cannot manage parent Team or open Team activity");
    }
    const scopedCalls = await page.evaluate(() => window.businessFixture.calls());
    assert.ok(scopedCalls.some(c => c.path === "/functions/v1/team"), "Actual Team panel must read fresh summary");
    assert.ok(scopedCalls.every(c => c.orgId === "55555555-5555-4555-8555-555555555555"), "Team reads keep logical selected-library header rather than granting parent content access");
    assert.ok(scopedCalls.every(c => c.method === "GET"), "Permission verification must not send an invitation or mutate an account");
  }
  assert.deepEqual(receipt.errors, []); assert.deepEqual(receipt.externalRequests, []);
  assert.deepEqual(await sourceManifest(),receipt.sourceHashes,"Source changed during browser verification");receipt.status = "passed"; await writeFile(join(artifacts, "receipt.json"), JSON.stringify(receipt, null, 2)); console.log(JSON.stringify({ ...receipt, artifacts }, null, 2));
} finally { await browser?.close(); if (server) await new Promise((done) => server.close(done)); }
