import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "node:http";
import { build } from "vite";
import { chromium, expect } from "@playwright/test";

const root = fileURLToPath(new URL("../", import.meta.url)), artifacts = await mkdtemp(join(tmpdir(), "rendprop-business-browser-")), dist = join(artifacts, "dist");
const receipt = { proof: "Isolated real business UI with native-contract responses; no live customer account or outgoing mail", checks: [], externalRequests: [], errors: [] };
let browser, server;
try {
  await build({ configFile: false, root, publicDir: false, logLevel: "error", build: { outDir: dist, rollupOptions: { input: join(root, "tests/business-fixture.html") } } });
  server = createServer(async (request, response) => { const path = resolve(dist, `.${new URL(request.url, "http://localhost").pathname}`); if (!path.startsWith(`${dist}/`)) return response.writeHead(400).end(); try { response.setHeader("Content-Type", ({ ".html": "text/html", ".js": "application/javascript", ".css": "text/css" })[extname(path)] ?? "application/octet-stream"); response.end(await readFile(path)); } catch { response.writeHead(404).end(); } });
  await new Promise((done) => server.listen(0, "127.0.0.1", done));
  const origin = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ headless: true, executablePath: process.env.STUDIO_BROWSER_EXECUTABLE });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: "block" });
  await context.route("**/*", (route) => { if (new URL(route.request().url()).origin === origin && route.request().method() === "GET") return route.continue(); receipt.externalRequests.push(route.request().url()); return route.abort(); });
  const page = await context.newPage(); page.on("pageerror", (e) => receipt.errors.push(e.message)); page.setDefaultTimeout(6000);
  const nav = (name) => page.getByRole("navigation", { name: "Business tools" }).getByRole("button", { name, exact: true });
  await page.goto(`${origin}/tests/business-fixture.html`);
  await page.getByRole("button", { name: "Alex Buyer", exact: true }).click();
  await expect(page.getByText("Can I see the garden?", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Status for Alex Buyer" }).selectOption("contacted");
  await expect(page.getByRole("status")).toContainText("marked contacted");
  receipt.checks.push("Lead details and status roundtrip through native route");
  await nav("Brand & portfolio").click(); await page.getByLabel("Display name", { exact: true }).fill("Office Agent");
  await page.getByRole("button", { name: "Save brand", exact: true }).click(); await expect(page.getByRole("status")).toContainText("Brand saved");
  await nav("Leads").click(); await nav("Brand & portfolio").click(); await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Office Agent");
  receipt.checks.push("Brand persists through remote reload and matches card preview");
  await nav("Account & plan").click(); await page.getByLabel("New leads", { exact: true }).uncheck();
  await page.getByRole("button", { name: "Save notification preferences" }).click(); await expect(page.getByRole("status")).toContainText("preferences saved");
  await page.getByText("Delete Rendprop account", { exact: true }).click(); await page.getByRole("button", { name: "Review account deletion" }).click();
  await expect(page.getByRole("button", { name: "Permanently delete my account" })).toBeDisabled();
  receipt.checks.push("Notification preference write and guarded account deletion");
  await nav("Team").click(); await page.getByRole("textbox", { name: /^Email addresses/ }).fill("agent@example.invalid");
  await expect(page.getByRole("button", { name: "Create & send invitations" })).toBeDisabled();
  await page.getByLabel(/Send an invitation email to 1 person/).check(); await page.getByRole("button", { name: "Create & send invitations" }).click();
  await expect(page.getByRole("textbox", { name: "Invitation link for agent@example.invalid" })).toHaveValue("https://rendprop.com/join/ABCD-EFGH-JKLM");
  receipt.checks.push("Invite email requires explicit form opt-in and displays one-time share link");
  await nav("Team activity").click(); await expect(page.getByRole("table")).toContainText("Tours published");
  await nav("AI disclosures").click(); await expect(page.getByText("Virtually staged with AI", { exact: true })).toBeVisible();
  receipt.checks.push("Team publishing and disclosure records render without raw payloads");
  await page.evaluate(() => window.businessFixture.marketing()); await nav("Leads").click();
  await expect(page.getByRole("combobox", { name: "Status for Alex Buyer" })).toHaveCount(0);
  await expect(nav("Team activity")).toHaveCount(0); await nav("Brand & portfolio").click(); await expect(page.getByLabel("Display name", { exact: true })).toBeDisabled();
  receipt.checks.push("Marketing role has read-only lead and brand controls; no team overview");
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "No horizontal page overflow on phone width");
  await page.screenshot({ path: join(artifacts, "business-mobile.png"), fullPage: true });
  receipt.checks.push("Responsive business workspace at 390px");
  const calls = await page.evaluate(() => window.businessFixture.calls());
  assert.equal(calls.filter((c) => c.method === "DELETE").length, 0);
  assert.equal(calls.filter((c) => c.method === "POST").length, 1);
  assert.deepEqual(receipt.errors, []); assert.deepEqual(receipt.externalRequests, []);
  receipt.status = "passed"; await writeFile(join(artifacts, "receipt.json"), JSON.stringify(receipt, null, 2)); console.log(JSON.stringify({ ...receipt, artifacts }, null, 2));
} finally { await browser?.close(); if (server) await new Promise((done) => server.close(done)); }
