import assert from "node:assert/strict";
import {mkdtemp, readFile, writeFile, open} from "node:fs/promises";
import {createHash} from "node:crypto";
import {createReadStream} from "node:fs";
import {tmpdir} from "node:os";
import {join, extname, resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {createServer} from "node:http";
import {execFileSync} from "node:child_process";
import {build} from "vite";
import {chromium, expect} from "@playwright/test";
const root = fileURLToPath(new URL("../", import.meta.url)), artifacts = await mkdtemp(join(tmpdir(), "rendprop-finishing-")), dist = join(artifacts, "dist");
const receipt = {proof: "Real editor UI, synthetic original footage and licensed-audio fixture, real H.264/AAC export decoded for music/original/narration mixing and timed caption pixels. No live media, account or provider.", checks: [], errors: [], externalRequests: [], status: "running"};
let browser, server;
try {
  await build({configFile: false, root, publicDir: false, logLevel: "error", build: {outDir: dist, rollupOptions: {input: join(root, "tests/finishing-fixture.html")}}});
  server = createServer(async (request, response) => {
    const path = resolve(dist, `.${new URL(request.url, "http://localhost").pathname}`);
    if (!path.startsWith(`${dist}/`)) return response.writeHead(400).end();
    try {response.setHeader("Content-Type", ({".html":"text/html", ".js":"application/javascript", ".css":"text/css"})[extname(path)] ?? "application/octet-stream"); response.end(await readFile(path));} catch {response.writeHead(404).end();}
  });
  await new Promise(done => server.listen(0, "127.0.0.1", done));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const video = join(artifacts, "source.mp4"), music = join(artifacts, "music.wav"), voice = join(artifacts, "voice.wav");
  execFileSync("ffmpeg", ["-v", "error", "-f", "lavfi", "-i", "color=c=blue:s=640x360:r=30:d=4", "-f", "lavfi", "-i", "sine=frequency=660:duration=4", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", video]);
  for (const [file, frequency, seconds] of [[music,440,10],[voice,880,1]]) execFileSync("ffmpeg", ["-v", "error", "-f", "lavfi", "-i", `sine=frequency=${frequency}:duration=${seconds}:sample_rate=48000`, "-c:a", "pcm_s16le", file]);
  browser = await chromium.launch({headless: true, executablePath: process.env.STUDIO_BROWSER_EXECUTABLE});
  const context = await browser.newContext({viewport:{width:1440,height:1100}, acceptDownloads:true, serviceWorkers:"block"});
  await context.route("**/*", route => {const url = new URL(route.request().url()); if (url.origin === origin && route.request().method() === "GET" || url.protocol === "blob:") return route.continue(); receipt.externalRequests.push(url.href); return route.abort();});
  const page = await context.newPage(); page.setDefaultTimeout(12000); page.on("pageerror", error => receipt.errors.push(error.message));
  await page.goto(`${origin}/tests/finishing-fixture.html`);
  const snapshot = () => page.evaluate(() => window.finishingFixture.snapshot());
  await page.getByLabel("Add photos or videos", {exact:true}).setInputFiles(video);
  await expect.poll(async () => (await snapshot()).draft.clips.length).toBe(1);
  await page.getByText("Sound & captions", {exact:true}).click();
  await expect(page.getByLabel("Add licensed music", {exact:true})).toBeDisabled();
  await page.getByLabel("I have permission to use this music", {exact:true}).check();
  await page.getByLabel("Add licensed music", {exact:true}).setInputFiles(music);
  await expect.poll(async () => !!(await snapshot()).draft.music).toBe(true);
  await page.getByLabel("Music volume", {exact:true}).fill("0.5");
  await page.getByText("Music timing and fades", {exact:true}).click();
  await page.getByLabel("Music fade in", {exact:true}).fill("1");
  await page.getByRole("button", {name:"Transcribe selected clip", exact:true}).click();
  await expect.poll(async () => (await snapshot()).requests.length).toBe(1);
  await page.evaluate(() => window.finishingFixture.resolve(0, true));
  await expect(page.getByText("The transcript does not match this original clip.", {exact:true})).toBeVisible();
  assert.equal((await snapshot()).draft.speech, undefined);
  await page.getByRole("button", {name:"Transcribe selected clip", exact:true}).click();
  await expect.poll(async () => (await snapshot()).requests.length).toBe(2);
  await page.getByLabel("Title overlay", {exact:true}).fill("Latest title");
  await page.evaluate(() => window.finishingFixture.resolve(1));
  await expect(page.getByRole("region", {name:"Review speech captions", exact:true})).toHaveCount(0);
  assert.equal((await snapshot()).draft.speech, undefined);
  receipt.checks.push("Source fingerprint mismatch and late analysis after a manual edit cannot add captions or overwrite the current draft");
  await page.getByLabel("Title overlay", {exact:true}).fill("");
  await page.getByRole("button", {name:"Transcribe selected clip", exact:true}).click();
  await expect.poll(async () => (await snapshot()).requests.length).toBe(3);
  await page.evaluate(() => window.finishingFixture.resolve(2));
  await expect(page.getByRole("button", {name:"Apply reviewed captions", exact:true})).toBeDisabled();
  await page.getByLabel("I checked these words and timings against the original clip", {exact:true}).check();
  const beforePassage=(await snapshot()).draft;
  await page.getByRole("button", {name:"Use speaking passage 1",exact:true}).click();
  await expect.poll(async()=>(await snapshot()).draft.clips[0].start).toBe(.4);
  await expect.poll(async()=>(await snapshot()).draft.clips[0].end).toBe(1.5);
  assert.equal((await snapshot()).draft.clips[0].source.sha256,beforePassage.clips[0].source.sha256);
  await page.getByLabel("Trim start (sec)",{exact:true}).fill("0");
  await page.getByLabel("Trim end (sec)",{exact:true}).fill("4");
  receipt.checks.push("A transcript-backed speaking passage stays unchanged until reviewed, then explicitly trims the selected original and applies its verified captions");
  await expect.poll(async () => (await snapshot()).draft.speech?.length ?? 0).toBe(1);
  const photo = await page.evaluate(() => {const canvas=document.createElement("canvas"); canvas.width=720;canvas.height=1280; const ctx=canvas.getContext("2d");ctx.fillStyle="red";ctx.fillRect(0,0,720,1280);return canvas.toDataURL().split(",")[1];});
  await page.getByLabel("Add photos or videos", {exact:true}).setInputFiles({name:"red.png",mimeType:"image/png",buffer:Buffer.from(photo,"base64")});
  await expect.poll(async () => (await snapshot()).draft.clips.length).toBe(2);
  await page.getByRole("button", {name:/Select clip 2:/}).click();
  await page.getByLabel("Photo duration (seconds)", {exact:true}).fill("4");
  await page.evaluate(bytes => window.finishingFixture.voice(bytes), [...await readFile(voice)]);
  await page.getByLabel("Saved narration", {exact:true}).selectOption("00000000-0000-0000-0000-000000000001");
  await page.getByLabel("Narration starts at (seconds)", {exact:true}).fill("5");
  await expect(page.getByRole("button", {name:"Export MP4", exact:true})).toBeEnabled();
  await page.getByRole("button", {name:"Export MP4", exact:true}).click();
  await expect(page.getByRole("link", {name:/Download MP4/})).toBeVisible({timeout:30000});
  const download = page.waitForEvent("download"); await page.getByRole("link", {name:/Download MP4/}).click();
  const output=join(artifacts,"music-captions-mix.mp4"); await (await download).saveAs(output);
  const probe=JSON.parse(execFileSync("ffprobe",["-v","error","-show_entries","stream=codec_name,codec_type:format=duration","-of","json",output],{encoding:"utf8"}));
  assert(probe.streams.some(stream=>stream.codec_name==="aac"));assert(probe.streams.some(stream=>stream.codec_name==="h264"));assert(Math.abs(Number(probe.format.duration)-8)<.5);
  function amplitude(time, frequency) {
    const bytes=execFileSync("ffmpeg",["-v","error","-ss",String(time),"-i",output,"-t","0.15","-vn","-ac","1","-ar","48000","-f","f32le","pipe:1"]);
    const data=new Float32Array(bytes.buffer,bytes.byteOffset,bytes.byteLength/4);let real=0,imaginary=0;
    for(let i=0;i<data.length;i++){real+=data[i]*Math.cos(2*Math.PI*frequency*i/48000);imaginary+=data[i]*Math.sin(2*Math.PI*frequency*i/48000);}
    return 2*Math.hypot(real,imaginary)/data.length;
  }
  const levels={musicUnderOriginal:amplitude(2,440),musicOnPhoto:amplitude(4.4,440),musicUnderVoice:amplitude(5.3,440),musicAfterVoice:amplitude(6.4,440),musicFadeIn:amplitude(.03,440),musicFadeOut:amplitude(7.8,440),original:amplitude(2,660),voice:amplitude(5.3,880)};
  assert(levels.musicOnPhoto>levels.musicUnderOriginal*3,JSON.stringify(levels));assert(levels.musicAfterVoice>levels.musicUnderVoice*3,JSON.stringify(levels));assert(levels.original>.05&&levels.voice>.05,JSON.stringify(levels));assert(levels.musicFadeOut<levels.musicAfterVoice*.5,JSON.stringify(levels));assert(levels.musicFadeIn<levels.musicUnderOriginal*.5,JSON.stringify(levels));
  const pixel=time=>[...execFileSync("ffmpeg",["-v","error","-ss",String(time),"-i",output,"-frames:v","1","-vf","format=rgb24,crop=1:1:100:1140","-f","rawvideo","pipe:1"])];
  const caption=pixel(.7),clear=pixel(2.3);assert(caption[0]>180&&caption[1]>180&&caption[2]<150,`${caption}`);assert(clear[2]>180&&clear[0]<50,`${clear}`);
  receipt.levels=levels;receipt.checks.push("Decoded H.264/AAC output proves timed caption pixels, original sound, music continuity, fades, original-audio ducking, narration ducking and recovery after speech");
  await page.getByLabel("Title overlay", {exact:true}).fill("Cancel test");
  await page.getByRole("button", {name:"Export MP4", exact:true}).click();
  await page.getByRole("button", {name:"Cancel export", exact:true}).click();
  await expect(page.getByRole("link", {name:/Download MP4/})).toHaveCount(0);
  await expect(page.getByRole("button", {name:"Export MP4", exact:true})).toBeEnabled();
  receipt.checks.push("Canceling a real encode does not expose a partial downloadable output and releases the export state");
  await page.getByLabel("Saved narration", {exact:true}).selectOption("");
  await page.getByRole("button", {name:/Select clip 1:/}).click();
  await page.getByLabel("Trim end (sec)", {exact:true}).fill("3.8");
  await page.getByText("Match cuts to the beat", {exact:true}).click();
  const beforeBeats=(await snapshot()).draft;
  await page.getByRole("button", {name:"Review beat cuts", exact:true}).click();
  await expect(page.getByRole("region", {name:"Beat cut proposal",exact:true})).toBeVisible();
  assert.deepEqual((await snapshot()).draft,beforeBeats);
  await page.getByRole("button", {name:"Apply reviewed beat cuts",exact:true}).click();
  await expect.poll(async()=>(await snapshot()).draft.clips[0].end).toBe(3.5);
  await page.getByRole("button",{name:/^Undo/}).click();
  await expect.poll(async()=>(await snapshot()).draft.clips[0].end).toBe(3.8);
  receipt.checks.push("Beat alignment displays a concrete proposal without mutating the edit, applies selected video trim only after review, and undoes in one step");
  await page.getByRole("button", {name:"Chat", exact:true}).click();
  await page.getByRole("textbox", {name:"Describe your video or edit", exact:true}).fill("Set music volume to 20 percent");
  await page.getByRole("textbox", {name:"Describe your video or edit", exact:true}).press("Enter");
  await expect.poll(async()=>(await snapshot()).draft.music.volume).toBe(.2);
  receipt.checks.push("A typed music-volume command changes the actual shared draft and mix controls without a provider call");
  await page.evaluate(()=>window.finishingFixture.cutaway());
  await expect.poll(async()=>(await snapshot()).draft.overlays?.length??0).toBe(1);
  await page.getByLabel("Scrub video timeline", {exact:true}).fill("0.7");
  await expect.poll(()=>page.locator("canvas").evaluate(canvas=>[...canvas.getContext("2d").getImageData(100,1140,1,1).data].slice(0,3))).toEqual([231,244,108]);
  await expect.poll(()=>page.locator("canvas").evaluate(canvas=>[...canvas.getContext("2d").getImageData(100,600,1,1).data].slice(0,3))).toEqual([255,0,0]);
  receipt.checks.push("Original speech captions remain visible over an actual photo cutaway while the base video supplies the speaking timeline");
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:join(artifacts,"finishing-mobile.png"),fullPage:true});
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole("button", {name:"Transcribe selected clip", exact:true}).click();
  await expect.poll(async()=>(await snapshot()).requests.length).toBe(4);
  await page.getByRole("button", {name:"Cancel sound task", exact:true}).click();
  await expect(page.getByRole("button", {name:"Transcribe selected clip", exact:true})).toBeEnabled();
  await page.evaluate(()=>window.finishingFixture.resolve(3));
  await expect(page.getByRole("region", {name:"Review speech captions", exact:true})).toHaveCount(0);
  receipt.checks.push("Cancel releases the sound controls immediately even when the test provider ignores abort, and its late response is discarded");
  await page.getByRole("button", {name:"Transcribe selected clip", exact:true}).click();
  await expect.poll(async()=>(await snapshot()).requests.length).toBe(5);
  await page.evaluate(()=>window.finishingFixture.account());
  await expect.poll(async()=>(await snapshot()).draft?.clips.length).toBe(0);
  await page.evaluate(()=>window.finishingFixture.resolve(4));
  await expect(page.getByRole("region", {name:"Review speech captions", exact:true})).toHaveCount(0);
  assert.equal((await snapshot()).draft.speech,undefined);assert.equal((await snapshot()).draft.music,undefined);
  assert.equal((await snapshot()).requests[4].aborted,true);
  receipt.checks.push("Account remount aborts outstanding speech work and rejects a late transcript without carrying music or captions into the new account");
  const largeOriginal=join(artifacts,"original-4k.mov");
  execFileSync("ffmpeg",["-v","error","-f","lavfi","-i","color=c=blue:s=3840x2160:r=30:d=2.2","-f","lavfi","-i","sine=frequency=660:duration=2.2:sample_rate=48000","-c:v","libx264","-preset","ultrafast","-pix_fmt","yuv420p","-c:a","aac","-shortest",largeOriginal]);
  // A valid MP4/MOV free atom makes a genuine large file without an expensive
  // long encode. Its entire padding must still participate in the fingerprint.
  const originalHandle=await open(largeOriginal,"a"), paddingBytes=130*1024*1024, atom=Buffer.alloc(8);atom.writeUInt32BE(paddingBytes+8,0);atom.write("free",4);await originalHandle.write(atom);
  const padding=Buffer.alloc(1024*1024);for(let i=0;i<130;i++)await originalHandle.write(padding);await originalHandle.close();
  const originalHash=createHash("sha256");for await(const part of createReadStream(largeOriginal))originalHash.update(part);const originalDigest=originalHash.digest("hex");
  await page.evaluate(()=>{const native=Blob.prototype.arrayBuffer;window.proxyReads=[];Blob.prototype.arrayBuffer=function(){window.proxyReads.push(this.size);if(this.size>1024*1024)throw new Error("Unbounded large-original read");return native.call(this);};});
  await page.getByLabel("Add photos or videos",{exact:true}).setInputFiles(largeOriginal);
  await expect(page.locator(".rp-editor-notice")).toContainText("Create an editing copy");
  assert.equal((await snapshot()).draft.clips.length,0);
  await page.getByText("Large video? Create an editing copy",{exact:true}).click();
  await page.getByLabel("Original for editing copy",{exact:true}).setInputFiles(largeOriginal);
  await page.getByRole("button",{name:"Create editing copy",exact:true}).click();
  await expect(page.getByRole("region",{name:"Completed editing copy",exact:true})).toBeVisible({timeout:30000});
  assert.equal((await snapshot()).draft.clips.length,0,"Preparing a proxy must not silently import it");
  let proxyDownload=page.waitForEvent("download");await page.getByRole("button",{name:"Download provenance",exact:true}).click();
  const manifestPath=join(artifacts,"proxy-provenance.json");await(await proxyDownload).saveAs(manifestPath);const manifest=JSON.parse(await readFile(manifestPath,"utf8"));
  assert.equal(manifest.original.sha256,originalDigest);assert.equal(manifest.original.width,3840);assert.equal(manifest.original.height,2160);assert.equal(manifest.originalStorage,"user-device-only");
  proxyDownload=page.waitForEvent("download");await page.getByRole("button",{name:"Download editing copy",exact:true}).click();const proxyPath=join(artifacts,"editing-copy.mp4");await(await proxyDownload).saveAs(proxyPath);
  const proxyBytes=await readFile(proxyPath);assert.equal(createHash("sha256").update(proxyBytes).digest("hex"),manifest.copy.sha256);
  const proxyProbe=JSON.parse(execFileSync("ffprobe",["-v","error","-show_entries","stream=codec_name,codec_type,width,height:format=duration","-of","json",proxyPath],{encoding:"utf8"}));
  assert(proxyProbe.streams.some(stream=>stream.codec_name==="h264"&&stream.width===1280&&stream.height===720));assert(proxyProbe.streams.some(stream=>stream.codec_name==="aac"));assert(Math.abs(Number(proxyProbe.format.duration)-2.2)<.5);
  const proxyAudio=execFileSync("ffmpeg",["-v","error","-ss","0.5","-i",proxyPath,"-t","0.2","-vn","-ac","1","-ar","48000","-f","f32le","pipe:1"]),samples=new Float32Array(proxyAudio.buffer,proxyAudio.byteOffset,proxyAudio.byteLength/4);assert(Math.sqrt(samples.reduce((sum,value)=>sum+value*value,0)/samples.length)>.03);
  await page.getByRole("button",{name:"Use editing copy",exact:true}).click();await expect.poll(async()=>(await snapshot()).draft.clips.length).toBe(1);assert.match((await snapshot()).draft.clips[0].source.name,/editing-copy-720p/);assert.equal((await snapshot()).draft.clips[0].source.sha256,manifest.copy.sha256);
  assert((await page.evaluate(()=>Math.max(...window.proxyReads)))<=1024*1024);
  receipt.checks.push("A genuine130MiB4Koriginal is fingerprinted in≤1MiBslices, creates a real1280×720H.264/AACcopy with original sound, exports both exact hashes in provenance, and enters the draft only after explicit Use editing copy");
  const proxyDraft=structuredClone((await snapshot()).draft);
  await page.getByRole("button",{name:"Create editing copy",exact:true}).click();await page.getByRole("button",{name:"Cancel editing copy",exact:true}).click();
  await expect(page.getByRole("region",{name:"Completed editing copy",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"Create editing copy",exact:true})).toBeEnabled();assert.deepEqual((await snapshot()).draft,proxyDraft);
  receipt.checks.push("Canceling large-file preparation leaves the original and current draft unchanged and exposes no partial copy");
  assert.deepEqual(receipt.errors,[]);assert.deepEqual(receipt.externalRequests,[]);receipt.status="pass";
} catch(error){receipt.status="fail";receipt.failure=String(error.stack??error);throw error;}
finally{if(browser)await browser.close();if(server)await new Promise(done=>server.close(done));await writeFile(join(artifacts,"receipt.json"),JSON.stringify(receipt,null,2));console.log(JSON.stringify({status:receipt.status,artifacts,checks:receipt.checks}));}
