import { useState } from "react";
import { createRoot } from "react-dom/client";
import ListingWorkflow from "../src/features/listings/ListingWorkflow";
import BusinessWorkspace from "../src/features/business/BusinessWorkspace";
import RealEstateRolePicker from "../src/features/business/RealEstateRolePicker";
import type { Workspace, Listing } from "../src/data/contracts";
import type { StudioServices } from "../src/data/services";
import type { ClientContact } from "../src/features/listings/client-contact";
import type { ClientDelivery } from "../src/features/business/model";
import "../src/styles.css";
const org="10000000-0000-4000-8000-000000000001",user="20000000-0000-4000-8000-000000000002",a="30000000-0000-4000-8000-000000000003",b="30000000-0000-4000-8000-000000000004",video="40000000-0000-4000-8000-000000000004",leadId="50000000-0000-4000-8000-000000000005";
const workspace:Workspace={user:{id:user,email:"photographer@example.invalid",name:"Photographer",avatarUrl:null,realEstateRole:null},org:{id:org,name:"Photo studio",handle:"photo-studio",spaceType:"real_estate"},memberships:[{orgId:org,orgName:"Photo studio",role:"owner",spaceType:"real_estate"}],plan:"team",planRaw:"team",planDegraded:false,planExpiresAt:null,trialEndsAt:null,usage:{listings:2,leads:1,leadsNew:1,renders:0}};
const listings:Listing[]=[a,b].map((id,i)=>({id,orgId:org,spaceType:"real_estate",address:i?"20 Maple Avenue":"10 Oak Street",tagline:"",details:{},status:"ready",createdAt:"2026-10-01T12:00:00Z",mainPhotoKey:null,beds:3,baths:2,sqft:2000,priceCents:40000000}));
const contacts=new Map<string,ClientContact>(),uploads=new Map<string,Record<string,unknown>>(),calls:{path:string;method:string;body:unknown}[]=[],intentions=new Map<string,unknown>();
let failSave=false,loseSendReply=true;
let delivery:ClientDelivery={state:"email_sent",recipient_email:"private-a@example.invalid",client_name:"Agent A",last_attempt_at:"2026-10-01T12:00:00Z",sent_at:"2026-10-01T12:00:01Z",can_resend:true,reason:null};
const services={
 getSnapshot:()=>({status:"signed-in",identityVersion:1,identity:{userId:user,isAnonymous:false}}),
 listMedia:async (_org:string,id:string)=>({orgId:org,listingId:id,photos:[],videos:[],nextOffset:null,unavailableCount:0}),
 upload:async()=>({etag:"synthetic-receipt"}),
 api:async(path:string,options:{method?:string;orgId:string;body?:Record<string,unknown>})=>{
  if(options.orgId!==org)throw new Error("Foreign fixture workspace");const method=options.method??"GET",body=options.body;calls.push({path,method,body:structuredClone(body)});if(calls.length>150)throw new Error("Request loop");
  if(path.endsWith("/me/profile")){workspace.user.realEstateRole=body!.real_estate_role as "agent"|"photographer_videographer";return{ok:true,user:{id:user,real_estate_role:workspace.user.realEstateRole}};}
  if(path.endsWith("/client-contact")){const id=path.split("/").at(-2)!;if(method==="GET")return{contact:structuredClone(contacts.get(id)??null)};if(method!=="PUT")throw new Error("Unsupported contact mutation");if(failSave){failSave=false;throw new Error("Contact save failed. Your changes are kept.");}if(body!.expected_revision!==(contacts.get(id)?.revision??0))throw new Error("This contact changed on another device. Refresh the saved revision.");const card={...(body!.public_card as Record<string,string>),...(body!.photo_asset_id?{avatar_url:`https://media.invalid/contact-${body!.photo_asset_id}.png`}:{})};const value={...body,public_card:card,listing_id:id,revision:Number(body!.expected_revision)+1,updated_at:new Date().toISOString()} as ClientContact;contacts.set(id,value);return{contact:structuredClone(value)};}
  if(path.includes("studio/listing-state?")){const id=new URL(path,"https://fixture.invalid").searchParams.get("listing_id")!;return{org_id:org,listing_id:id,assets:[{id:video,listing_id:id,storage_key:`renders/${org}/${id}/edited-tour.mp4`,kind:"video",bucket:"renders",uploaded:true,duration_s:30,created_at:listings[0].createdAt}],photos:[],jobs:[],renders:[],chapters:[],next_offset:null};}
  if(path.includes("leads?"))return{leads:[{id:leadId,listing_id:a,name:"Alex Buyer",email:"buyer@example.invalid",phone:"+15551112222",message:"Can I see this house?",listing_address:"10 Oak Street",source:"tour",status:"new",synced_crm:false,created_at:listings[0].createdAt,client_delivery:structuredClone(delivery)}]};
  if(path.endsWith("send-to-client")){if(body!.expected_recipient_email!==(delivery.current_recipient_email??delivery.recipient_email))throw new Error("Recipient changed");let result=intentions.get(String(body!.request_id));if(!result){delivery={...delivery,recipient_email:delivery.current_recipient_email??delivery.recipient_email,client_name:delivery.current_client_name??delivery.client_name,state:"queued",can_resend:false};result={ok:true,delivery:structuredClone(delivery)};intentions.set(String(body!.request_id),result);}if(loseSendReply){loseSendReply=false;throw new Error("Connection lost after request was saved");}return structuredClone(result);}
  if(path.endsWith("/renders/publish-app"))return{ok:true};
  if(path.endsWith("/uploads")){const id=crypto.randomUUID(),row={id,listing_id:body!.listing_id,storage_key:`renders/${org}/${body!.listing_id}/contact-${id}.png`,kind:"photo",bucket:"renders",uploaded:false};uploads.set(id,row);return{asset_id:id,storage_key:row.storage_key,mode:"single",uploaded:false,put_url:"https://uploads.rendprop.com/v2/fixture"};}
  if(path.endsWith("/complete")){const row=uploads.get(path.split("/").at(-2)!)!;row.uploaded=true;return structuredClone(row);}
  throw new Error(`Unexpected fixture ${method} ${path}`);
 }
} as unknown as StudioServices;
function Fixture(){const[view,setView]=useState("role"),[selected,setSelected]=useState(a),[mount,setMount]=useState(0),[account,setAccount]=useState(workspace);Object.assign(window,{photographerFixture:{calls:()=>structuredClone(calls),contacts:()=>structuredClone([...contacts]),failSave:()=>{failSave=true;},phoneChange:(id:string)=>{const value=contacts.get(id)!;contacts.set(id,{...value,public_card:{...value.public_card,name:"Client changed on phone"},revision:value.revision+1});},reopen:()=>setMount(value=>value+1),intentions:()=>intentions.size,changeRecipient:()=>{delivery={...delivery,state:"email_sent",can_resend:true,current_recipient_email:"new-client@example.invalid",current_client_name:"New Client"};},olderInquiry:()=>{delivery={state:"skipped",recipient_email:null,client_name:null,current_recipient_email:"new-client@example.invalid",current_client_name:"New Client",last_attempt_at:null,sent_at:null,can_resend:true,reason:"This inquiry was recorded before client forwarding was enabled."};}}});return<main style={{padding:24}}><nav><button onClick={()=>setView("role")}>Work preference</button><button onClick={()=>setView("properties")}>Client properties</button><button onClick={()=>setView("leads")}>Client lead inbox</button></nav>{view==="role"?<RealEstateRolePicker workspace={account} services={services} onboarding onSaved={()=>setAccount({...workspace,user:{...workspace.user}})}/>:view==="leads"?<BusinessWorkspace workspace={account} services={services} listings={listings} onChanged={()=>{}}/>:<ListingWorkflow key={mount} workspace={account} services={services} listings={listings} listingId={selected} onSelectListing={setSelected} onChanged={()=>{}}/>}</main>;}
createRoot(document.getElementById("root")!).render(<Fixture/>);
