import test from "node:test";
import assert from "node:assert/strict";
import { dollars, AUTO_CHECK_LIMIT, decodeJobs, nextAutoCheck, readSubmission, resolvesSubmission, submissionKey } from "../src/features/presenter/jobs";
const org="11111111-1111-4111-8111-111111111111",listing="22222222-2222-4222-8222-222222222222",draft="33333333-3333-4333-8333-333333333333",quote="44444444-4444-4444-8444-444444444444",job="55555555-5555-4555-8555-555555555555";
function envelope(){return {org_id:org,listing_id:listing,runtime:{available:false,reason:"Not configured"},quotes:[{id:quote,draft_id:draft,draft_revision:3,profile_revision:2,quote_cents:47,max_cost_cents:100,estimate_usd:"0.470000",consumed:true,expires_at:new Date(Date.now()+300000).toISOString()}],jobs:[{id:job,quote_id:quote,draft_id:draft,draft_revision:3,profile_revision:2,status:"queued",revision:1,quote_cents:47,max_cost_cents:100,held_cents:100,estimate_usd:"0.470000",charged_cents:null,actual_usd:null,output:null as any,imported_asset_id:null,permissions:{can_cancel:true,can_review:false,can_import:false}}]};}
function signed(){const now=new Date(Math.floor(Date.now()/1000)*1000),expires=new Date(now.getTime()+300000).toISOString(),q=new URLSearchParams({"X-Amz-Algorithm":"AWS4-HMAC-SHA256","X-Amz-Credential":"fixture/auto/s3/aws4_request","X-Amz-Date":now.toISOString().replace(/[-:]/g,"").replace(".000",""),"X-Amz-Expires":"300","X-Amz-SignedHeaders":"host","X-Amz-Signature":"a".repeat(64)});return{preview_url:`https://${"b".repeat(32)}.r2.cloudflarestorage.com/private/presenter-private/${org}/${job}/output.mp4?${q}`,preview_expires_at:expires};}
test("Presenter jobs preserve distinct estimate, authorized ceiling, hold and unknown billing",()=>{const state=decodeJobs(envelope(),org,listing);assert.equal(state.quotes[0].quote_cents,47);assert.equal(state.quotes[0].max_cost_cents,100);assert.equal(state.jobs[0].held_cents,100);assert.equal(state.jobs[0].actual_usd,null);assert.equal(state.runtime.available,false);});
test("Presenter invalidation tombstone may clear revision snapshots without breaking job history",()=>{const e=envelope();Object.assign(e.jobs[0],{status:"invalidated",draft_revision:null,profile_revision:null});assert.equal(decodeJobs(e,org,listing).jobs[0].draft_revision,null);e.jobs[0].status="queued";assert.throws(()=>decodeJobs(e,org,listing));});
test("Presenter job decoder rejects malformed scope, state, costs and permission flags",()=>{for(const change of [(e:any)=>e.org_id=listing,(e:any)=>e.listing_id=org,(e:any)=>e.jobs[0].status="constructor",(e:any)=>e.jobs[0].quote_cents=NaN,(e:any)=>e.quotes[0].max_cost_cents=-1,(e:any)=>e.jobs[0].estimate_usd="NaN",(e:any)=>e.jobs[0].permissions.can_review="yes",(e:any)=>e.jobs.push(e.jobs[0]),(e:any)=>e.quotes[0].expires_at="not-a-date"]){const e=envelope();change(e);assert.throws(()=>decodeJobs(e,org,listing));}});
test("Private output URL is bound to exact org/job and existing strict R2 signer policy",()=>{const e=envelope();e.jobs[0].output={sha256:"c".repeat(64),bytes:1234,duration_s:6,...signed()};assert(decodeJobs(e,org,listing).jobs[0].output?.preview_url);for(const alter of [(url:string)=>url.replace(job,draft),(url:string)=>url.replace(org,listing),(url:string)=>url.replace(".r2.cloudflarestorage.com",".attacker.invalid"),(url:string)=>url.replace("output.mp4","different.mp4"),(url:string)=>url.replace("X-Amz-Signature=","token=secret&X-Amz-Signature=")]){const copy=structuredClone(e);copy.jobs[0].output.preview_url=alter(copy.jobs[0].output.preview_url);assert.throws(()=>decodeJobs(copy,org,listing));}e.jobs[0].output.duration_s=NaN;assert.throws(()=>decodeJobs(e,org,listing));});
test("Durable submission receipt contains scoped IDs and the exact authorized ceiling",()=>{const marker={quote_id:quote,idempotency_key:job,max_cost_cents:100};assert.deepEqual(readSubmission(JSON.stringify(marker)),marker);assert.equal(readSubmission(null),null);assert.throws(()=>readSubmission(JSON.stringify({...marker,max_cost_cents:undefined})));assert.notEqual(submissionKey(org,draft,listing),submissionKey(org,job,listing));});

test("An unresolved request is cleared only by its exact durable job or server closure",()=>{const marker={quote_id:quote,idempotency_key:job,max_cost_cents:100},state=decodeJobs(envelope(),org,listing);assert(resolvesSubmission(state,marker));state.jobs=[];assert(!resolvesSubmission(state,marker));state.closed_submission={quote_id:quote,idempotency_key:draft};assert(!resolvesSubmission(state,marker));state.closed_submission={quote_id:quote,idempotency_key:job};assert(resolvesSubmission(state,marker));const decoded=decodeJobs({...envelope(),jobs:[],closed_submission:state.closed_submission},org,listing);assert(resolvesSubmission(decoded,marker));});

test("Automatic progress is bounded and never chooses uncertain, review or terminal jobs",()=>{const state=decodeJobs(envelope(),org,listing),j=state.jobs[0];assert.equal(nextAutoCheck([j],{},true)?.id,j.id);assert.equal(nextAutoCheck([j],{},false),undefined);assert.equal(nextAutoCheck([j],{[j.id]:AUTO_CHECK_LIMIT},true),undefined);for(const status of ["uncertain","dispatching","review","accepted","rejected","imported","invalidated","failed","cancelled"] as const)assert.equal(nextAutoCheck([{...j,status}],{},true),undefined);for(const status of ["reserved","queued","processing","cancel_requested"] as const)assert.equal(nextAutoCheck([{...j,status}],{},true)?.id,j.id);});

test("USD labels use consistent cents for provider decimals", () => { assert.equal(dollars("0.470000"), "$0.47 USD"); assert.equal(dollars("1"), "$1.00 USD"); assert.equal(dollars("0.410000"), "$0.41 USD"); });
