import test from "node:test";
import assert from "node:assert/strict";
import { approvedDraft, approvedProfile, confirmsAction, decodePresenter, decodePreviews, type Profile, type Draft } from "../src/features/presenter/model";
const org="11111111-1111-4111-8111-111111111111",listing="22222222-2222-4222-8222-222222222222",user="33333333-3333-4333-8333-333333333333",photo="44444444-4444-4444-8444-444444444444",video="55555555-5555-4555-8555-555555555555";
const profile:Profile={id:"66666666-6666-4666-8666-666666666666",subject_user_id:user,source_listing_id:listing,display_name:"Morgan",reference_asset_ids:[photo],status:"approved",revision:2,approved_revision:2,permissions:{can_save:true,can_approve:true,can_revoke:true}};
const draft:Draft={id:"77777777-7777-4777-8777-777777777777",listing_id:listing,author_user_id:user,subject_user_id:user,profile_id:profile.id,profile_revision:2,title:"Welcome",script:"Welcome to this home.",source_asset_id:video,format:"listing_intro",resolution:"720p",revision:2,status:"approved",approved_revision:2,approved_profile_revision:2,permissions:{can_save:true,can_approve:true,can_request_generation:true,can_generate:false}};
function envelope(){return {org_id:org,listing_id:listing,profiles:[structuredClone(profile)],drafts:[structuredClone(draft)],reference_candidates:[{asset_id:photo,listing_id:listing}],source_candidates:[{asset_id:video,listing_id:listing,duration_s:10}],permissions:{can_save_profile:true,can_create_draft:true},runtime:{available:false,code:"enterprise_contract_required",reason:"Agreement required"}};}
test("Presenter accepts scoped shared state and exact approval only",()=>{const state=decodePresenter(envelope(),org,listing);assert(approvedProfile(state.profiles[0]));assert(approvedDraft(state.drafts[0],state.profiles[0]));assert(!approvedDraft({...draft,profile_revision:1},profile));assert(!approvedDraft(draft,{...profile,revision:3,approved_revision:3}));assert(!approvedProfile({...profile,status:"revoked"}));assert(!approvedProfile({...profile,invalid_reason:"References deleted"}));});
test("Presenter rejects cross-property envelopes, drafts, candidates and malformed limits",()=>{for(const change of [
 (e:any)=>e.org_id=listing,(e:any)=>e.drafts[0].listing_id=user,(e:any)=>e.source_candidates[0].listing_id=user,
 (e:any)=>e.profiles[0].reference_asset_ids=Array(9).fill(photo),(e:any)=>e.profiles[0].reference_asset_ids=[photo,photo],
 (e:any)=>e.source_candidates[0].duration_s=31,(e:any)=>e.drafts[0].format="toString",(e:any)=>e.drafts[0].permissions.can_approve="yes",
 (e:any)=>e.profiles[0].revision=0,(e:any)=>e.drafts[0].script="",
 ]){const e=envelope();change(e);assert.throws(()=>decodePresenter(e,org,listing));}});
test("Lost-response confirmation requires exact immediate next revision and payload",()=>{const action={action:"save_draft",draft_id:draft.id,expected_revision:2,expected_profile_revision:2,profile_id:profile.id,title:"Updated",script:draft.script,source_asset_id:video,format:draft.format,resolution:draft.resolution};const state=decodePresenter(envelope(),org,listing);state.drafts[0]={...draft,status:"draft",revision:3,title:"Updated",approved_revision:null,approved_profile_revision:null};assert(confirmsAction(state,action,user));assert(!confirmsAction(state,{...action,title:"Different"},user));assert(!confirmsAction(state,{...action,expected_revision:1},user));assert(!confirmsAction(state,{...action,expected_profile_revision:1},user));assert(!confirmsAction(state,{action:"approve_profile",profile_id:profile.id,expected_revision:1},listing));});
test("Cross-property profile previews validate original property and exact profile revision",()=>{const other="88888888-8888-4888-8888-888888888888",now=new Date(Math.floor(Date.now()/1000)*1000),expires_at=new Date(now.getTime()+300000).toISOString(),query=new URLSearchParams({"X-Amz-Algorithm":"AWS4-HMAC-SHA256","X-Amz-Credential":"fixture/auto/s3/aws4_request","X-Amz-Date":now.toISOString().replace(/[-:]/g,"").replace(".000",""),"X-Amz-Expires":"300","X-Amz-SignedHeaders":"host","X-Amz-Signature":"f".repeat(64)});const response={org_id:org,listing_id:other,profile_id:profile.id,profile_revision:2,references:[{asset_id:photo,expires_at,url:`https://${"a".repeat(32)}.r2.cloudflarestorage.com/bucket/uploads/${org}/${listing}/face.jpg?${query}`}]};assert.equal(decodePreviews(response,org,other,{profile})[0].asset_id,photo);assert.throws(()=>decodePreviews({...response,profile_revision:1},org,other,{profile}));assert.throws(()=>decodePreviews({...response,references:[{...response.references[0],asset_id:video}]},org,other,{profile}));assert.throws(()=>decodePreviews({...response,references:[{...response.references[0],url:"https://attacker.invalid/photo.jpg"}]},org,other,{profile}));});

test("Presenter accepts the server's 200 candidate/profile cap and surfaces truncation",()=>{const e=envelope();e.reference_candidates=Array.from({length:200},(_,i)=>({asset_id:`44444444-4444-4444-8444-${String(i).padStart(12,"0")}`,listing_id:listing}));e.profiles=Array.from({length:200},(_,i)=>({...profile,id:`66666666-6666-4666-8666-${String(i).padStart(12,"0")}`}));assert.equal(decodePresenter(e,org,listing).profiles.length,200);assert.equal(decodePresenter({...e,truncated:{profiles:true,drafts:false,reference_candidates:false,source_candidates:false}},org,listing).truncated,true);e.reference_candidates.push({asset_id:photo,listing_id:listing});assert.throws(()=>decodePresenter(e,org,listing));});
