import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, extname } from "node:path";
import { createServer } from "node:http";
import { execFileSync } from "node:child_process";
import { build } from "vite";
import { chromium, expect } from "@playwright/test";
const root=resolve(import.meta.dirname,".."),artifacts=await mkdtemp(join(tmpdir(),"rendprop-presenter-")),dist=join(artifacts,"dist");
const receipt={proof:"Real Presenter UI, synthetic local media and isolated revisioned API fixtures. No live writes or provider calls.",checks:[],errors:[],externalRequests:[]};
const first="22222222-2222-4222-8222-222222222222",second="22222222-2222-4222-8222-222222222223";
let browser,server,page,blockOutput=false;
try {
 const clip=join(artifacts,"performance.mp4");execFileSync("ffmpeg",["-v","error","-f","lavfi","-i","color=c=gray:s=128x128:d=6","-c:v","libx264","-pix_fmt","yuv420p","-movflags","+faststart",clip]);
 const mp4=await readFile(clip),png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=","base64");
 await build({configFile:false,root,publicDir:false,logLevel:"error",build:{outDir:dist,rollupOptions:{input:join(root,"tests/presenter-fixture.html")}}});
 server=createServer(async(req,res)=>{const path=resolve(dist,`.${new URL(req.url,"http://localhost").pathname}`);if(!path.startsWith(`${dist}/`))return res.writeHead(400).end();try{res.setHeader("Content-Type",({".html":"text/html",".js":"application/javascript",".css":"text/css"})[extname(path)]??"application/octet-stream");res.end(await readFile(path));}catch{res.writeHead(404).end();}});
 await new Promise(done=>server.listen(0,"127.0.0.1",done));const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true,executablePath:process.env.STUDIO_BROWSER_EXECUTABLE});const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:"block"});
 await context.route("**/*",route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();if(url.hostname===`${"a".repeat(32)}.r2.cloudflarestorage.com`)return route.fulfill({status:200,contentType:url.pathname.endsWith(".mp4")?"video/mp4":"image/png",body:url.pathname.includes("presenter-private")&&blockOutput?Buffer.from("invalid video"):url.pathname.endsWith(".mp4")?mp4:png});receipt.externalRequests.push(url.href);return route.abort();});
 page=await context.newPage();page.on("pageerror",e=>receipt.errors.push(e.message));page.setDefaultTimeout(15000);
 await page.clock.install({time:new Date("2026-09-24T11:59:00Z")});
 await page.goto(`${origin}/tests/presenter-fixture.html`);
 const panel=page.getByRole("region",{name:"AI Presenter",exact:true});
 async function reload(){await page.clock.resume();await page.reload();await expect(panel.getByRole("button",{name:"Check job status",exact:true})).toBeVisible();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));}
 await expect(panel.getByRole("button",{name:"Create my likeness profile"})).toBeVisible();await page.clock.pauseAt(new Date("2026-09-24T12:00:00Z"));
 assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action).length,0);
 await panel.getByRole("button",{name:"Create my likeness profile"}).click();await panel.getByLabel("Your display name").fill("Morgan Agent");
 await panel.getByRole("checkbox",{name:"Use reference photo 1",exact:true}).check();await panel.getByRole("checkbox",{name:"Use reference photo 2",exact:true}).check();
 await panel.getByRole("button",{name:"Save my profile",exact:true}).click();await expect(panel.getByAltText("Agent reference 1",{exact:true})).toBeVisible();
 await expect(panel.getByRole("button",{name:"Approve my likeness profile",exact:true})).toBeDisabled();
 await panel.getByRole("checkbox",{name:/I am the person shown/}).check();await panel.getByRole("button",{name:"Approve my likeness profile",exact:true}).click();
 await expect(panel.getByText(/Likeness approved/)).toBeVisible();
 receipt.checks.push("Original reference selection saves a shared profile; only explicit self-consent approves the exact profile revision; opening the panel dispatches no mutation");
 await panel.getByLabel("Video title",{exact:true}).fill("Welcome to Oak Street");await panel.getByLabel("Script or talking points").fill("Welcome to this bright home. Come inside.");
 await panel.getByLabel("Presenter resolution").selectOption("480p");await panel.getByLabel("Source performance video",{exact:true}).selectOption("55555555-5555-4555-8555-555555555555");
 await expect(panel.getByLabel("Source performance preview")).toHaveJSProperty("duration",6);
 await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();
 await expect(panel.getByRole("button",{name:"Approve this Presenter draft",exact:true})).toBeDisabled();
 await panel.getByRole("checkbox",{name:/I approve this saved script/}).check();await panel.getByRole("button",{name:"Approve this Presenter draft",exact:true}).click();
 await expect(panel.getByText("The agent approved this exact saved draft and profile.",{exact:true})).toBeVisible();
 await expect(panel.getByRole("button",{name:/Generate AI Presenter/})).toBeDisabled();
 receipt.checks.push("A decoded original 6-second performance, guide text and 480p choice save together; source-performance permission and exact-version agent approval are explicit; generation stays unavailable");
 await panel.getByRole("button",{name:"Edit the original performance video",exact:true}).click();
 assert.deepEqual((await page.evaluate(()=>window.presenterFixture.snapshot())).handoffs[0],{listingId:first,assetId:"55555555-5555-4555-8555-555555555555",cutaways:[],script:"Welcome to this bright home. Come inside."});
 receipt.checks.push("Saved original performance hands off its actual source ID and guide to the existing editor without fabricated AI output");
 await panel.getByLabel("Script or talking points").fill("A later local script.");await page.evaluate(()=>window.presenterFixture.lose("save_draft"));
 const beforeLost=(await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action==="save_draft").length;
 await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();await expect(panel.getByText(/The save could not be confirmed/)).toBeVisible();
 await expect(panel.getByLabel("Script or talking points")).toBeDisabled();await panel.getByRole("button",{name:"Check saved status",exact:true}).click();
 await expect(panel.getByLabel("Script or talking points")).toBeEnabled();await expect(panel.getByLabel("Script or talking points")).toHaveValue("A later local script.");
 assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action==="save_draft").length,beforeLost+1);
 receipt.checks.push("A committed save with lost POST+GET responses is reconciled at exact next revision without a duplicate mutation or discarded text");
 await page.evaluate(()=>window.presenterFixture.editRemote());await panel.getByLabel("Script or talking points").fill("My carefully reviewed changes");await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();
 const conflict=panel.getByRole("region",{name:"Presenter version conflict"});await expect(conflict).toContainText("A newer script from the office");await expect(panel.getByLabel("Script or talking points")).toHaveValue("My carefully reviewed changes");
 await conflict.getByRole("button",{name:"Keep my changes for review"}).click();await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();await expect(panel.getByText("Unsaved changes",{exact:true})).toHaveCount(0);
 receipt.checks.push("A competing desktop revision preserves local text, exposes the saved script, and requires an explicit review choice before replacement");
 await panel.getByLabel("Script or talking points").fill("Unsaved navigation protection");page.once("dialog",dialog=>dialog.dismiss());await page.getByRole("combobox",{name:"Property",exact:true}).selectOption(second);await expect(page.getByRole("combobox",{name:"Property",exact:true})).toHaveValue(first);
 await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();await expect(panel.getByText("Unsaved changes",{exact:true})).toHaveCount(0);
 await page.getByRole("combobox",{name:"Property",exact:true}).selectOption(second);await page.getByRole("navigation",{name:"Creative tools"}).getByRole("button",{name:"AI Presenter",exact:true}).click();
 await expect(panel.getByRole("combobox",{name:"Agent likeness profile"})).toContainText("Morgan Agent");await expect(panel.getByAltText("Agent reference 1",{exact:true})).toBeVisible();await expect(panel.getByLabel("Video title",{exact:true})).toHaveValue("");
 receipt.checks.push("Dirty property navigation is guarded; a second property reuses the workspace-approved agent and original-property references without exposing the first property's draft");
 await page.getByRole("combobox",{name:"Property",exact:true}).selectOption(first);await page.getByRole("navigation",{name:"Creative tools"}).getByRole("button",{name:"AI Presenter",exact:true}).click();
 await expect(panel.getByLabel("Script or talking points")).toHaveValue("Unsaved navigation protection");
 await panel.getByLabel("Script or talking points").fill("My pending words survive a profile update");
 await panel.getByRole("button",{name:"Update my likeness profile"}).click();await panel.getByLabel("Your display name").fill("Morgan Updated");await panel.getByRole("button",{name:"Save my profile",exact:true}).click();
 await expect(panel.getByText(/likeness profile changed/)).toBeVisible();await panel.getByRole("checkbox",{name:/I am the person shown/}).check();await panel.getByRole("button",{name:"Approve my likeness profile",exact:true}).click();
 await expect(panel.getByRole("button",{name:"Save Presenter draft",exact:true})).toBeEnabled();await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();
 await expect(panel.getByLabel("Script or talking points")).toHaveValue("My pending words survive a profile update");await expect(panel.getByText("Unsaved changes",{exact:true})).toHaveCount(0);await expect(panel.getByRole("region",{name:"Presenter version conflict"})).toHaveCount(0);
 await panel.getByRole("checkbox",{name:/I approve this saved script/}).check();await panel.getByRole("button",{name:"Approve this Presenter draft",exact:true}).click();await expect(panel.getByText("The agent approved this exact saved draft and profile.",{exact:true})).toBeVisible();
 receipt.checks.push("Profile updates preserve pending script, advance the returned draft base revision without a conflict, and require fresh exact-version approval");
 await page.evaluate(()=>window.presenterFixture.actor("editor"));await expect(panel.getByLabel("Video title",{exact:true})).toHaveValue("Welcome to Oak Street");
 await expect(panel.getByRole("button",{name:"Approve this Presenter draft",exact:true})).toHaveCount(0);await expect(panel.getByRole("button",{name:"Revoke my likeness permission",exact:true})).toHaveCount(0);
 await panel.getByLabel("Script or talking points").fill("Prepared by the agency for agent review");await panel.getByRole("button",{name:"Save Presenter draft",exact:true}).click();await expect(panel.getByText("Unsaved changes",{exact:true})).toHaveCount(0);
 await page.evaluate(()=>window.presenterFixture.actor("agent"));await expect(panel.getByLabel("Script or talking points")).toHaveValue("Prepared by the agency for agent review");
 receipt.checks.push("Agency editor can prepare shared content but cannot impersonate the agent's approval or revoke another person's likeness; subject sees the shared update after account switch");
 await panel.getByRole("checkbox",{name:/I approve this saved script/}).check();await panel.getByRole("button",{name:"Approve this Presenter draft",exact:true}).click();
 const jobPanel=panel.getByRole("region",{name:"Presenter generation jobs"});
 await expect(jobPanel.getByRole("button",{name:/Generate AI Presenter/})).toBeDisabled();
 await page.evaluate(()=>window.presenterFixture.enableGeneration());await jobPanel.getByRole("button",{name:"Check job status",exact:true}).click();
 await jobPanel.getByRole("button",{name:"Get generation quote",exact:true}).click();await expect(jobPanel).toContainText("$0.47 USD");
 await expect(jobPanel.getByRole("button",{name:"Generate this approved draft",exact:true})).toBeDisabled();
 await jobPanel.getByRole("checkbox",{name:/I authorize up to \$1.00 USD/}).check();await page.evaluate(()=>window.presenterFixture.lose("generate"));
 await jobPanel.getByRole("button",{name:"Generate this approved draft",exact:true}).click();await expect(jobPanel).toContainText("A submission is awaiting confirmation");
 assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,1);
 await reload();await expect(jobPanel.getByRole("heading",{name:"Queued",exact:true})).toBeVisible();await expect(jobPanel.getByText(/A submission is awaiting confirmation/)).toHaveCount(0);
 assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,1);
 receipt.checks.push("Quoted USD estimate and exact cents consent are required; a lost generate reply plus failed reconciliation survives reload and recovers one durable job without another dispatch");
 const checkCount=async()=> (await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action==="check").length;
 await page.evaluate(()=>Object.defineProperty(document,"visibilityState",{configurable:true,value:"hidden"}));const hiddenChecks=await checkCount();await page.clock.fastForward(11000);assert.equal(await checkCount(),hiddenChecks);
 await page.evaluate(()=>{Object.defineProperty(document,"visibilityState",{configurable:true,value:"visible"});Object.defineProperty(navigator,"onLine",{configurable:true,value:false});});await page.clock.fastForward(11000);assert.equal(await checkCount(),hiddenChecks);
 await page.evaluate(()=>{Object.defineProperty(navigator,"onLine",{configurable:true,value:true});window.presenterFixture.actor("viewer");});await expect(panel.getByLabel("Video title",{exact:true})).toBeDisabled();await page.clock.fastForward(11000);assert.equal(await checkCount(),hiddenChecks);await expect(jobPanel.getByRole("button",{name:"Check progress",exact:true})).toHaveCount(0);
 await page.evaluate(()=>window.presenterFixture.actor("agent"));await expect(jobPanel.getByRole("heading",{name:"Queued",exact:true})).toBeVisible();blockOutput=true;await page.clock.fastForward(11000);await expect(jobPanel.getByRole("heading",{name:"Ready for your private review",exact:true})).toBeVisible();assert.equal(await checkCount(),hiddenChecks+1);assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,1);
 const reviewChecks=await checkCount();await page.clock.fastForward(11000);assert.equal(await checkCount(),reviewChecks);
 receipt.checks.push("Automatic progress pauses hidden/offline/read-only, checks one existing job when active, stops at review and never sends another paid generation");
 await expect(jobPanel.getByText(/Preview could not load/)).toBeVisible();await expect(jobPanel.getByRole("button",{name:"Accept generated video",exact:true})).toBeDisabled();
 blockOutput=false;await jobPanel.getByRole("button",{name:"Check job status",exact:true}).click();await expect(jobPanel.getByLabel("Private Presenter output")).toHaveJSProperty("duration",6);await expect(jobPanel.getByText(/Preview could not load/)).toHaveCount(0);
 receipt.checks.push("A broken private output cannot be approved; refreshing status reloads and decodes the actual video before allowing review consent");
 await expect(jobPanel.getByRole("button",{name:"Accept generated video",exact:true})).toBeDisabled();await jobPanel.screenshot({path:join(artifacts,"presenter-generated-review.png")});
 await page.evaluate(()=>window.presenterFixture.actor("editor"));await expect(panel.getByLabel("Video title",{exact:true})).toHaveValue("Welcome to Oak Street");await expect(jobPanel.getByLabel("Private Presenter output")).toHaveCount(0);await expect(jobPanel.getByRole("button",{name:"Accept generated video",exact:true})).toHaveCount(0);
 await page.evaluate(()=>window.presenterFixture.actor("agent"));await expect(jobPanel.getByLabel("Private Presenter output")).toHaveJSProperty("duration",6);
 await jobPanel.getByRole("checkbox",{name:/I reviewed this exact generated video/}).check();await jobPanel.getByRole("button",{name:"Accept generated video",exact:true}).click();
 await jobPanel.getByRole("button",{name:"Add accepted video to property",exact:true}).click();await jobPanel.getByRole("button",{name:"Open generated video in editor",exact:true}).click();
 const generatedHandoff=(await page.evaluate(()=>window.presenterFixture.snapshot())).handoffs.at(-1);assert.equal(generatedHandoff.assetId,"55555555-5555-4555-8555-555555555556");assert.deepEqual(generatedHandoff.cutaways,[]);
 receipt.checks.push("Private synthetic output is reviewable only by its represented subject; exact-output consent gates acceptance, followed by accepted asset import and the real editor handoff");
 async function anotherJob(){await jobPanel.getByRole("button",{name:"Get generation quote",exact:true}).click();await expect(jobPanel.getByRole("checkbox",{name:/I authorize up to/})).not.toBeChecked();await jobPanel.getByRole("checkbox",{name:/I authorize up to/}).check();await jobPanel.getByRole("button",{name:"Generate this approved draft",exact:true}).click();await expect(jobPanel.getByRole("heading",{name:"Queued",exact:true})).toBeVisible();}
 await anotherJob();page.once("dialog",d=>d.accept());await jobPanel.getByRole("button",{name:"Cancel generation",exact:true}).click();await expect(jobPanel.getByRole("heading",{name:"Cancelled",exact:true})).toBeVisible();
 await jobPanel.getByRole("button",{name:"Get generation quote",exact:true}).click();await jobPanel.getByRole("checkbox",{name:/I authorize up to/}).check();await page.evaluate(()=>window.presenterFixture.failBefore("generate"));await jobPanel.getByRole("button",{name:"Generate this approved draft",exact:true}).click();await expect(jobPanel).toContainText("A submission is awaiting confirmation");
 const originalAttempt=(await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action==="generate").at(-1).body;await reload();await expect(jobPanel.getByRole("button",{name:"Recover submission",exact:true})).toBeVisible();assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,2);
 await jobPanel.getByRole("button",{name:"Recover submission",exact:true}).click();await expect(jobPanel.getByRole("heading",{name:"Queued",exact:true})).toBeVisible();
 const recoveredAttempt=(await page.evaluate(()=>window.presenterFixture.snapshot())).calls.filter(c=>c.body?.action==="generate").at(-1).body;assert.deepEqual(recoveredAttempt,originalAttempt);assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,3);
 receipt.checks.push("An unsent request remains locked across reload; explicit recovery reuses the identical quote, idempotency UUID and authorized maximum, creating exactly one job");
 await jobPanel.getByRole("button",{name:"Check progress",exact:true}).click();page.once("dialog",d=>d.accept());await jobPanel.getByRole("button",{name:"Reject generated video",exact:true}).click();await expect(jobPanel.getByRole("heading",{name:"Rejected",exact:true})).toBeVisible();
 receipt.checks.push("Each new quote resets amount consent; cancellation and subject rejection persist as distinct terminal jobs without importing rejected output");
 await jobPanel.getByRole("button",{name:"Get generation quote",exact:true}).click();await jobPanel.getByRole("checkbox",{name:/I authorize up to/}).check();await page.evaluate(()=>window.presenterFixture.failBefore("generate"));await jobPanel.getByRole("button",{name:"Generate this approved draft",exact:true}).click();await expect(jobPanel).toContainText("A submission is awaiting confirmation");await page.evaluate(()=>window.presenterFixture.expireQuotes());
 await jobPanel.getByRole("button",{name:"Recover submission",exact:true}).click();await expect(jobPanel).toContainText("Get a fresh presenter quote");await jobPanel.getByRole("button",{name:"Close unsubmitted request",exact:true}).click();await expect(jobPanel.getByRole("button",{name:"Recover submission",exact:true})).toHaveCount(0);assert.equal((await page.evaluate(()=>window.presenterFixture.snapshot())).dispatches,3);
 receipt.checks.push("An expired unsent quote is closed by the server before clearing its receipt; a fresh quote becomes possible without an extra dispatch");
 await anotherJob();await jobPanel.getByRole("button",{name:"Check progress",exact:true}).click();await expect(jobPanel.getByRole("heading",{name:"Ready for your private review",exact:true})).toBeVisible();
 page.once("dialog",d=>d.accept());await panel.getByRole("button",{name:"Revoke my likeness permission",exact:true}).click();
 await expect(jobPanel.getByLabel("Private Presenter output")).toHaveCount(0);await expect(jobPanel.getByRole("button",{name:"Accept generated video",exact:true})).toHaveCount(0);await expect(jobPanel.getByRole("button",{name:"Open generated video in editor",exact:true})).toHaveCount(0);await expect(jobPanel.getByRole("heading",{name:"Approval withdrawn",exact:true})).toHaveCount(4);
 receipt.checks.push("Revoking the likeness immediately removes private output, review/import/editor actions and shows readable invalidated job history");
 await page.screenshot({path:join(artifacts,"presenter-desktop.png"),fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:join(artifacts,"presenter-mobile.png"),fullPage:true});
 const final=await page.evaluate(()=>window.presenterFixture.snapshot());assert.equal(final.dispatches,4);assert(!JSON.stringify({profiles:final.profiles,drafts:final.drafts,jobs:final.jobs}).includes("X-Amz"));assert.equal(receipt.externalRequests.length,0);assert.equal(receipt.errors.length,0);
 receipt.checks.push("Desktop/mobile layouts fit; shared rows contain source IDs rather than signed URLs; all generation was isolated fixture state; no external live requests occurred");
 await writeFile(join(artifacts,"receipt.json"),JSON.stringify(receipt,null,2));console.log(JSON.stringify({...receipt,artifacts},null,2));
}catch(error){await page?.screenshot({path:join(artifacts,"failure.png"),fullPage:true}).catch(()=>{});console.error(JSON.stringify({...receipt,artifacts,error:String(error.stack)},null,2));throw error;}
finally{await browser?.close();await new Promise(done=>server?.close(done)??done());}
