import assert from "node:assert/strict";
import {mkdtemp,readFile,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,resolve,extname} from "node:path";
import {fileURLToPath} from "node:url";
import {createServer} from "node:http";
import {build} from "vite";
import {chromium,expect} from "@playwright/test";
import {execFileSync} from "node:child_process";
const root=fileURLToPath(new URL("../",import.meta.url)),artifacts=await mkdtemp(join(tmpdir(),"rendprop-production-")),dist=join(artifacts,"dist");
const receipt={proof:"Actual capture planning, editor recipes, cloud sync and review UI using synthetic media and isolated API fixtures. Database authority is covered separately.",checks:[],errors:[],externalRequests:[]};
const listing="20000000-0000-4000-8000-000000000002",editKey=`edit:${listing}`,planKey=`production:${listing}`;
let browser,server,page;
try{
  await build({configFile:false,root,publicDir:false,logLevel:"error",build:{outDir:dist,rollupOptions:{input:join(root,"tests/cloud-editor-fixture.html")}}});
  server=createServer(async(req,res)=>{const path=resolve(dist,`.${new URL(req.url,"http://localhost").pathname}`);if(!path.startsWith(`${dist}/`))return res.writeHead(400).end();try{res.setHeader("Content-Type",({".html":"text/html",".js":"application/javascript",".css":"text/css"})[extname(path)]??"application/octet-stream");res.end(await readFile(path));}catch{res.writeHead(404).end();}});
  await new Promise(done=>server.listen(0,"127.0.0.1",done));const origin=`http://127.0.0.1:${server.address().port}`;
  const voiceFile=join(artifacts,"review-narration.wav");
  execFileSync("ffmpeg",["-v","error","-f","lavfi","-i","sine=frequency=660:duration=4","-c:a","pcm_s16le",voiceFile]);
  const voiceBytes=await readFile(voiceFile),voiceURL=`https://${"a".repeat(32)}.r2.cloudflarestorage.com/fixture/narration.wav`;
  browser=await chromium.launch({headless:true,executablePath:process.env.STUDIO_BROWSER_EXECUTABLE});
  const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:"block"});
  await context.route("**/*",route=>{const url=new URL(route.request().url());if(url.href===voiceURL)return route.fulfill({status:200,contentType:"audio/wav",body:voiceBytes});if(url.origin===origin||["blob:","data:"].includes(url.protocol))return route.continue();receipt.externalRequests.push(url.href);return route.abort();});
  page=await context.newPage();page.on("pageerror",error=>receipt.errors.push(error.message));page.setDefaultTimeout(15000);
  await page.goto(`${origin}/tests/cloud-editor-fixture.html`);
  const capture=page.getByRole("region",{name:"Capture plan",exact:true});
  await expect(capture.getByRole("button",{name:/Listing highlight/})).toHaveAttribute("aria-pressed","true");
  await capture.getByRole("button",{name:"Open shot checklist"}).click();
  await capture.getByLabel("Set the scene status").selectOption("captured");
  await capture.getByLabel("Set the scene notes").fill("Use the steady afternoon view");
  await expect.poll(async()=> (await page.evaluate(()=>window.cloudFixture.snapshot())).documents[planKey]?.payload.shots[0].notes).toBe("Use the steady afternoon view");
  await capture.getByRole("button",{name:/Market update/}).click();
  await expect(capture.getByLabel("Set the scene notes")).toHaveValue("Use the steady afternoon view");
  await capture.getByRole("button",{name:/Listing highlight/}).click();
  await expect.poll(async()=> (await page.evaluate(()=>window.cloudFixture.snapshot())).documents[planKey]?.payload.recipe).toBe("listing-highlight");
  receipt.checks.push("Format selection, marked coverage and notes persist through CAS; changing formats retains completed work");
  const png=await page.evaluate(()=>{const canvas=document.createElement("canvas");canvas.width=640;canvas.height=360;const ctx=canvas.getContext("2d");ctx.fillStyle="#315b72";ctx.fillRect(0,0,640,360);return canvas.toDataURL().split(",")[1];});
  await page.getByLabel("Add photos or videos",{exact:true}).setInputFiles({name:"synthetic-room.png",mimeType:"image/png",buffer:Buffer.from(png,"base64")});
  await expect.poll(async()=> (await page.evaluate(()=>window.cloudFixture.snapshot())).documents[editKey]?.payload.sources.length).toBe(1);
  await page.getByRole("button",{name:"Build a guided draft",exact:true}).click();
  await page.getByRole("button",{name:"Apply guided draft",exact:true}).click();
  await page.getByRole("button",{name:"Pro view",exact:true}).click();
  await expect(page.getByLabel("Photo motion",{exact:true})).toHaveValue("push_in");
  await page.getByLabel("Saved narration",{exact:true}).selectOption("50000000-0000-4000-8000-000000000005");
  await expect(page.getByText(/Narration is ready/)).toBeVisible();
  const review=page.getByRole("region",{name:"Video review",exact:true});
  await expect(review.getByRole("button",{name:"Send saved version for review"})).toBeEnabled();
  await review.getByRole("button",{name:"Send saved version for review"}).click();
  await expect(review.locator(".production-state")).toContainText("Ready for review");
  await review.getByLabel("Feedback",{exact:true}).fill("Hold this opening view a little longer.");
  await review.getByLabel("Comment video time").fill("0:01");
  await review.getByRole("button",{name:"Add comment",exact:true}).click();
  await expect(review.getByText("Hold this opening view a little longer.",{exact:true})).toBeVisible();
  await review.getByRole("button",{name:"Approve this version"}).click();
  await expect(review.locator(".production-state")).toContainText("Approved");
  receipt.checks.push("Actual uploaded media becomes an editable guided draft; saved revision accepts timestamped feedback and approval");
  await page.getByLabel("Title overlay",{exact:true}).fill("A revised opening");
  await expect(review.locator(".production-state")).toContainText("Draft");
  await expect(review.getByText("Feedback on an earlier version").first()).toBeVisible();
  await review.getByRole("button",{name:"Send saved version for review"}).click();
  await page.getByRole("button",{name:"Open review queue",exact:true}).click();
  await page.getByRole("button",{name:"Open review",exact:true}).click();
  await page.getByRole("button",{name:"Preview this saved version"}).click();
  const preview=page.getByRole("region",{name:"Saved edit review",exact:true});
  await expect(preview).toBeVisible();await expect(preview.getByRole("button",{name:"Play",exact:true})).toBeEnabled();
  await expect(preview.getByRole("button",{name:/Export/})).toHaveCount(0);
  await expect(preview.getByLabel("Title overlay",{exact:true})).toHaveCount(0);
  await expect.poll(()=>page.evaluate(()=>window.cloudFixture.reviewNarrationCalls())).toBeGreaterThan(0);
  await expect(preview.getByText(/Restoring saved narration/)).toHaveCount(0);
  await page.evaluate(()=>{
    const original=HTMLMediaElement.prototype.play,context=new AudioContext(),connected=new WeakSet();
    let analyser;
    window.reviewAudioProbe={read:()=>{if(!analyser)return {rms:0,hz:0};const wave=new Float32Array(analyser.fftSize),frequency=new Float32Array(analyser.frequencyBinCount);analyser.getFloatTimeDomainData(wave);analyser.getFloatFrequencyData(frequency);let peak=1;for(let i=2;i<frequency.length;i++)if(frequency[i]>frequency[peak])peak=i;return {rms:Math.sqrt(wave.reduce((sum,value)=>sum+value*value,0)/wave.length),hz:peak*context.sampleRate/analyser.fftSize};},stop:()=>{HTMLMediaElement.prototype.play=original;void context.close();}};
    HTMLMediaElement.prototype.play=async function(){if(this.tagName==="AUDIO"&&!connected.has(this)){connected.add(this);analyser=context.createAnalyser();analyser.fftSize=4096;context.createMediaElementSource(this).connect(analyser);analyser.connect(context.destination);await context.resume();}return original.call(this);};
  });
  await preview.getByRole("button",{name:"Play",exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.reviewAudioProbe.read().rms)).toBeGreaterThan(.02);
  const sharedAudio=await page.evaluate(()=>window.reviewAudioProbe.read());assert(sharedAudio.hz>630&&sharedAudio.hz<690,`Shared preview narration frequency ${sharedAudio.hz}`);
  await preview.getByRole("button",{name:"Pause",exact:true}).click();await page.evaluate(()=>window.reviewAudioProbe.stop());
  receipt.checks.push(`Shared-review narration endpoint restores audio for readonly playback; real decoded output measured ${Math.round(sharedAudio.hz)}Hz and RMS ${sharedAudio.rms.toFixed(3)}`);
  receipt.checks.push("Editing clears approval; old feedback stays tagged; team queue previews the exact saved edit without mutation controls");
  await page.getByRole("button",{name:"Close selected review"}).click();
  await page.reload();
  await page.getByRole("button",{name:"Open shot checklist"}).click();
  await expect(page.getByLabel("Set the scene status")).toHaveValue("captured");
  await expect(page.getByLabel("Set the scene notes")).toHaveValue("Use the steady afternoon view");
  await expect(page.getByLabel("Title overlay",{exact:true})).toHaveValue("A revised opening");
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),"Production UI must not overflow the narrow screen");
  await page.screenshot({path:join(artifacts,"production-mobile.png"),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:join(artifacts,"production-desktop.png"),fullPage:true});
  receipt.checks.push("Capture plan and edit reopen with exact saved content; 390px layout does not overflow");
  const savedVersions=await page.evaluate(()=>window.cloudFixture.versions());
  const sourceVersion=savedVersions.map(([,snapshot])=>snapshot).filter(snapshot=>snapshot.version.key===editKey&&snapshot.version.reason==="submitted").sort((a,b)=>b.version.document_revision-a.version.document_revision)[0];
  const version=sourceVersion.version.document_revision;
  await page.getByLabel("Title overlay",{exact:true}).fill("Private agency changes");
  await expect.poll(async()=> (await page.evaluate(()=>window.cloudFixture.snapshot())).documents[editKey]?.payload.draft.title).toBe("Private agency changes");
  const beforeCopy=(await page.evaluate(()=>window.cloudFixture.snapshot())).documents[editKey];
  async function chooseOwnVersion(beforeRestore){
    const history=page.getByRole("region",{name:"Saved version history",exact:true});
    await history.getByRole("button",{name:"Open saved versions",exact:true}).click();
    await history.getByRole("button",{name:`View version ${version}`,exact:true}).click();
    if(beforeRestore)await beforeRestore();
    await history.getByRole("button",{name:"Restore this saved version",exact:true}).click();
    await expect(page.getByRole("button",{name:"Confirm copy to my edit",exact:true})).toBeVisible();
  }
  await chooseOwnVersion(()=>page.getByLabel("Brief for the edit",{exact:true}).fill("Brief flushed before the handoff"));
  assert.equal((await page.evaluate(()=>window.cloudFixture.snapshot())).documents[planKey].payload.notes,"Brief flushed before the handoff");
  await expect(page.getByLabel("Property reel",{exact:true})).toBeDisabled();
  await expect(page.locator('fieldset[aria-label="Property editing workspace"]')).toHaveJSProperty("disabled",true);
  await expect(page.locator('fieldset[aria-label="Property editing workspace"] textarea').first()).toBeDisabled();
  await page.evaluate(()=>window.cloudFixture.holdNextCopy());
  await page.getByRole("button",{name:"Confirm copy to my edit",exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.cloudFixture.pendingCopies())).toBe(1);
  await expect(page.getByRole("region",{name:"Confirm version handoff"})).toContainText("Editing and property switching are paused");
  await page.evaluate(()=>window.cloudFixture.releaseCopies());
  await expect(page.getByLabel("Title overlay",{exact:true})).toHaveValue("A revised opening");
  await expect.poll(()=>page.evaluate(key=>window.cloudFixture.snapshot().documents[key]?.revision,editKey)).toBe(beforeCopy.revision+1);
  const afterVersions=await page.evaluate(()=>window.cloudFixture.versions());
  assert.deepEqual(afterVersions.find(([,snapshot])=>snapshot.version.key===editKey&&snapshot.version.document_revision===beforeCopy.revision)[1].document.payload,beforeCopy.payload);
  assert.deepEqual(afterVersions.find(([id])=>id===savedVersions.find(([,snapshot])=>snapshot.version.id===sourceVersion.version.id)[0])[1],sourceVersion);
  receipt.checks.push("Immutable history restores an exact saved version through explicit confirmation; in-flight handoff locks inputs and archives the existing private edit without changing the source snapshot");
  for(const lostStatus of [0,408]){
  await chooseOwnVersion();
  await page.evaluate(status=>window.cloudFixture.loseNextCopy(status),lostStatus);
  const callsBefore=await page.evaluate(()=>window.cloudFixture.copyCalls());
  await page.getByRole("button",{name:"Confirm copy to my edit",exact:true}).click();
  await expect(page.getByRole("button",{name:"Open latest saved edit",exact:true})).toBeVisible();
  await expect(page.locator('fieldset[aria-label="Property editing workspace"]')).toHaveJSProperty("disabled",true);
  await expect(page.locator('fieldset[aria-label="Property editing workspace"] textarea').first()).toBeDisabled();
  await page.getByRole("button",{name:"Open latest saved edit",exact:true}).click();
  await expect(page.getByLabel("Title overlay",{exact:true})).toHaveValue("A revised opening");
  assert.equal(await page.evaluate(()=>window.cloudFixture.copyCalls()),callsBefore+1);
  }
  receipt.checks.push("Lost copy response and HTTP408 after commit both leave stale autosave locked; explicit server recovery reopens without retrying the mutation");
  await chooseOwnVersion();
  await page.evaluate(()=>window.cloudFixture.holdNextCopy());
  await page.getByRole("button",{name:"Confirm copy to my edit",exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.cloudFixture.pendingCopies())).toBe(1);
  await page.evaluate(id=>window.cloudFixture.remoteEdit(id),listing);
  await page.evaluate(()=>window.cloudFixture.releaseCopies());
  await expect(page.getByText(/Your saved target changed/)).toBeVisible();
  await expect(page.getByLabel("Title overlay",{exact:true})).toHaveValue("A revised opening");
  assert.equal((await page.evaluate(()=>window.cloudFixture.snapshot())).documents[editKey].payload.draft.title,"Saved on another device");
  receipt.checks.push("A concurrent target save wins CAS; the copy is rejected and the open private edit stays mounted for recovery");
  await page.evaluate(()=>window.cloudFixture.switchAccount());
  await expect(page.getByLabel("Title overlay",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Open review queue",exact:true}).click();
  await page.getByRole("button",{name:"Open review",exact:true}).click();
  const sharedHistory=page.locator('.production-review-dialog').getByRole("region",{name:"Saved version history",exact:true});
  await sharedHistory.getByRole("button",{name:"Open saved versions",exact:true}).click();
  await sharedHistory.getByRole("button",{name:`View version ${version}`,exact:true}).click();
  await sharedHistory.getByRole("button",{name:"Copy into my editable reel",exact:true}).click();
  await page.getByRole("button",{name:"Confirm copy to my edit",exact:true}).click();
  await expect(page.getByLabel("Title overlay",{exact:true})).toHaveValue("A revised opening");
  assert.equal((await page.evaluate(()=>window.cloudFixture.actorDocuments()))[editKey].payload.draft.title,"A revised opening");
  assert.equal((await page.evaluate(()=>window.cloudFixture.snapshot())).documents[editKey].payload.draft.title,"Saved on another device");
  receipt.checks.push("A different workspace member copies the earlier submitted version into their private editor while the author's newer private draft remains untouched");
  await page.evaluate(()=>window.cloudFixture.setRole("marketing"));
  await expect(page.getByRole("button",{name:"Copy into my editable reel",exact:true})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"Restore this saved version",exact:true})).toHaveCount(0);
  await expect(sharedHistory.getByText("Your workspace role can view saved versions.")).toBeVisible();
  receipt.checks.push("Marketing membership can read immutable history and briefs while copy/restore controls stay hidden");
  assert.deepEqual(receipt.errors,[]);assert.deepEqual(receipt.externalRequests,[]);receipt.status="passed";
}catch(error){receipt.status="failed";receipt.failure=String(error?.stack??error);if(page)await page.screenshot({path:join(artifacts,"failure.png"),fullPage:true}).catch(()=>{});throw error;}
finally{await writeFile(join(artifacts,"receipt.json"),JSON.stringify(receipt,null,2));console.log(JSON.stringify({artifacts,...receipt},null,2));await browser?.close();await new Promise(done=>server?server.close(done):done());}
