import { assert, assertEquals, assertRejects } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { memberPortfolio, portfolioReceipt } from "./portfolio.ts";
import { HttpError } from "../_shared/http.ts";
const actor="ca100601-0000-4000-8000-000000000001",org="ca100601-0000-4000-8000-000000000002",id="ca100601-0000-4000-8000-000000000003",listing="ca100602-0000-4000-8000-000000000001";
function fixture(data:unknown={user_id:actor,org_id:org,id:null,revision:0,listing_ids:[]},error:string|null=null){const calls:unknown[]=[];return{calls,admin:{rpc:async(name:string,args:unknown)=>{calls.push({name,args});return{data,error:error?{message:error}:null};}}};}
Deno.test("member portfolio starts empty and binds authenticated actor and explicit workspace",async()=>{const f=fixture();const r=await memberPortfolio(f.admin,actor,org);assertEquals(r.listing_ids,[]);assertEquals(r.portfolio_url,null);assertEquals(f.calls,[{name:"read_member_portfolio",args:{p_actor:actor,p_org:org}}]);});
Deno.test("member portfolio writes exact deliberate selection and preserves CAS revision",async()=>{const f=fixture({user_id:actor,org_id:org,id,revision:1,listing_ids:[listing]});const r=await memberPortfolio(f.admin,actor,org,{expected_revision:0,listing_ids:[listing]});assertEquals(f.calls,[{name:"save_member_portfolio",args:{p_actor:actor,p_org:org,p_expected:0,p_ids:[listing]}}]);assert(String(r.portfolio_url).endsWith(`/a/member-${id}`));assert(!String(r.portfolio_url).includes(actor));});
Deno.test("member portfolio refuses injected identity, duplicate selections and malformed revision before RPC",async()=>{for(const body of[{expected_revision:0,listing_ids:[],user_id:id},{expected_revision:0,listing_ids:[listing,listing]},{expected_revision:-1,listing_ids:[]},{expected_revision:0,listing_ids:["foreign"]},[],null]){const f=fixture();await assertRejects(()=>memberPortfolio(f.admin,actor,org,body),HttpError);assertEquals(f.calls,[]);}});
Deno.test("member portfolio fails closed on wrong actor/workspace/receipt and sanitizes DB outage",async()=>{for(const data of[{user_id:id,org_id:org,id,revision:1,listing_ids:[]},{user_id:actor,org_id:id,id,revision:1,listing_ids:[]},{user_id:actor,org_id:org,id,revision:1,listing_ids:[listing,listing]}])await assertRejects(async()=>portfolioReceipt(data,actor,org),HttpError);for(const[message,status]of[["RP409: selection changed",409],["RP403: removed member",403],["private database detail",503]]as const){try{await memberPortfolio(fixture(undefined,message).admin,actor,org);throw Error("accepted error");}catch(e){assert(e instanceof HttpError);assertEquals(e.status,status);if(status===503)assert(!e.message.includes("private database"));}}});

async function actualRoute() {
 const source=await Deno.readTextFile(new URL("./index.ts",import.meta.url)),start=source.indexOf("Deno.serve(async (req) => {"),end=source.indexOf("\n});",start)+5;
 assert(start>=0&&end>start);
 const body=source.slice(start,end).trimEnd().replace("Deno.serve(async (req) => {","export const handler=async(req:Request)=>{").replace(/\n\}\);$/,"\n};");
 const code=`import{HttpError,assert,json,pathSegments,readJsonLimited,respondError}from ${JSON.stringify(new URL("../_shared/http.ts",import.meta.url).href)};import{handleOptions}from ${JSON.stringify(new URL("../_shared/cors.ts",import.meta.url).href)};import{requestedWorkspace}from ${JSON.stringify(new URL("../_shared/workspaces.ts",import.meta.url).href)};import{memberPortfolio}from ${JSON.stringify(new URL("./portfolio.ts",import.meta.url).href)};export const state:any={actor:${JSON.stringify(actor)},calls:[]};const getUser=async()=>{if(!state.actor)throw new HttpError(401,"Sign in required");return{id:state.actor}};const adminClient=()=>({rpc:async(name:string,args:any)=>{state.calls.push({name,args});return{error:null,data:{user_id:args.p_actor,org_id:args.p_org,id:null,revision:0,listing_ids:[]}}}});${body}`;
 return import("data:application/typescript;base64,"+btoa(String.fromCharCode(...new TextEncoder().encode(code))));
}
Deno.test("actual /me portfolio dispatch requires Auth, explicit workspace, exact method and exact field body",async()=>{
 const f=await actualRoute();
 for(const account of[actor,id]){f.state.actor=account;f.state.calls=[];const response=await f.handler(new Request("https://fixture.invalid/me/portfolio",{headers:{"X-Org-Id":org}}));assertEquals(response.status,200);assertEquals((await response.json()).user_id,account);assertEquals(f.state.calls,[{name:"read_member_portfolio",args:{p_actor:account,p_org:org}}]);}
 for(const request of[new Request("https://fixture.invalid/me/portfolio"),new Request("https://fixture.invalid/me/portfolio",{headers:{"X-Org-Id":"foreign"}}),new Request("https://fixture.invalid/me/portfolio",{method:"POST",headers:{"X-Org-Id":org}}),new Request("https://fixture.invalid/me/portfolio",{method:"PUT",headers:{"X-Org-Id":org},body:JSON.stringify({expected_revision:0,listing_ids:[],user_id:actor})})]){f.state.calls=[];assert([400,405,409].includes((await f.handler(request)).status));assertEquals(f.state.calls,[]);}
 f.state.actor=null;assertEquals((await f.handler(new Request("https://fixture.invalid/me/portfolio",{headers:{"X-Org-Id":org}}))).status,401);
});
